#include "mtp_ep.h"

#include <linux/tcp.h>

#include "tcp_in.h"
#include "tcp_out.h"
#include "timer.h"
#include "tcp_stream.h"
#include "fhash.h"
#include "debug.h"
#include "ip_out.h"
#include "tcp_util.h"
#include "socket.h"
#include "mtp_instr.h"
#include "mtp_net.h"
#include "mtp_seq.h"

#define MAX(a, b) ((a)>(b)?(a):(b))
#define MIN(a, b) ((a)<(b)?(a):(b))
#define TCP_MAX_WINDOW 65535

// Intermediate output
typedef struct scratchpad_decl {
	uint8_t change_cwnd;
	bool skip_ack_eps;
	bool expecting_ack;
} scratchpad;


// Helper functions
/*----------------------------------------------------------------------------*/
static inline void EstimateRTT(mtcp_manager_t mtcp, tcp_stream *cur_stream, uint32_t mrtt)
{
	/* This function should be called for not retransmitted packets */
	/* TODO: determine tcp_rto_min */
#define TCP_RTO_MIN 0
	long m = mrtt;
	uint32_t tcp_rto_min = TCP_RTO_MIN;
	struct tcp_recv_vars *rcvvar = cur_stream->rcvvar;

	if (m == 0) {
		m = 1;
	}
	if (rcvvar->srtt != 0) {
		/* rtt = 7/8 rtt + 1/8 new */
		m -= (rcvvar->srtt >> 3);
		rcvvar->srtt += m;
		if (m < 0) {
			m = -m;
			m -= (rcvvar->mdev >> 2);
			if (m > 0) {
				m >>= 3;
			}
		} else {
			m -= (rcvvar->mdev >> 2);
		}
		rcvvar->mdev += m;
		if (rcvvar->mdev > rcvvar->mdev_max) {
			rcvvar->mdev_max = rcvvar->mdev;
			if (rcvvar->mdev_max > rcvvar->rttvar) {
				rcvvar->rttvar = rcvvar->mdev_max;
			}
		}
		if (TCP_SEQ_GT(cur_stream->mtp->send_una, rcvvar->rtt_seq)) {
			if (rcvvar->mdev_max < rcvvar->rttvar) {
				rcvvar->rttvar -= (rcvvar->rttvar - rcvvar->mdev_max) >> 2;
			}
			rcvvar->rtt_seq = cur_stream->mtp->send_next;
			rcvvar->mdev_max = tcp_rto_min;
		}
	} else {
		/* fresh measurement */
		rcvvar->srtt = m << 3;
		rcvvar->mdev = m << 1;
		rcvvar->mdev_max = rcvvar->rttvar = MAX(rcvvar->mdev, tcp_rto_min);
		rcvvar->rtt_seq = cur_stream->mtp->send_next;
	}

	TRACE_RTT("mrtt: %u (%uus), srtt: %u (%ums), mdev: %u, mdev_max: %u, "
			"rttvar: %u, rtt_seq: %u\n", mrtt, mrtt * TIME_TICK, 
			rcvvar->srtt, TS_TO_MSEC((rcvvar->srtt) >> 3), rcvvar->mdev, 
			rcvvar->mdev_max, rcvvar->rttvar, rcvvar->rtt_seq);
}


/***********************************************
 MTP Event Processors
 
 EPs are static and used only by MTP EP chains
 They have 1-to-1 mappings to mtp code
 They should be generated by the MTP compiler
 ***********************************************/
static inline void send_ep(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream *cur_stream)
{
	struct tcp_send_vars *sndvar = cur_stream->sndvar;

    if (cur_stream->mtp->state != MTP_TCP_ESTABLISHED_ST) return;

	struct mtp_ctx *ctx = cur_stream->mtp;
	
	// MTP_PRINT("send_ep before grabbing lock\n");
	SBUF_LOCK(&sndvar->write_lock);
	// MTP_PRINT("send_ep after grabbing lock\n");

	// MTP_PRINT("in send ep\n");
	if ((!sndvar->sndbuf0 || sndvar->sndbuf0->len == 0) &&
		(!sndvar->sndbuf1 || sndvar->sndbuf1->len == 0)) {
		// MTP_PRINT("send_ep before releasing lock\n");
        SBUF_UNLOCK(&sndvar->write_lock);
        return;
	}

	MTP_PRINT("****************************\n");
	MTP_PRINT("Conn %u in send ep\n", cur_stream->id);

	// Calculate how much can we send from stream 0
	int data_rest0 = sndvar->sndbuf0->len - 
					MTP_SEQ_SUB(ctx->s0.send_next, sndvar->sndbuf0->head_seq, 
								sndvar->sndbuf0->head_seq);
	int in_flight0 = MTP_SEQ_SUB(ctx->s0.send_next, ctx->s0.send_una, 
								ctx->s0.send_una); 
	int recv_wnd0 = ctx->s0.last_rwnd_remote - in_flight0;
	int bytes_to_send0 = MIN(data_rest0, recv_wnd0);

	MTP_PRINT("data_rest0: %d, recv_wnd0: %d, bytes_to_send0: %d\n", 
			data_rest0, recv_wnd0, bytes_to_send0);

	// Calculate how much can we send from stream 1
	int data_rest1 = sndvar->sndbuf1->len - 
					MTP_SEQ_SUB(ctx->s1.send_next, sndvar->sndbuf1->head_seq, 
								sndvar->sndbuf1->head_seq);
	int in_flight1 = MTP_SEQ_SUB(ctx->s1.send_next, ctx->s1.send_una, 
								ctx->s1.send_una);
	int recv_wnd1 = ctx->s1.last_rwnd_remote - in_flight1;
	int bytes_to_send1 = MIN(data_rest1, recv_wnd1);

	MTP_PRINT("data_rest1: %d, recv_wnd1: %d, bytes_to_send1: %d\n", 
			data_rest1, recv_wnd1, bytes_to_send1);


	// Calculate total to send
	int remaining_in_cwnd = ctx->cwnd_size - (in_flight0 + in_flight1);
	int total_bytes_to_send = MIN(bytes_to_send0 + bytes_to_send1, 
							remaining_in_cwnd);
	MTP_PRINT("cwnd_size: %u, in_flight0: %u, in_flight1: %u, "
			"bytes_to_send: %d\n", 
			ctx->cwnd_size, in_flight0, in_flight1, bytes_to_send);
	
	// MTP: maps to bytes_to_send
	// int data_rest = sndvar->sndbuf->len - 
	// 				MTP_SEQ_SUB(ctx->send_next, sndvar->sndbuf->head_seq, 
	// 							sndvar->sndbuf->head_seq);
	// int window_avail = MIN(ctx->cwnd_size, ctx->last_rwnd_remote) - 
	// 				   MTP_SEQ_SUB(ctx->send_next, ctx->send_una, ctx->send_una);

    // int bytes_to_send = MIN(data_rest, window_avail);

	// MTP_PRINT("send_ep cwnd_size: %u, last_rwnd_remote: %u, "
	// 		"send_next: %u, send_una: %u\n", 
	// 		ctx->cwnd_size, ctx->last_rwnd_remote, ctx->send_next, 
	// 		ctx->send_una);
	// MTP_PRINT("send_ep bytes to send: %d, data_rest: %d, window_avail: %d\n", 
	// 		bytes_to_send, data_rest, window_avail);

	if (total_bytes_to_send <= 0) {
		// MTP_PRINT("send_ep before releasing lock\n");
		SBUF_UNLOCK(&sndvar->write_lock);
		// MTP_PRINT("send_ep after releasing lock\n");
        return;
	}

	MTP_PRINT("send_ep bytes to send: %d\n", bytes_to_send);
	// MTP: maps to packet blueprint creation
	
	// Decide which stream should go first
	// a little hacky because assumes seq starts from 0.
	uint32_t sent_from_s0 = ctx->s0.send_next;
	uint32_t sent_from_s1 = ctx->s1.send_next;

	uint8_t first_stream = 0;
	struct mtp_ctx_stream* first_stream_ctx = &ctx->s0;
	struct tcp_send_buffer* first_stream_buf = sndvar->sndbuf0;
	int first_bytes_to_send = bytes_to_send0;

	uint8_t next_stream = 1;
	struct mtp_ctx_stream* next_stream_ctx = &ctx->s1;
	struct tcp_send_buffer* next_stream_buf = sndvar->sndbuf1;
	int next_bytes_to_send = bytes_to_send1;

	if ( (sent_from_s0 > sent_from_s1 + MTP_QUIC_SCHED_CHUNK) ||
		 bytes_to_send0 <= 0){
		first_stream = 1;
		first_stream_ctx = &ctx->s1;
		first_stream_buf = sndvar->sndbuf1;
		first_bytes_to_send = bytes_to_send1;

		next_stream = 0;
		next_stream_ctx = &ctx->s0;
		next_stream_buf = sndvar->sndbuf0;
		next_bytes_to_send = bytes_to_send0;
	}

	int bytes_from_first = MIN(first_bytes_to_send, remaining_in_cwnd);
	int bytes_from_next = 0;
	if (bytes_from_first < remaining_in_cwnd){
		bytes_from_next = MIN(next_bytes_to_send, (remaining_in_cwnd - bytes_from_first));
	}

	// Generating from first
	{
		mtp_bp* bp;
		bool data_merging = FALSE;
		bool ack_merging = FALSE;

		if (!BPBuffer_isempty(cur_stream)){
			mtp_bp* last_bp = GetLastBP(cur_stream);
			uint32_t next_sched_byte = ntohl(last_bp->hdr.seq) + last_bp->payload.len;
			if (last_bp->hdr.urg_ptr == ntohs(first_stream) &&
				last_bp->payload.len > 0 && 
				first_stream_ctx->send_next == next_sched_byte){
				MTP_PRINT("merging, prev blueprint is:");
				print_MTP_bp(last_bp);
				bp = last_bp;
				data_merging = FALSE;
				// data_merging = TRUE;
			}
			else if (last_bp->hdr.urg_ptr == ntohs(first_stream) &&
					last_bp->payload.len == 0 &&
					last_bp->hdr.ack == TRUE &&
					last_bp->hdr.fin == FALSE &&
					last_bp->hdr.syn == FALSE) {
				MTP_PRINT("merging, prev blueprint is:");
				print_MTP_bp(last_bp);
				bp = last_bp;
				ack_merging = TRUE;
			}
		}

		if (!data_merging && !ack_merging){
			bp = GetFreeBP(cur_stream);	
		} 
		MTP_PRINT("got bp\n");
		MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		if (!data_merging && !ack_merging){
			memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));
		}

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;

		if (!data_merging){
			bp->hdr.seq = htonl(first_stream_ctx->send_next);
		}

		MTP_PRINT("Seq in send_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(first_stream_ctx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;
		bp->hdr.urg_ptr = ntohs(first_stream); // indicate which stream this bp is for

		// options to calculate data offset
	
		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		
	
		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint8_t wscale = ctx->wscale;
		uint32_t window32 = first_stream_ctx->rwnd_size >> wscale;  
		// MTP TODO: fix this
		uint16_t advertised_window = (uint16_t)MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) first_stream_ctx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		if (!data_merging){
			// uint8_t *data = sndvar->sndbuf->head + MTP_SEQ_SUB(ctx->send_next,
			// 												sndvar->sndbuf->head_seq,
			// 												sndvar->sndbuf->head_seq);
			// bp->payload.data = data;
			uint32_t buf_offset = MTP_SEQ_SUB(first_stream_ctx->send_next,
													first_stream_buf->head_seq,
													first_stream_buf->head_seq);

			if (first_stream_buf->head_off + buf_offset > first_stream_buf->size){
				// struct tcp_send_buffer* buf = sndvar->sndbuf;
				uint32_t first_half = first_stream_buf->size - first_stream_buf->head_off;
				uint32_t second_half = buf_offset - first_half;
				uint32_t go_back = first_stream_buf->head_off - second_half;
				bp->payload.data = first_stream_buf->head - go_back;
				bp->payload.wraps_around = FALSE;
			}
			else {
				uint8_t *data = first_stream_buf->head + buf_offset;
				bp->payload.data = data;

				// struct tcp_send_buffer* buf = sndvar->sndbuf;
				if (first_stream_buf->head_off + buf_offset + bytes_from_first > 
					first_stream_buf->size){
					uint32_t start = first_stream_buf->head_off + buf_offset;
					uint32_t first_half = first_stream_buf->size - start;
					bp->payload.wraps_around = TRUE;
					bp->payload.wrap_around_seg = first_stream_ctx->send_next + first_half;
					bp->payload.wrap_around_data = first_stream_buf->data;
				}
			}
		}

		if (data_merging){
			bp->payload.len += bytes_from_first;
		}
		else {
			bp->payload.len = bytes_from_first;
		}

		if (bp->payload.len > ctx->eff_SMSS){
			bp->payload.needs_segmentation = TRUE;
			bp->payload.seg_size = ctx->eff_SMSS;
			bp->payload.seg_rule_group_id = 1; 
		}

		MTP_PRINT("Generated bp:\n");
		print_MTP_bp(bp);

		first_stream_ctx->send_next += bytes_from_first;
		MTP_PRINT("send next for stream %d: %u\n", first_stream, 
												first_stream_ctx->send_next);
	}
    
	
	// Generating from next
	if (bytes_from_next > 0){
		mtp_bp* bp;
		bool data_merging = FALSE;
		bool ack_merging = FALSE;

		if (!BPBuffer_isempty(cur_stream)){
			mtp_bp* last_bp = GetLastBP(cur_stream);
			uint32_t next_sched_byte = ntohl(last_bp->hdr.seq) + last_bp->payload.len;
			if (last_bp->hdr.urg_ptr == ntohs(next_stream) &&
				last_bp->payload.len > 0 && 
				next_stream_ctx->send_next == next_sched_byte){
				MTP_PRINT("merging, prev blueprint is:");
				print_MTP_bp(last_bp);
				bp = last_bp;
				data_merging = FALSE;
				// data_merging = TRUE;
			}
			else if (last_bp->hdr.urg_ptr == ntohs(next_stream) &&
					last_bp->payload.len == 0 &&
					last_bp->hdr.ack == TRUE &&
					last_bp->hdr.fin == FALSE &&
					last_bp->hdr.syn == FALSE) {
				MTP_PRINT("merging, prev blueprint is:");
				print_MTP_bp(last_bp);
				bp = last_bp;
				ack_merging = TRUE;
			}
		}

		if (!data_merging && !ack_merging){
			bp = GetFreeBP(cur_stream);	
		} 
		MTP_PRINT("got bp\n");
		MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		if (!data_merging && !ack_merging){
			memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));
		}

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;

		if (!data_merging){
			bp->hdr.seq = htonl(next_stream_ctx->send_next);
		}

		MTP_PRINT("Seq in send_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(next_stream_ctx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;
		bp->hdr.urg_ptr = ntohs(next_stream); // indicate which stream this bp is for

		// options to calculate data offset
	
		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		
	
		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint8_t wscale = ctx->wscale;
		uint32_t window32 = next_stream_ctx->rwnd_size >> wscale;  
		// MTP TODO: fix this
		uint16_t advertised_window = (uint16_t)MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) next_stream_ctx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		if (!data_merging){
			// uint8_t *data = sndvar->sndbuf->head + MTP_SEQ_SUB(ctx->send_next,
			// 												sndvar->sndbuf->head_seq,
			// 												sndvar->sndbuf->head_seq);
			// bp->payload.data = data;
			uint32_t buf_offset = MTP_SEQ_SUB(next_stream_ctx->send_next,
													next_stream_buf->head_seq,
													next_stream_buf->head_seq);

			if (next_stream_buf->head_off + buf_offset > next_stream_buf->size){
				// struct tcp_send_buffer* buf = sndvar->sndbuf;
				uint32_t first_half = next_stream_buf->size - next_stream_buf->head_off;
				uint32_t second_half = buf_offset - first_half;
				uint32_t go_back = next_stream_buf->head_off - second_half;
				bp->payload.data = next_stream_buf->head - go_back;
				bp->payload.wraps_around = FALSE;
			}
			else {
				uint8_t *data = next_stream_buf->head + buf_offset;
				bp->payload.data = data;

				// struct tcp_send_buffer* buf = sndvar->sndbuf;
				if (next_stream_buf->head_off + buf_offset + bytes_from_next > 
					next_stream_buf->size){
					uint32_t start = next_stream_buf->head_off + buf_offset;
					uint32_t first_half = next_stream_buf->size - start;
					bp->payload.wraps_around = TRUE;
					bp->payload.wrap_around_seg = next_stream_ctx->send_next + first_half;
					bp->payload.wrap_around_data = next_stream_buf->data;
				}
			}
		}

		if (data_merging){
			bp->payload.len += bytes_from_next;
		}
		else {
			bp->payload.len = bytes_from_next;
		}

		if (bp->payload.len > ctx->eff_SMSS){
			bp->payload.needs_segmentation = TRUE;
			bp->payload.seg_size = ctx->eff_SMSS;
			bp->payload.seg_rule_group_id = 1; 
		}

		MTP_PRINT("Generated bp:\n");
		print_MTP_bp(bp);

		next_stream_ctx->send_next += bytes_from_next;
		MTP_PRINT("send next for stream %d: %u\n", next_stream, 
												next_stream_ctx->send_next);
	}
	
	
	AddtoGenList(mtcp, cur_stream, cur_ts);	
	
	// MTP_PRINT("preprared bp:\n");
	// print_MTP_bp(bp);
	// MTP_PRINT("head ptr: %p, head seq: %d, len: %d\n", sndvar->sndbuf->head, 
	// 		sndvar->sndbuf->head_seq, sndvar->sndbuf->len);

	// MTP TODO: implement + for MTP_SEQ
	


	// MTP TODO: map to timer event with event input
	TimerStart(mtcp, cur_stream, cur_ts);

	// MTP_PRINT("send_ep before releasing lock\n");
	SBUF_UNLOCK(&sndvar->write_lock);
	// MTP_PRINT("send_ep after releasing lock\n");
	return;
}

static inline int receive_ep(mtcp_manager_t mtcp, socket_map_t socket, 
								bool non_block, char *ev_buf, int ev_data_size, 
								uint8_t stream_id, tcp_stream *cur_stream)
{
	struct mtp_ctx* ctx = cur_stream->mtp;
	struct tcp_recv_vars *rcvvar = cur_stream->rcvvar;

	struct tcp_ring_buffer *rcvbuf = rcvvar->rcvbuf0;
	if (stream_id == 1){
		rcvbuf = rcvvar->rcvbuf1;
	}

	if (ctx->state == MTP_TCP_CLOSE_WAIT_ST) {
		if (!rcvbuf)
			return 0;
		
		if (rcvbuf->merged_len == 0)
			return 0;

	}
	
	/* return EAGAIN if no receive buffer */
	if (non_block) {
		if (!rcvbuf || rcvbuf->merged_len == 0) {
			errno = EAGAIN;
			return -1;
		}
	}

	struct mtp_ctx_stream *stx = &ctx->s0;
	if (stream_id == 1){
		stx = &ctx->s1;
	}
	MTP_PRINT("receive_ep: ev_data_sizse: %d, "
			"cur_stream->mtp->recv_next: %u, "
			"cur_stream->mtp->last_flushed: %u\n", 
			ev_data_size, stx->recv_next, stx->last_flushed);

	uint32_t recv_next = stx->recv_next;
	// TODO: FIN HANDLING
	if (ctx->state == MTP_TCP_CLOSE_WAIT_ST){
		recv_next--;
	}
	uint32_t data_avail = MTP_SEQ_SUB(recv_next, 
									 stx->last_flushed, 
									 stx->last_flushed) - 1;
    if (data_avail > ev_data_size){
        data_avail = ev_data_size;
    }

	MTP_PRINT("data_avail: %u\n", data_avail);

	int ret = FlushAndNotify(mtcp, socket, cur_stream, ev_buf, data_avail,
							 stream_id);
    
    stx->last_flushed += data_avail;
	stx->rwnd_size = rcvbuf->size - (MTP_SEQ_SUB(recv_next, 
													stx->last_flushed, 
													stx->last_flushed) - 1);
	
	// MTP TODO: I think this has race conditions
	
	if (socket->epoll & MTCP_EPOLLIN) {
		if (!(socket->epoll & MTCP_EPOLLET) && recv_next > stx->last_flushed + 1) {
			if (socket->epoll) {
				AddEpollEvent(mtcp->ep, USR_SHADOW_EVENT_QUEUE, socket, MTCP_EPOLLIN,
							 stream_id);
			}
		}
	}

	return ret;
	// TODO: send ack when window becomes non zero after being zero (part 2)
}

static inline void timestamp_ep(mtcp_manager_t mtcp, uint32_t cur_ts, 
		struct tcp_opt_timestamp* ev_ts, tcp_stream* cur_stream, scratchpad* scratch)
{
	struct mtp_ctx *ctx = cur_stream->mtp;
	
	if (ev_ts->valid) {
		// MTP TODO: do we need MTP_SEQ_LT here?
		if (ev_ts->value1 < ctx->ts_recent) {
			/* TODO: ts_recent should be invalidated 
					 before timestamp wraparound for long idle flow */
			MTP_PRINT("PAWS Detect wrong timestamp. "
					"ts_val: %u, prev: %u\n", 
					ev_ts->value1, ctx->ts_recent);
			// EnqueueACK(mtcp, cur_stream, cur_ts, ACK_OPT_NOW);
			return;
		} else {
			/* valid timestamp */
			if (ev_ts->value1 > ctx->ts_recent) {
				TRACE_TSTAMP("Timestamp update. cur: %u, prior: %u "
					"(time diff: %uus)\n", 
					ev_ts->value1, ctx->ts_recent, 
					TS_TO_USEC(cur_ts - ctx->ts_last_ts_upd));
				ctx->ts_last_ts_upd = cur_ts;
			}

			ctx->ts_recent = ev_ts->value1;
			ctx->ts_lastack_rcvd = ev_ts->value2;
			// MTP TODO: integrate with MTP
			cur_stream->rcvvar->ts_lastack_rcvd = ev_ts->value2;
		}
	}
	else {
		MTP_PRINT("timestamp_ep: no valid timestamp\n");
	}
}
static inline void conn_ack_ep ( mtcp_manager_t mtcp, int32_t cur_ts, uint32_t ev_ack_seq, 
        uint32_t ev_seq, tcp_stream* cur_stream, 
		uint8_t stream_id, scratchpad* scratch){

	// MTP_PRINT("----------------------------- Ack: %u\n", ev_ack_seq);

	struct mtp_ctx *ctx = cur_stream->mtp;

    if (ctx->state == MTP_TCP_SYNACK_SENT_ST &&
        ev_ack_seq == ctx->init_seq + 1){
        ctx->state = MTP_TCP_ESTABLISHED_ST;
        
		ctx->s0.send_una += 1;
        ctx->s0.send_next = ev_ack_seq;
        ctx->s0.last_ack = ev_ack_seq;

		ctx->s1.send_una += 1;
        ctx->s1.send_next = ev_ack_seq;
        ctx->s1.last_ack = ev_ack_seq;

        if (ctx->cwnd_size == 1){
            ctx->cwnd_size = 2 * ctx->SMSS;
        }
        else {
            ctx->cwnd_size = ctx->SMSS;
        }

		ctx->s0.lwu_seq = ev_seq;
		ctx->s0.lwu_ack = ev_ack_seq;

		ctx->s1.lwu_seq = ev_seq;
		ctx->s1.lwu_ack = ev_ack_seq;

        scratch->skip_ack_eps = TRUE;
		// MTP TODO: timer
        TimerCancel(mtcp, cur_stream);

        // MTP TODO: Raise an event to the listening socket
		struct mtp_listen_ctx *listen_ctx = 
			(struct mtp_listen_ctx *)ListenerHTSearch(mtcp->listeners, &cur_stream->sport);
		if (listen_ctx->socket && (listen_ctx->socket->epoll & MTCP_EPOLLIN)) {
			AddEpollEvent(mtcp->ep, MTCP_EVENT_QUEUE, listen_ctx->socket, MTCP_EPOLLIN,
						  MTP_QUIC_SHARED);
		}
    }
    else {
        scratch->skip_ack_eps = FALSE;
		// MTP_PRINT("conn_ack, no skip: lwu_seq: %u, lwu_ack: %u, rwindow: %u\n", cur_stream->mtp->lwu_seq,
		// 							   cur_stream->mtp->lwu_ack,
		// 							   cur_stream->mtp->last_rwnd_remote);
    }

	
}

static inline void rto_ep( mtcp_manager_t mtcp, int32_t cur_ts, uint32_t ev_ack_seq, 
    tcp_stream* cur_stream, scratchpad* scratch)
{
    if (scratch->skip_ack_eps) return;

	// if (cur_stream->mtp->state != MTP_TCP_ESTABLISHED_ST) return;

    struct mtp_ctx* ctx = cur_stream->mtp;
	if (ctx->state == MTP_TCP_FIN_WAIT_1_ST || 
		ctx->state == MTP_TCP_FIN_WAIT_2_ST ||
		ctx->state == MTP_TCP_CLOSING_ST || 
		ctx->state == MTP_TCP_CLOSE_WAIT_ST || 
		ctx->state == MTP_TCP_LAST_ACK_ST) {
		if (ctx->fin_sent && ev_ack_seq == ctx->final_seq + 1) {
			ev_ack_seq--;
		}
	}

	struct mtp_ctx_stream* stx = &ctx->s0;
	if (stream_id == 1){
		stx = &ctx->s1;
	}
	
    if(MTP_SEQ_LT(ev_ack_seq, stx->send_una, stx->send_una) || 
	   MTP_SEQ_LT(stx->send_next, ev_ack_seq, stx->send_una)) {
		scratch->skip_ack_eps = TRUE;
		return;
	}
    
	// MTP TODO: make consistent with MTP
    // Set RTO, using RTT calculation logic from mTCP
	uint32_t rmlen = MTP_SEQ_SUB(ev_ack_seq, stx->send_una, stx->send_una);
	if (rmlen > 0){
		struct tcp_send_vars *sndvar = cur_stream->sndvar;
		struct tcp_recv_vars *rcvvar = cur_stream->rcvvar;
		uint32_t rtt = cur_ts - rcvvar->ts_lastack_rcvd;
		// printf("Stream %u, rtt: %u, last_ack_ts:%u\n", 
		// 		cur_stream->id, rtt, rcvvar->ts_lastack_rcvd);
		EstimateRTT(mtcp, cur_stream, rtt);
		#ifndef MTP_FIXED_RTO
		sndvar->rto = (rcvvar->srtt >> 3) + rcvvar->rttvar;
		#else
		sndvar->rto = 3;
		#endif
	}
}

static inline void fast_retr_rec_ep(mtcp_manager_t mtcp, uint32_t cur_ts, 
								    uint32_t ev_ack_seq, uint8_t stream_id,
									tcp_stream* cur_stream, 
									scratchpad* scratch)
{
	if(scratch->skip_ack_eps) return;
	// if (cur_stream->mtp->state != MTP_TCP_ESTABLISHED_ST) return;

    struct mtp_ctx* ctx = cur_stream->mtp;
	if (ctx->state == MTP_TCP_FIN_WAIT_1_ST || 
		ctx->state == MTP_TCP_FIN_WAIT_2_ST ||
		ctx->state == MTP_TCP_CLOSING_ST || 
		ctx->state == MTP_TCP_CLOSE_WAIT_ST || 
		ctx->state == MTP_TCP_LAST_ACK_ST) {
		if (ctx->fin_sent && ev_ack_seq == ctx->final_seq + 1) {
			ev_ack_seq--;
		}
	}

	struct tcp_send_vars *sndvar = cur_stream->sndvar;
	struct tcp_send_buffer* sndbuf = sndvar->sndbuf0;
	if (stream_id == 1){
		sndbuf = sndvar->sndbuf1;
	}
	struct mtp_ctx_stream* stx = &ctx->s0;
	struct mtp_ctx_stream* stx_other = &ctx->s1;
	if (stream_id == 1){
		stx = &ctx->s1;
		stx_other = &ctx->s0;
	}

	SBUF_LOCK(&sndvar->write_lock);
	uint32_t data_rest =  sndbuf->len - 
					      MTP_SEQ_SUB(stx->send_next, sndbuf->head_seq,
									  sndbuf->head_seq);
	SBUF_UNLOCK(&sndvar->write_lock);

	scratch->expecting_ack = TRUE;
	if (data_rest == 0 && stx->send_una == stx->send_next) {
		scratch->expecting_ack = FALSE;
		return;
	}

	scratch->change_cwnd = 1;

	// MTP_PRINT("fast_retr BEFORE: cwnd:%u, ssthresh:%u\n", ctx->cwnd_size, ctx->ssthresh);
	if(ev_ack_seq == stx->last_ack) {
		stx->duplicate_acks = stx->duplicate_acks + 1;

		scratch->change_cwnd = 0;

		if(stx->duplicate_acks == 1) {
			stx->flightsize_dupl = MTP_SEQ_SUB(stx->send_next, 
											   stx->send_una, 
											   stx->send_una);
		}

		if(stx->duplicate_acks == 3) {
			// MTP congestion window resize
			uint32_t other_flight_size = MTP_SEQ_SUB(stx_other->send_next, 
											   stx_other->send_una, 
											   stx_other->send_una);
            uint32_t opt1 = stx->flightsize_dupl/2 + other_flight_size;
            uint32_t opt2 = 2 * stx->SMSS;
            if (opt1 >= opt2) ctx->ssthresh = opt1;
            else ctx->ssthresh = opt2;
			
            ctx->cwnd_size = ctx->ssthresh + ctx->SMSS;
		}

		if(stx->duplicate_acks != 3) {
			ctx->cwnd_size += ctx->SMSS;
		}
	} else {
		if(stx->duplicate_acks >= 3) {
			ctx->cwnd_size = ctx->ssthresh;
		}
		stx->duplicate_acks = 0;
		stx->last_ack = ev_ack_seq;
	}
	// MTP_PRINT("fast_retr AFTER: cwnd:%u, ssthresh:%u\n", ctx->cwnd_size, ctx->ssthresh);
}

static inline void slows_congc_ep(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t ev_ack_seq, 
				uint8_t stream_id,
				tcp_stream* cur_stream, scratchpad* scratch)
{
	if(scratch->skip_ack_eps) return;
	// if (cur_stream->mtp->state != MTP_TCP_ESTABLISHED_ST) return;
    struct mtp_ctx *ctx = cur_stream->mtp;

	if (ctx->state == MTP_TCP_FIN_WAIT_1_ST || 
		ctx->state == MTP_TCP_FIN_WAIT_2_ST ||
		ctx->state == MTP_TCP_CLOSING_ST || 
		ctx->state == MTP_TCP_CLOSE_WAIT_ST || 
		ctx->state == MTP_TCP_LAST_ACK_ST) {
		if (ctx->fin_sent && ev_ack_seq == ctx->final_seq + 1) {
			ev_ack_seq--;
		}
	}

	if (!scratch->expecting_ack) return;

	// MTP_PRINT("before DIV\n");
	// MTP_PRINT("slows_cong BEFORE: cwnd:%u\n", ctx->cwnd_size);

	struct mtp_ctx_stream* stx = &ctx->s0;
	if (stream_id == 1){
		stx = &ctx->s1;
	}

	if(scratch->change_cwnd) {
		uint32_t rmlen = MTP_SEQ_SUB(ev_ack_seq, stx->send_una, stx->send_una);
		// MTP_PRINT("rmlen: %u, eff_SMSS: %u\n", rmlen, ctx->eff_SMSS);
		uint16_t packets = rmlen / ctx->eff_SMSS;
		// MTP_PRINT("after\n");
		if (packets * ctx->eff_SMSS > rmlen) {
			packets++;
		}

		if (ctx->cwnd_size < ctx->ssthresh) {
			ctx->cwnd_size += (ctx->SMSS * packets);
		} else {
			// MTP_PRINT("SMSS: %u, cwnd: %u\n", ctx->SMSS, ctx->cwnd_size);
			uint32_t add_cwnd = packets * ctx->SMSS * ctx->SMSS / ctx->cwnd_size;
			// MTP_PRINT("after\n");
			ctx->cwnd_size += add_cwnd;
		}
	}
	// MTP_PRINT("after DIV\n");
	// MTP_PRINT("slows_cong AFTER: cwnd:%u\n", ctx->cwnd_size);
}

static inline void ack_net_ep(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t ev_ack_seq, 
	uint32_t ev_window, uint32_t ev_seq, uint8_t stream_id, 
	tcp_stream* cur_stream, scratchpad* scratch)
{
	// MTP TODO: do wscale properly?
	if(scratch->skip_ack_eps) return;

	struct mtp_ctx *ctx = cur_stream->mtp;
	
	if (ctx->state == MTP_TCP_FIN_WAIT_1_ST || 
		ctx->state == MTP_TCP_FIN_WAIT_2_ST ||
		ctx->state == MTP_TCP_CLOSING_ST || 
		ctx->state == MTP_TCP_CLOSE_WAIT_ST || 
		ctx->state == MTP_TCP_LAST_ACK_ST) {
		if (ctx->fin_sent && ev_ack_seq == ctx->final_seq + 1) {
			ev_ack_seq--;
		}
	}
	
	// if (cur_stream->mtp->state != MTP_TCP_ESTABLISHED_ST) return;


	struct tcp_send_vars *sndvar = cur_stream->sndvar;

	struct mtp_ctx_stream* stx = &ctx->s0;
	if (stream_id == 1){
		stx = &ctx->s1;
	}
	
	// MTP_PRINT("ack_net_ep before grabbing lock\n");
	SBUF_LOCK(&sndvar->write_lock);
	// MTP_PRINT("ack_net_ep after grabbing lock\n");

	// Update window
	// MTP_PRINT("ev_window: %u, wscale_remote: %u\n", ev_window, ctx->wscale_remote);
	uint32_t rwindow = ev_window << ctx->wscale_remote;
	// MTP_PRINT("rwindow: %u\n", rwindow);
    // MTP TODO: sequence comparisons
    if (MTP_SEQ_LT(stx->lwu_seq, ev_seq, stx->send_una) ||
        (stx->lwu_seq == ev_seq && MTP_SEQ_LT(stx->lwu_ack, ev_ack_seq, stx->send_una)) ||
        (stx->lwu_ack == ev_ack_seq && rwindow > stx->last_rwnd_remote)){
        uint32_t rwindow_prev = stx->last_rwnd_remote;
		// MTP_PRINT("ack_net_ep, before: lwu_seq: %u, lwu_ack: %u, rwindow: %u\n", cur_stream->mtp->lwu_seq,
		// 							   cur_stream->mtp->lwu_ack,
		// 							   cur_stream->mtp->last_rwnd_remote);
        stx->last_rwnd_remote = rwindow;
        stx->lwu_seq = ev_seq;
        stx->lwu_ack = ev_ack_seq;
		// MTP_PRINT("ack_net_ep, after: lwu_seq: %u, lwu_ack: %u, rwindow: %u\n", cur_stream->mtp->lwu_seq,
		// 							   cur_stream->mtp->lwu_ack,
		// 							   cur_stream->mtp->last_rwnd_remote);
        if (rwindow_prev < MTP_SEQ_SUB(stx->send_next, stx->send_una, stx->send_una) &&
            stx->last_rwnd_remote >= MTP_SEQ_SUB(stx->send_next, stx->send_una, stx->send_una)){
            // This is kinda "notify" in MTP
			MTP_PRINT("rwnd opened up\n");
            RaiseWriteEvent(mtcp, cur_stream, stream_id);
        }
    }
 
    // Calculate how much can we send from stream 0
	int data_rest0 = sndvar->sndbuf0->len - 
					MTP_SEQ_SUB(ctx->s0.send_next, sndvar->sndbuf0->head_seq, 
								sndvar->sndbuf0->head_seq);

	uint32_t send_una0 = ctx->s0.send_una;
	if (stream_id == 0 &&
		ev_ack_seq > send_una0){send_una_0 = ev_ack_seq;}	 
	int in_flight0 = MTP_SEQ_SUB(ctx->s0.send_next, send_una0, 
								send_una0); 
	int recv_wnd0 = ctx->s0.last_rwnd_remote - in_flight0;
	int bytes_to_send0 = MIN(data_rest0, recv_wnd0);

	MTP_PRINT("data_rest0: %d, recv_wnd0: %d, bytes_to_send0: %d\n", 
			data_rest0, recv_wnd0, bytes_to_send0);

	// Calculate how much can we send from stream 1
	int data_rest1 = sndvar->sndbuf1->len - 
					MTP_SEQ_SUB(ctx->s1.send_next, sndvar->sndbuf1->head_seq, 
								sndvar->sndbuf1->head_seq);
	uint32_t send_una1 = ctx->s1.send_una;
	if (stream_id == 1 &&
		ev_ack_seq > send_una1){send_una_1 = ev_ack_seq;}

	int in_flight1 = MTP_SEQ_SUB(ctx->s1.send_next, send_una1, 
								 send_una1);
	int recv_wnd1 = ctx->s1.last_rwnd_remote - in_flight1;
	int bytes_to_send1 = MIN(data_rest1, recv_wnd1);

	MTP_PRINT("data_rest1: %d, recv_wnd1: %d, bytes_to_send1: %d\n", 
			data_rest1, recv_wnd1, bytes_to_send1);


	// Calculate total to send
	int remaining_in_cwnd = ctx->cwnd_size - (in_flight0 + in_flight1);
	int total_bytes_to_send = MIN(bytes_to_send0 + bytes_to_send1, 
							remaining_in_cwnd);

	MTP_PRINT("cwnd_size: %u, in_flight0: %u, in_flight1: %u, "
			"bytes_to_send: %d\n", 
			ctx->cwnd_size, in_flight0, in_flight1, bytes_to_send);

	if ((stream_id == 0 && data_rest0 == 0 && ev_ack_seq == ctx->s0.send_next) ||
		(stream_id == 1 && data_rest1 == 0 && ev_ack_seq == ctx->s1.send_next)) {
		SBUF_UNLOCK(&sndvar->write_lock);
		if (ctx->state != MTP_TCP_FIN_WAIT_1_ST &&
		    ctx->state != MTP_TCP_CLOSING_ST) {
			TimerCancel(mtcp, cur_stream);
			MTP_PRINT("THIS CASE\n");

			// Remove acked sequence from sending buffer
			// This step is kinda target dependent (depending on the implementation of sending buffer)
			uint32_t rmlen = MTP_SEQ_SUB(ev_ack_seq, stx->send_una, stx->send_una);
			// MTP_PRINT("ack_net_ep: rmlen: %u, send_una: %u, ev_ack_seq: %u\n", 
			// 		rmlen, ctx->send_una, ev_ack_seq);
			
			if(rmlen > 0) {
				// MTP_PRINT("Removing %d bytes\n", rmlen);
				//uint32_t offset = MTP_SEQ_SUB(ctx->send_una, ctx->init_seq, ctx->init_seq);
				uint32_t offset = stx->send_una;
				TxDataFlush(mtcp, cur_stream, offset, rmlen, stream_id);
				// MTP_PRINT("head ptr: %p, head seq: %d, len: %d, snd_wnd: %d\n", sndvar->sndbuf->head, 
					// sndvar->sndbuf->head_seq, sndvar->sndbuf->len, sndvar->snd_wnd);
				stx->send_una = ev_ack_seq;
				stx->num_rtx = 0;
			}
			
			// MTP_PRINT("ack_net_ep before releasing lock\n");
		}
		else {
			// Send FIN
			mtp_bp* bp = GetFreeBP(cur_stream);

			// MTP_PRINT("got bp\n");
			// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
			
			memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

			bp->hdr.source = cur_stream->mtp->local_port;
			bp->hdr.dest = cur_stream->mtp->remote_port;
			bp->hdr.seq = htonl(ctx->final_seq);
			// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
			bp->hdr.ack_seq = htonl(ctx->recv_next);

			bp->hdr.syn = FALSE;
			bp->hdr.ack = TRUE;
			bp->hdr.fin = TRUE;
			bp->hdr.urg_ptr = htons(MTP_QUIC_SHARED);

			// options to calculate data offset

			// MTP TODO: SACK? 
		#if TCP_OPT_SACK_ENABLED
			MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
		#endif

			MTP_set_opt_nop(&(bp->opts.nop1));
			MTP_set_opt_nop(&(bp->opts.nop2));

			// MTP TODO: Timestamp
			MTP_set_opt_timestamp(&(bp->opts.timestamp),
									htonl(cur_ts),
									htonl(ctx->ts_recent));
			

			// MTP TODO: would the MTP program do the length 
			//           calculation itself?
			uint16_t optlen = MTP_CalculateOptionLength(bp);
			bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

			// MTP TODO: wscale on local
			uint32_t window32 = ctx->rwnd_size >> ctx->wscale;
			uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
			bp->hdr.window = htons(advertised_window);
			if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

			// Payload
			// MTP TODO: fix snbuf
			bp->payload.data = NULL;
			bp->payload.len = 0;
			bp->payload.needs_segmentation = FALSE;

			AddtoGenList(mtcp, cur_stream, cur_ts);
		} 	
		// MTP_PRINT("ack_net_ep after releasing lock\n");
		return;
	}

	uint32_t effective_window = ctx->cwnd_size;
    if (stx->last_rwnd_remote < effective_window){
        effective_window = stx->last_rwnd_remote;
    }
	
	MTP_PRINT("ack_net_ep: cwnd: %d, rwnd: %d, stream_id: %d\n", 
				ctx->cwnd_size, stx->last_rwnd_remote, stream_id);

	if(ctx->duplicate_acks == 3) {
		int bytes_to_send = ctx->eff_SMSS;
        if (bytes_to_send > effective_window){
            bytes_to_send = effective_window;
        }

		int data_rest = data_rest0;
		if (stream_id == 1){
			data_rest = data_rest1;
		}
		if (bytes_to_send > data_rest){
			bytes_to_send = data_rest;
		}

        // MTP TODO: check that size + options is not more than MSS
        mtp_bp* bp = GetFreeBP(cur_stream);
		// MTP_PRINT("dup ack got bp\n");
		// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
        
        memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

        bp->hdr.source = ctx->local_port;
        bp->hdr.dest = ctx->remote_port;
        bp->hdr.seq = htonl(stx->send_una);
		// MTP_PRINT("dup ack Seq: %u\n", ntohl(bp->hdr.seq));
        bp->hdr.ack_seq = htonl(stx->recv_next);

        bp->hdr.syn = FALSE;
        bp->hdr.ack = TRUE;
		bp->hdr.urg_ptr = htons(stream_id);

        // options to calculate data offset
       
        // MTP TODO: SACK? 
    #if TCP_OPT_SACK_ENABLED
        MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
    #endif

        MTP_set_opt_nop(&(bp->opts.nop1));
        MTP_set_opt_nop(&(bp->opts.nop2));

        // MTP TODO: Timestamp
        MTP_set_opt_timestamp(&(bp->opts.timestamp),
                                htonl(cur_ts),
                                htonl(ctx->ts_recent));
        
       
        // MTP TODO: would the MTP program do the length 
        //           calculation itself?
        uint16_t optlen = MTP_CalculateOptionLength(bp);
        bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

        // MTP TODO: wscale on local
        uint8_t wscale = ctx->wscale;
    	uint32_t window32 = ctx->rwnd_size >> wscale;  
		// MTP TODO: fix this
    	uint16_t advertised_window = (uint16_t)MIN(window32, TCP_MAX_WINDOW);
        bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

        // Payload
        // MTP TODO: fix snbuf

		struct tcp_send_buffer* sndbuf = sndvar->sndbuf0;
		if (stream_id == 1){
			sndbuf = sndvar->sndbuf1;
		}
		uint32_t buf_offset = MTP_SEQ_SUB(stx->send_una,
												sndbuf->head_seq,
												sndbuf->head_seq);

		if (sndbuf->head_off + buf_offset > sndbuf->size){
			// struct tcp_send_buffer* buf = sndvar->sndbuf;
			uint32_t first_half = sndbuf->size - sndbuf->head_off;
			uint32_t second_half = buf_offset - first_half;
			uint32_t go_back = sndbuf->head_off - second_half;
			bp->payload.data = sndbuf->head - go_back;
			bp->payload.wraps_around = FALSE;
		}
		else {
			uint8_t *data = sndbuf->head + buf_offset;
			bp->payload.data = data;

			// struct tcp_send_buffer* buf = sndvar->sndbuf;
			if (sndbuf->head_off + buf_offset + bytes_to_send > sndbuf->size){
				uint32_t start = sndbuf->head_off + buf_offset;
				uint32_t first_half = sndbuf->size - start;
				bp->payload.wraps_around = TRUE;
				bp->payload.wrap_around_seg = stx->send_next + first_half;
				bp->payload.wrap_around_data = sndbuf->data;
			}
		}
		// uint8_t *data = sndvar->sndbuf->head + MTP_SEQ_SUB(ctx->send_una,
		// 												   sndvar->sndbuf->head_seq,
		// 												   sndvar->sndbuf->head_seq);
        // bp->payload.data = data;
        
		bp->payload.len = bytes_to_send;
        bp->payload.needs_segmentation = FALSE;

        AddtoGenList(mtcp, cur_stream, cur_ts);

		// MTP_PRINT("dup ack prepared bp:\n");
		// print_MTP_bp(bp);
		// MTP_PRINT("dup ack head ptr: %p, head seq: %d, len: %d, snd wnd: %d\n", sndvar->sndbuf->head, 
		// 		sndvar->sndbuf->head_seq, sndvar->sndbuf->len, sndvar->snd_wnd);
		
		// MTP_PRINT("ack_net_ep before releasing lock\n");
		SBUF_UNLOCK(&sndvar->write_lock);
		// MTP_PRINT("ack_net_ep after releasing lock\n");
		return;
	}

	// Continue sending if window is available and there's remaining data in sending buffer
	/*
	uint32_t window_avail = 0;
	uint32_t window_end_exclusive = ev_ack_seq + effective_window;
	MTP_PRINT("ack_net_ep: window_end_exclusive: %u, send_next: %u, send_una: %u\n", 
			window_end_exclusive, ctx->send_next, ctx->send_una);
	if (MTP_SEQ_GT(window_end_exclusive, ctx->send_next, ctx->send_una)) 
		window_avail = MTP_SEQ_SUB(window_end_exclusive, ctx->send_next,
								   ctx->send_una);

	if (window_avail == 0)
		bytes_to_send = 0;
	else {
        if (data_rest < window_avail) bytes_to_send = data_rest;
        else bytes_to_send = window_avail;
    }
	*/

	// MTP TODO: check bytes to send is not zero
	MTP_PRINT("ack_net_ep: window_avail: %u, bytes to send: %d\n", 
						window_avail, bytes_to_send);

	if (total_bytes_to_send > 0) {

		// Decide which stream should go first
		// a little hacky because assumes seq starts from 0.
		uint32_t sent_from_s0 = ctx->s0.send_next;
		uint32_t sent_from_s1 = ctx->s1.send_next;

		uint8_t first_stream = 0;
		struct mtp_ctx_stream* first_stream_ctx = &ctx->s0;
		struct tcp_send_buffer* first_stream_buf = sndvar->sndbuf0;
		int first_bytes_to_send = bytes_to_send0;

		uint8_t next_stream = 1;
		struct mtp_ctx_stream* next_stream_ctx = &ctx->s1;
		struct tcp_send_buffer* next_stream_buf = sndvar->sndbuf1;
		int next_bytes_to_send = bytes_to_send1;

		if ( (sent_from_s0 > sent_from_s1 + MTP_QUIC_SCHED_CHUNK) ||
			bytes_to_send0 <= 0){
			first_stream = 1;
			first_stream_ctx = &ctx->s1;
			first_stream_buf = sndvar->sndbuf1;
			first_bytes_to_send = bytes_to_send1;

			next_stream = 0;
			next_stream_ctx = &ctx->s0;
			next_stream_buf = sndvar->sndbuf0;
			next_bytes_to_send = bytes_to_send0;
		}

		int bytes_from_first = MIN(first_bytes_to_send, remaining_in_cwnd);
		int bytes_from_next = 0;
		if (bytes_from_first < remaining_in_cwnd){
			bytes_from_next = MIN(next_bytes_to_send, (remaining_in_cwnd - bytes_from_first);
		}

		// Generating from first
		{
			mtp_bp* bp;
			bool merging = FALSE;

			if (!BPBuffer_isempty(cur_stream)){
				mtp_bp* last_bp = GetLastBP(cur_stream);
				uint32_t next_sched_byte = ntohl(last_bp->hdr.seq) + last_bp->payload.len;
				if (last_bp->hdr.urg_ptr == htons(first_stream) &&
					last_bp->payload.len > 0 && 
					ctx->send_next == next_sched_byte){
					MTP_PRINT("merging, prev blueprint is:\n");
					print_MTP_bp(last_bp);
					bp = last_bp;
					merging = FALSE;
					// merging = TRUE;
				}
			}

			if (!merging){
				bp = GetFreeBP(cur_stream);	
			}
			MTP_PRINT("got bp\n");
			MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
			
			if (!merging){
				memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));
			}

			bp->hdr.source = cur_stream->mtp->local_port;
			bp->hdr.dest = cur_stream->mtp->remote_port;

			if (!merging){
				bp->hdr.seq = htonl(first_stream_ctx->send_next);
			}
			MTP_PRINT("Seq: %u\n", ntohl(bp->hdr.seq));

			// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
			bp->hdr.ack_seq = htonl(first_stream_ctx->recv_next);

			bp->hdr.syn = FALSE;
			bp->hdr.ack = TRUE;
			bp->hdr.urg_ptr = htons(first_stream);

			// options to calculate data offset
		
			// MTP TODO: SACK? 
		#if TCP_OPT_SACK_ENABLED
			MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
		#endif

			MTP_set_opt_nop(&(bp->opts.nop1));
			MTP_set_opt_nop(&(bp->opts.nop2));

			// MTP TODO: Timestamp
			MTP_set_opt_timestamp(&(bp->opts.timestamp),
									htonl(cur_ts),
									htonl(ctx->ts_recent));
			
		
			// MTP TODO: would the MTP program do the length 
			//           calculation itself?
			uint16_t optlen = MTP_CalculateOptionLength(bp);
			bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

			// MTP TODO: wscale on local
			uint32_t window32 = first_stream_ctx->rwnd_size >> cur_stream->mtp->wscale;
			uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
			bp->hdr.window = htons(advertised_window);
			if (advertised_window == 0) first_stream_ctx->adv_zero_wnd = TRUE;

			// Payload
			// MTP TODO: fix snbuf
			if (!merging){
				uint32_t buf_offset = MTP_SEQ_SUB(ctx->send_next,
													first_stream_buf->head_seq,
													first_stream_buf->head_seq);

				if (first_stream_buf->head_off + buf_offset > first_stream_buf->size){
					// struct tcp_send_buffer* buf = sndvar->sndbuf;
					uint32_t first_half = first_stream_buf->size - first_stream_buf->head_off;
					uint32_t second_half = buf_offset - first_half;
					uint32_t go_back = first_stream_buf->head_off - second_half;
					bp->payload.data = first_stream_buf->head - go_back;
					bp->payload.wraps_around = FALSE;
				}
				else {
					uint8_t *data = first_stream_buf->head + buf_offset;
					bp->payload.data = data;

					// struct tcp_send_buffer* buf = sndvar->sndbuf;
					if (first_stream_buf->head_off + buf_offset + bytes_to_send > 
						first_stream_buf->size){
						uint32_t start = first_stream_buf->head_off + buf_offset;
						uint32_t first_half = first_stream_buf->size - start;
						bp->payload.wraps_around = TRUE;
						bp->payload.wrap_around_seg = first_stream_ctx->send_next + first_half;
						bp->payload.wrap_around_data = buf->data;
					}
				}
			}

			if (merging){
				bp->payload.len += bytes_from_first;
			}
			else {
				bp->payload.len = bytes_from_first;
			}


			if (bp->payload.len > ctx->eff_SMSS){
				bp->payload.needs_segmentation = TRUE;
				bp->payload.seg_size = ctx->eff_SMSS;
				bp->payload.seg_rule_group_id = 1; 
			} 

			MTP_PRINT("Generated bp:\n");
			print_MTP_bp(bp);

			AddtoGenList(mtcp, cur_stream, cur_ts);	

			// MTP_PRINT("prepared bp:\n");
			// print_MTP_bp(bp);
			// MTP_PRINT("head ptr: %p, head seq: %d, len: %d, snd_wnd: %d\n", sndvar->sndbuf->head, 
			// 		sndvar->sndbuf->head_seq, sndvar->sndbuf->len, sndvar->snd_wnd);

			first_stream_ctx->send_next = first_stream_ctx->send_next + bytes_from_first;
			// MTP_PRINT("ack_ep send next: %u\n", ctx->send_next);
		}

		// Generating from next
		if (bytes_from_next > 0){
			mtp_bp* bp;
			bool merging = FALSE;

			if (!BPBuffer_isempty(cur_stream)){
				mtp_bp* last_bp = GetLastBP(cur_stream);
				uint32_t next_sched_byte = ntohl(last_bp->hdr.seq) + last_bp->payload.len;
				if (last_bp->hdr.urg_ptr == htons(next_stream) &&
					last_bp->payload.len > 0 && 
					ctx->send_next == next_sched_byte){
					MTP_PRINT("merging, prev blueprint is:\n");
					print_MTP_bp(last_bp);
					bp = last_bp;
					merging = FALSE;
					// merging = TRUE;
				}
			}

			if (!merging){
				bp = GetFreeBP(cur_stream);	
			}
			MTP_PRINT("got bp\n");
			MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
			
			if (!merging){
				memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));
			}

			bp->hdr.source = cur_stream->mtp->local_port;
			bp->hdr.dest = cur_stream->mtp->remote_port;

			if (!merging){
				bp->hdr.seq = htonl(next_stream_ctx->send_next);
			}
			MTP_PRINT("Seq: %u\n", ntohl(bp->hdr.seq));

			// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
			bp->hdr.ack_seq = htonl(next_stream_ctx->recv_next);

			bp->hdr.syn = FALSE;
			bp->hdr.ack = TRUE;
			bp->hdr.urg_ptr = htons(next_stream);

			// options to calculate data offset
		
			// MTP TODO: SACK? 
		#if TCP_OPT_SACK_ENABLED
			MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
		#endif

			MTP_set_opt_nop(&(bp->opts.nop1));
			MTP_set_opt_nop(&(bp->opts.nop2));

			// MTP TODO: Timestamp
			MTP_set_opt_timestamp(&(bp->opts.timestamp),
									htonl(cur_ts),
									htonl(ctx->ts_recent));
			
		
			// MTP TODO: would the MTP program do the length 
			//           calculation itself?
			uint16_t optlen = MTP_CalculateOptionLength(bp);
			bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

			// MTP TODO: wscale on local
			uint32_t window32 = next_stream_ctx->rwnd_size >> cur_stream->mtp->wscale;
			uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
			bp->hdr.window = htons(advertised_window);
			if (advertised_window == 0) next_stream_ctx->adv_zero_wnd = TRUE;

			// Payload
			// MTP TODO: fix snbuf
			if (!merging){
				uint32_t buf_offset = MTP_SEQ_SUB(ctx->send_next,
													next_stream_buf->head_seq,
													next_stream_buf->head_seq);

				if (next_stream_buf->head_off + buf_offset > next_stream_buf->size){
					// struct tcp_send_buffer* buf = sndvar->sndbuf;
					uint32_t next_half = next_stream_buf->size - next_stream_buf->head_off;
					uint32_t second_half = buf_offset - first_half;
					uint32_t go_back = next_stream_buf->head_off - second_half;
					bp->payload.data = next_stream_buf->head - go_back;
					bp->payload.wraps_around = FALSE;
				}
				else {
					uint8_t *data = next_stream_buf->head + buf_offset;
					bp->payload.data = data;

					// struct tcp_send_buffer* buf = sndvar->sndbuf;
					if (next_stream_buf->head_off + buf_offset + bytes_to_send > 
						next_stream_buf->size){
						uint32_t start = next_stream_buf->head_off + buf_offset;
						uint32_t first_half = next_stream_buf->size - start;
						bp->payload.wraps_around = TRUE;
						bp->payload.wrap_around_seg = next_stream_ctx->send_next + first_half;
						bp->payload.wrap_around_data = buf->data;
					}
				}
			}

			if (merging){
				bp->payload.len += bytes_from_next;
			}
			else {
				bp->payload.len = bytes_from_next;
			}


			if (bp->payload.len > ctx->eff_SMSS){
				bp->payload.needs_segmentation = TRUE;
				bp->payload.seg_size = ctx->eff_SMSS;
				bp->payload.seg_rule_group_id = 1; 
			} 

			MTP_PRINT("Generated bp:\n");
			print_MTP_bp(bp);

			// AddtoGenList(mtcp, cur_stream, cur_ts);	

			// MTP_PRINT("prepared bp:\n");
			// print_MTP_bp(bp);
			// MTP_PRINT("head ptr: %p, head seq: %d, len: %d, snd_wnd: %d\n", sndvar->sndbuf->head, 
			// 		sndvar->sndbuf->head_seq, sndvar->sndbuf->len, sndvar->snd_wnd);

			next_stream_ctx->send_next = next_stream_ctx->send_next + bytes_from_next;
			// MTP_PRINT("ack_ep send next: %u\n", ctx->send_next);
		}
	}

	
	// MTP TODO: match the mtp file in creating right "event" on timeout
	TimerRestart(mtcp, cur_stream, cur_ts);
	// MTP_PRINT("ack_net_ep before releasing lock\n");
	SBUF_UNLOCK(&sndvar->write_lock);
	// MTP_PRINT("ack_net_ep after releasing lock\n");
}

static inline void fin_ack_ep(mtcp_manager_t mtcp, uint32_t cur_ts, 
		uint32_t ev_ack_seq, tcp_stream *cur_stream, scratchpad *scratch)
{
	MTP_PRINT("----------------------------- fin_ack_ep: %u\n", ev_ack_seq);
	MTP_PRINT("cur_stream->mtp->state: %d\n", cur_stream->mtp->state);
	struct mtp_ctx *ctx = cur_stream->mtp;
	if ((ctx->state != MTP_TCP_FIN_WAIT_1_ST) &&
	    (ctx->state != MTP_TCP_CLOSING_ST) &&
		(ctx->state != MTP_TCP_LAST_ACK_ST)) return;

	MTP_PRINT("in fin_ack_ep: ev_ack_seq: %u, final_seq: %u, fin_sent:%d\n", 
			ev_ack_seq, ctx->final_seq, ctx->fin_sent);

	if (cur_stream->socket){
		MTP_PRINT("socket id: %d\n", cur_stream->socket->id);
	}
	
	if (ctx->fin_sent && 
		ev_ack_seq == ctx->final_seq + 1) {
		ctx->send_una = ev_ack_seq;
		if (MTP_SEQ_GT(ev_ack_seq, ctx->send_next, ctx->send_una)) {
			TRACE_DBG("Stream %d: update snd_nxt to %u\n", 
					cur_stream->id, ev_ack_seq);
			MTP_PRINT("I think this is not supposed to happen\n");
			ctx->send_next = ev_ack_seq;
		}
		
		ctx->num_rtx = 0;
		TimerCancel(mtcp, cur_stream);
		if (ctx->state == MTP_TCP_FIN_WAIT_1_ST){
			ctx->state = MTP_TCP_FIN_WAIT_2_ST;
			MTP_PRINT("fin_ack_ep: state changed to FIN_WAIT_2\n");
		}
		else if (ctx->state == MTP_TCP_CLOSING_ST){
			ctx->state = MTP_TCP_TIME_WAIT_ST;
			// MTP TODO: do we need this?
			// MTP TODO: fix
			ctx->state = MTP_TCP_CLOSED_ST;
			DestroyCtx(mtcp, cur_stream, ctx->local_port);
			MTP_PRINT("fin_ack_ep: state changed to CLOSED\n");
			//AddtoTimewaitList(mtcp, cur_stream, cur_ts);
		}
		else if (ctx->state == MTP_TCP_LAST_ACK_ST){
			ctx->state = MTP_TCP_CLOSED_ST;
			DestroyCtx(mtcp, cur_stream, ctx->local_port);
			MTP_PRINT("fin_ack_ep: state changed to CLOSED\n");
		}
	}
}

static inline void data_net_ep(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t ev_seq, uint8_t *ev_payload,
    int ev_payloadlen, uint8_t stream_id, tcp_stream* cur_stream)
{
	struct mtp_ctx *ctx = cur_stream->mtp;

	if (ctx->state == MTP_TCP_CLOSE_WAIT_ST) return;
	struct mtp_ctx_stream *stx = &ctx.s0;
	if (stream_id == 1){
		stx = &ctx.s1;
	}

    struct tcp_recv_vars *rcvvar = cur_stream->rcvvar;
	struct tcp_ring_buffer *rcvbuf = rcvvar->rcvbuf0;
	if (stream_id == 1){
		rcvbuf = rcvvar->rcvbuf1;
	}
	
    uint32_t last_rcvd_seq = ev_seq + ev_payloadlen;

	// MTP TODO?: new ordered data

	MTP_PRINT("in data_net_ep for stream id: %d\n", stream_id);
	MTP_PRINT("data_net_ep: ev_seq: %u, ev_payloadlen: %d, last_rcvd_seq: %u, ctx->rwnd_size: %u\n", 
			ev_seq, ev_payloadlen, last_rcvd_seq, stx->rwnd_size);
	MTP_PRINT("MTP_SEQ_GT(last_rcvd_seq, ctx->recv_next + ctx->rwnd_size, ctx->recv_init_seq): %d\n", 
			MTP_SEQ_GT(last_rcvd_seq, stx->recv_next + stx->rwnd_size, stx->recv_init_seq));
	MTP_PRINT("data_net_ep: MTP_SEQ_LT(last_rcvd_seq, ctx->recv_next, ctx->recv_init_seq): %d\n", 
			MTP_SEQ_LT(last_rcvd_seq, stx->recv_next, ctx->recv_init_seq));
	// if seq and segment length is lower than rcv_nxt or exceeds buffer, ignore and send ack
	if (MTP_SEQ_LT(last_rcvd_seq, stx->recv_next, ctx->recv_init_seq) ||
		MTP_SEQ_GT(last_rcvd_seq, stx->recv_next + stx->rwnd_size, ctx->recv_init_seq)) {
		return;
	}

	// if (!rcvvar->rcvbuf) {
	// 	rcvvar->rcvbuf = RBInit(mtcp->rbm_rcv, ctx->recv_init_seq);
	// 	ctx->meta_rwnd = RBInit(mtcp->rbm_rcv, ctx->recv_init_seq);
	// 	if (!rcvvar->rcvbuf || !ctx->meta_rwnd) {
	// 		MTP_PRINT("Stream %d: Failed to allocate receive buffer.\n", 
	// 				cur_stream->id);
	// 		cur_stream->state = TCP_ST_CLOSED;
	// 		cur_stream->close_reason = TCP_NO_MEM;
	// 		RaiseErrorEvent(mtcp, cur_stream);

	// 		return;
	// 	}
	// }

	MTP_PRINT("Grabbing lock in data_net_ep\n");
	if (SBUF_LOCK(&rcvvar->read_lock)) {
		if (errno == EDEADLK) perror("ProcessTCPPayload: read_lock blocked\n");
		assert(0);
	}

	// MTP TODO: this needs to be optimized
	// MtpWndPut(mtcp->rbm_rcv, ctx->meta_rwnd, ev_payload, ev_payloadlen, ev_seq);
	// MtpWndSlide(mtcp->rbm_rcv, ctx->meta_rwnd, AT_MTCP);
	// ctx->recv_next = ctx->meta_rwnd->head_seq;

    RBPut(mtcp->rbm_rcv, rcvbuf, ev_payload, ev_payloadlen, ev_seq);
	MTP_PRINT("recv buffer merged len: %u\n", rcvvar->rcvbuf->merged_len);
	MTP_PRINT("my calculated merged len: %u, recv_next: %u, last_flushed: %u\n", 
			MTP_SEQ_SUB(stx->recv_next, stx->last_flushed, stx->last_flushed) - 1, 
			stx->recv_next, stx->last_flushed);

	stx->recv_next = rcvbuf->head_seq + rcvbuf->merged_len;

	if (ctx->state == MTP_TCP_FIN_WAIT_1_ST || 
		ctx->state == MTP_TCP_FIN_WAIT_2_ST) {
			// MTP TODO: integrate with MTP. Do we even need to do this?
		RBRemove(mtcp->rbm_rcv, 
				rcvbuf, 
				MTP_SEQ_SUB(stx->recv_next, stx->last_flushed, stx->last_flushed) - 1, 
				AT_MTCP);
	}

	SBUF_UNLOCK(&rcvvar->read_lock);

	if (ctx->state == MTP_TCP_ESTABLISHED_ST) {
		// "add_data_seg" instruction
		MTP_PRINT("data_net_ep: raising read event\n");
		RaiseReadEvent(mtcp, cur_stream, stream_id);
	}
}

inline void send_ack_ep(mtcp_manager_t mtcp, uint32_t cur_ts, 
						uint8_t stream_id, tcp_stream *cur_stream)
{

	struct mtp_ctx *ctx = cur_stream->mtp;

	if (ctx->state == MTP_TCP_CLOSE_WAIT_ST) return;

	if (ctx->state == MTP_TCP_ESTABLISHED_ST &&
		ctx->fin_received &&
	    ctx->final_seq_remote == ctx->recv_next) {
		MTP_PRINT("data_net_ep: final_seq_remote: %u, recv_next: %u\n", 
				ctx->final_seq_remote, ctx->recv_next);
		ctx->state = MTP_TCP_CLOSE_WAIT_ST;
		ctx->recv_next += 1;
		MTP_PRINT("data_net_ep: raising read event for fin\n");
		RaiseReadEvent(mtcp, cur_stream);
	}


	struct mtp_ctx_stream *stx = &ctx->s0;
	if (stream_id == 1){
		stx = &ctx->s1;
	}

    struct tcp_recv_vars *rcvvar = cur_stream->rcvvar;
	struct tcp_ring_buffer* rcvbuf = rcvvar->rcvbuf0;
	if (stream_id == 1){
		rcvbuf = rcvvar->rcvbuf1;
	}

	stx->rwnd_size = rcvbuf->size - (MTP_SEQ_SUB(stx->recv_next,
														stx->last_flushed,
														stx->last_flushed) - 1);

	mtp_bp* bp;													
	bool merging = FALSE;

	if (!BPBuffer_isempty(cur_stream)){
		mtp_bp* last_bp = GetLastBP(cur_stream);
		if (last_bp->hdr.urg_ptr == hton(stream_id) &&
			last_bp->payload.len == 0 &&
			last_bp->hdr.ack == TRUE &&
			last_bp->hdr.fin == FALSE) {
			MTP_PRINT("merging, prev blueprint is:\n");
			print_MTP_bp(last_bp);
			bp = last_bp;
			merging = TRUE;
		}
	}	
	
	if (!merging){
		bp = GetFreeBP(cur_stream);
	}

	// MTP_PRINT("got bp\n");
	// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
	
	memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

	bp->hdr.source = cur_stream->mtp->local_port;
	bp->hdr.dest = cur_stream->mtp->remote_port;
	bp->hdr.seq = htonl(ctx->send_next);
	// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
	bp->hdr.ack_seq = htonl(ctx->recv_next);

	bp->hdr.syn = FALSE;
	bp->hdr.ack = TRUE;
	bp->hdr.urg_ptr = htons(stream_id);

	// options to calculate data offset

	// MTP TODO: SACK? 
#if TCP_OPT_SACK_ENABLED
	MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
#endif

	MTP_set_opt_nop(&(bp->opts.nop1));
	MTP_set_opt_nop(&(bp->opts.nop2));

	// MTP TODO: Timestamp
	MTP_set_opt_timestamp(&(bp->opts.timestamp),
							htonl(cur_ts),
							htonl(ctx->ts_recent));
	

	// MTP TODO: would the MTP program do the length 
	//           calculation itself?
	uint16_t optlen = MTP_CalculateOptionLength(bp);
	bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

	// MTP TODO: wscale on local
	uint32_t window32 = ctx->rwnd_size >> ctx->wscale;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
	bp->hdr.window = htons(advertised_window);
	if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

	// Payload
	// MTP TODO: fix snbuf
	bp->payload.data = NULL;
	bp->payload.len = 0;
	bp->payload.needs_segmentation = FALSE;

	AddtoGenList(mtcp, cur_stream, cur_ts);
    
}

static inline int listen_ep(mtcp_manager_t mtcp, int sockid, int backlog) 
{
	return CreateListenCtx(mtcp, sockid, backlog);
}

static inline struct accept_res* accept_ep(mctx_t mctx, mtcp_manager_t mtcp,
	struct sockaddr *addr, socklen_t *addrlen, bool non_block, struct mtp_listen_ctx *ctx) 
{
	// Wait until a client request to connect
	pthread_mutex_lock(&ctx->accept_lock);
	if (TAILQ_EMPTY(&ctx->pending)) {
		if (non_block) {
			MTP_PRINT("accept_ep: non-blocking mode, no pending connections\n");
			pthread_mutex_unlock(&ctx->accept_lock);
			MTP_PRINT("accept_ep: errno set to EAGAIN\n");
			errno = EAGAIN;
			MTP_PRINT("accept_ep: returning NULL\n");
			return NULL;
		}
		else{
			MTP_PRINT("accept_ep: blocking mode, waiting for connections\n");
			pthread_cond_wait(&ctx->accept_cond, &ctx->accept_lock);// check lock
			if (mtcp->ctx->done || mtcp->ctx->exit) {
				pthread_mutex_unlock(&ctx->accept_lock);
				errno = EINTR;
				return NULL;
			}
		}
	}

	MTP_PRINT("accept_ep: pending connections available, proceeding\n");
	struct accept_res *res = TAILQ_FIRST(&ctx->pending);
	TAILQ_REMOVE(&ctx->pending, res, link);
	ctx->pending_len--;
	pthread_mutex_unlock(&ctx->accept_lock);

	// Return res, let target (api) do the following socket allocation
	return res;
}

static inline void syn_ep(mtcp_manager_t mtcp, uint32_t cur_ts,
	uint32_t ev_remote_ip, uint16_t ev_remote_port, uint32_t ev_init_seq, uint16_t ev_rwnd_size,
    bool ev_sack_permit, bool ev_mss_valid, uint16_t ev_mss, bool ev_wscale_valid, uint8_t ev_wscale,
	struct tcp_opt_timestamp *ev_ts,
	struct mtp_listen_ctx *ctx)
{
	MTP_PRINT("syn_ep: received SYN from %u:%u to %u:%u\n", 
			ev_remote_ip, ev_remote_port, ctx->local_ip, ctx->local_port);
	MTP_PRINT("ctx->state: %d\n", ctx->state);
	if (ctx->state != MTP_TCP_LISTEN_ST) return;
	MTP_PRINT("syn_ep: in LISTEN state, proceeding\n");

    
    // MTP TODO: do rand init seq
    // uint32_t init_seq = rand_r(&next_seed) % TCP_MAX_SEQ;
    uint32_t init_seq = 0;

    uint8_t wscale = 0;
    if (ev_wscale_valid) wscale = ev_wscale;

    uint16_t mss = 1460;
    if (ev_mss_valid) mss = ev_mss;
	// MTP new_ctx instruction
	MTP_PRINT("Creating new context\n");
	tcp_stream *cur_stream = CreateCtx(mtcp, cur_ts, 
                                      ev_remote_ip, ctx->local_ip, 
                                      ev_remote_port, ctx->local_port,
                                      ev_sack_permit, mss, 
                                      init_seq, init_seq, init_seq + 1,
                                      ev_init_seq, ev_init_seq + 1, ev_init_seq,
                                      ev_rwnd_size, wscale,
                                      MTP_TCP_SYNACK_SENT_ST);
	
	MTP_PRINT("Created context, stream ptr: %p\n", cur_stream);
	if (cur_stream == NULL) return;

	cur_stream->sndvar->sndbuf0 = SBInit(mtcp->rbm_snd, cur_stream->mtp->init_seq + 1);
	if (!cur_stream->sndvar->sndbuf0) {
		cur_stream->close_reason = TCP_NO_MEM;
		/* notification may not required due to -1 return */
		errno = ENOMEM;
		return;
	}

	cur_stream->sndvar->sndbuf1 = SBInit(mtcp->rbm_snd, cur_stream->mtp->init_seq + 1);
	if (!cur_stream->sndvar->sndbuf1) {
		cur_stream->close_reason = TCP_NO_MEM;
		/* notification may not required due to -1 return */
		errno = ENOMEM;
		return;
	}

	// Add stream to the listen context
	// Note: since mTCP's accept_res struct includes flow context, we insert
	//		new accept_res after context creation
	pthread_mutex_lock(&ctx->accept_lock);
	if (ctx->pending_len < ctx->pending_cap) {
		struct accept_res *acc = malloc(sizeof(*acc));
		acc->stream = cur_stream;
		TAILQ_INSERT_TAIL(&ctx->pending, acc, link);
		ctx->pending_len++;
	} else {
		// Error handling
		cur_stream->state = TCP_ST_CLOSED;
		cur_stream->close_reason = TCP_NOT_ACCEPTED;
		pthread_mutex_unlock(&ctx->accept_lock);
		return;
	}
	pthread_mutex_unlock(&ctx->accept_lock);

	// MTP pkt gen
	/*uint32_t window32 = cur_stream->rcvvar->rcv_wnd;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);

	SendMTPPacket(mtcp, cur_stream, cur_ts,
		TCP_FLAG_SYN | TCP_FLAG_ACK, 
		cur_stream->sndvar->iss, //seq
		init_seq + 1, //ack
		advertised_window, //window
		NULL, 0);
    */
    // MTP TODO: check that size + options is not more than MSS
   
    mtp_bp* bp = GetFreeBP(cur_stream);

	// MTP_PRINT("got bp\n");
	// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
    
    memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

	bp->hdr.source = cur_stream->mtp->local_port;
	bp->hdr.dest = cur_stream->mtp->remote_port;
    bp->hdr.seq = htonl(cur_stream->mtp->init_seq);
	// MTP_PRINT("Seq: %u\n", ntohl(bp->hdr.seq));
    bp->hdr.ack_seq = htonl(ev_init_seq + 1);

    bp->hdr.syn = TRUE;
    bp->hdr.ack = TRUE;
	bp->hdr.urg_ptr = ntohs(MTP_QUIC_SHARED);

    // options to calculate data offset
    // MSS
    MTP_set_opt_mss(&(bp->opts.mss), cur_stream->mtp->SMSS);
   
    // MTP TODO: SACK? 
#if TCP_OPT_SACK_ENABLED
    MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
#endif

    MTP_set_opt_nop(&(bp->opts.nop1));
    MTP_set_opt_nop(&(bp->opts.nop2));

    // MTP TODO: Timestamp
	uint32_t ts_value2 = 0;
	if (ev_ts->valid){
		ts_value2 = ev_ts->value1;
	}
    MTP_set_opt_timestamp(&(bp->opts.timestamp),
                            htonl(cur_ts),
                            htonl(ts_value2));
    
    // MTP TODO: Window scale
    MTP_set_opt_nop(&(bp->opts.nop3));
    MTP_set_opt_wscale(&(bp->opts.wscale), cur_stream->mtp->wscale);
   
    // MTP TODO: would the MTP program do the length 
    //           calculation itself?
    uint16_t optlen = MTP_CalculateOptionLength(bp);
    bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

    uint32_t window32 = cur_stream->mtp->initial_rwnd_size >> cur_stream->mtp->wscale;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
	bp->hdr.window = htons(advertised_window);


    // Payload
    bp->payload.data = NULL;
    bp->payload.len = 0;
    bp->payload.needs_segmentation = FALSE;

    AddtoGenList(mtcp, cur_stream, cur_ts);
}

void synack_ep(mtcp_manager_t mtcp, uint32_t cur_ts, 
				uint32_t ev_init_seq, uint32_t ev_ack_seq, 
				uint16_t ev_rwnd_size, bool ev_sack_permit, 
				bool ev_mss_valid, uint16_t ev_mss, 
				bool ev_wscale_valid, uint8_t ev_wscale,
				struct tcp_opt_timestamp* ev_ts, 
				tcp_stream* cur_stream)
{
	struct mtp_ctx *ctx = cur_stream->mtp;

	if (ctx->state != MTP_TCP_SYN_SENT_ST) {
		MTP_PRINT("MtpSyNAckChain: Invalid state %d for SYN-ACK\n", ctx->state);
		return;
	}

	
	ctx->state = MTP_TCP_ESTABLISHED_ST; //ESTABLISHED_ST

	// receiver related variables
    ctx->s0.recv_init_seq = ev_init_seq;
    ctx->s0.recv_next = ev_init_seq + 1;
	ctx->s0.last_flushed = ev_init_seq;

	ctx->s1.recv_init_seq = ev_init_seq;
    ctx->s1.recv_next = ev_init_seq + 1;
	ctx->s1.last_flushed = ev_init_seq;

	// sender related variables
	if (ev_wscale_valid) ctx->wscale_remote = ev_wscale;
    
	ctx->s0.last_rwnd_remote = ev_rwnd_size << ctx->wscale_remote;
	ctx->s1.last_rwnd_remote = ev_rwnd_size << ctx->wscale_remote;
	
	ctx->s0.send_una = ev_ack_seq;
	ctx->s1.send_una = ev_ack_seq;

	ctx->s0.send_next = ev_ack_seq;
	ctx->s1.send_next = ev_ack_seq;

	ctx->lwu_seq = ev_init_seq - 1;
	ctx->last_ack = ev_ack_seq;

	// options
	if (ev_mss_valid) ctx->SMSS = ev_mss;
	ctx->sack_permit_remote = ev_sack_permit;
	ctx->ts_recent = ev_ts->value1;
	ctx->ts_lastack_rcvd = ev_ts->value2;
	// MTP TODO: integrate with MTP
	cur_stream->rcvvar->ts_lastack_rcvd = ev_ts->value2;
	ctx->ts_last_ts_upd = cur_ts;

	// Other sender size variables
	if (ctx->cwnd_size == 1) ctx->cwnd_size = 2 * ctx->SMSS;
	else ctx->cwnd_size = ctx->SMSS;
	ctx->ssthresh = ctx->SMSS * 10;

	mtp_bp* bp = GetFreeBP(cur_stream);

	// MTP_PRINT("got bp\n");
	// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
	
	memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

	bp->hdr.source = cur_stream->mtp->local_port;
	bp->hdr.dest = cur_stream->mtp->remote_port;
	bp->hdr.seq = htonl(ev_ack_seq);
	// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
	bp->hdr.ack_seq = htonl(ev_init_seq + 1);

	bp->hdr.syn = FALSE;
	bp->hdr.ack = TRUE;
	bp->hdr.urg_ptr = ntohs(MTP_QUIC_SHARED);

	// options to calculate data offset

	// MTP TODO: SACK? 
#if TCP_OPT_SACK_ENABLED
	MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
#endif

	MTP_set_opt_nop(&(bp->opts.nop1));
	MTP_set_opt_nop(&(bp->opts.nop2));

	// MTP TODO: Timestamp
	MTP_set_opt_timestamp(&(bp->opts.timestamp),
							htonl(cur_ts),
							htonl(ctx->ts_recent));
	

	// MTP TODO: would the MTP program do the length 
	//           calculation itself?
	uint16_t optlen = MTP_CalculateOptionLength(bp);
	bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

	// MTP TODO: wscale on local
	uint32_t window32 = cur_stream->mtp->initial_rwnd_size >> cur_stream->mtp->wscale;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
	bp->hdr.window = htons(advertised_window);
	if (advertised_window == 0) {
		ctx->s0.adv_zero_wnd = TRUE;
		ctx->s1.adv_zero_wnd = TRUE;
	}

	// Payload
	// MTP TODO: fix snbuf
	bp->payload.data = NULL;
	bp->payload.len = 0;
	bp->payload.needs_segmentation = FALSE;

	AddtoGenList(mtcp, cur_stream, cur_ts);
	
	// MTP TODO: integrate into MTP
	RaiseWriteEvent(mtcp, cur_stream, MTP_QUIC_SHARED);
}

void timeout_ep(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream* cur_stream){
	struct mtp_ctx *ctx = cur_stream->mtp;
	// MTP_PRINT("Stream %d Timeout. cwnd: %u, ssthresh: %u\n", 
	// 		cur_stream->id, ctx->cwnd_size, ctx->ssthresh);
	MTP_PRINT("Stream %d, port:%u, Timeout. rto: %u, tx_rto:%u, cur_ts: %u\n", 
			cur_stream->id, cur_stream->mtp->remote_port, cur_stream->sndvar->rto, 
			cur_stream->sndvar->ts_rto, cur_ts);			

	/* count number of retransmissions */
	if (ctx->num_rtx < MTP_TCP_MAX_RTX) {
		ctx->num_rtx = ctx->num_rtx + 1;
	} else {
		/* if it exceeds the threshold, destroy and notify to application */
		// MTP_PRINT("Stream %d: Exceed MAX_RTX\n", cur_stream->id);
		
	}
	if (ctx->num_rtx > ctx->max_num_rtx) {
		ctx->max_num_rtx = ctx->num_rtx;
	}
	
	uint8_t backoff;
	/* update rto timestamp */
	if (ctx->state >= MTP_TCP_ESTABLISHED_ST) {
		backoff = MIN(ctx->num_rtx, MTP_TCP_MAX_BACKOFF);

		uint32_t rto_prev;
		rto_prev = cur_stream->sndvar->rto;
		#ifndef MTP_FIXED_RTO
		cur_stream->sndvar->rto = ((cur_stream->rcvvar->srtt >> 3) + 
				cur_stream->rcvvar->rttvar) << backoff;
		#else
		cur_stream->sndvar->rto = rto_prev << backoff;
		#endif
		if (cur_stream->sndvar->rto <= 0) {
			// MTP_PRINT("Stream %d current rto: %u, prev: %u, state: %s\n", 
					// cur_stream->id, cur_stream->sndvar->rto, rto_prev, 
					// TCPStateToString(cur_stream));
			cur_stream->sndvar->rto = rto_prev;
		}
	} else if (ctx->state >= MTP_TCP_SYN_SENT_ST) {
		/* if there is no rtt measured, update rto based on the previous one */
		if (ctx->num_rtx < MTP_TCP_MAX_BACKOFF) {
			cur_stream->sndvar->rto <<= 1;
		}
	}
	//cur_stream->sndvar->ts_rto = cur_ts + cur_stream->sndvar->rto;

	/* reduce congestion window and ssthresh */
	ctx->ssthresh = MIN(ctx->cwnd_size, ctx->last_rwnd_remote) / 2;
	if (ctx->ssthresh < (2 * ctx->SMSS)) {
		ctx->ssthresh = ctx->SMSS * 2;
	}
	ctx->cwnd_size = ctx->SMSS;
	
	/* Retransmission */
	// MTP TODO: add cases for other states
	
	if (ctx->state == MTP_TCP_ESTABLISHED_ST ||
		ctx->state == MTP_TCP_FIN_WAIT_1_ST ||
		ctx->state == MTP_TCP_CLOSING_ST) {
		
		struct tcp_send_vars *sndvar = cur_stream->sndvar;

		SBUF_LOCK(&sndvar->write_lock);
        // MTP TODO: check that size + options is not more than MSS
        uint32_t data_rest =  sndvar->sndbuf->len - 
					      MTP_SEQ_SUB(ctx->send_una, sndvar->sndbuf->head_seq,
									  sndvar->sndbuf->head_seq);

		uint32_t effective_window = ctx->cwnd_size;
		if (ctx->last_rwnd_remote < effective_window){
			effective_window = ctx->last_rwnd_remote;
		}
		
		uint32_t bytes_to_send = effective_window;
		if (data_rest < effective_window) bytes_to_send = data_rest;
		
		// MTP TODO: check bytes to send is not zero
		// MTP_PRINT("ack_net_ep: bytes to send: %d\n", bytes_to_send);

		// assert(bytes_to_send > 0);
		bool send_fin_again = FALSE;
		if (bytes_to_send == 0 && ctx->fin_sent) {
			if(ctx->send_next == ctx->final_seq &&
				   ctx->send_una == ctx->final_seq) send_fin_again = TRUE;
		}

		mtp_bp* bp = GetFreeBP(cur_stream);

		// MTP_PRINT("got bp\n");
		// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;
		bp->hdr.seq = htonl(ctx->send_una);
		// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(ctx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;
		bp->hdr.fin = send_fin_again;

		// options to calculate data offset
	
		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		
	
		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint32_t window32 = cur_stream->mtp->rwnd_size >> cur_stream->mtp->wscale;
		uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		uint8_t *data = sndvar->sndbuf->head + MTP_SEQ_SUB(ctx->send_una,
														sndvar->sndbuf->head_seq,
														sndvar->sndbuf->head_seq);
		bp->payload.data = data;
		bp->payload.len = bytes_to_send;
		bp->payload.needs_segmentation = TRUE;
		bp->payload.seg_size = ctx->eff_SMSS;
		bp->payload.seg_rule_group_id = 1; 

		AddtoGenList(mtcp, cur_stream, cur_ts);	
		
			
		// MTP_PRINT("ack_net_ep before releasing lock\n");
		TimerRestart(mtcp, cur_stream, cur_ts);
		
		SBUF_UNLOCK(&sndvar->write_lock);
		// MTP_PRINT("ack_net_ep after releasing lock\n");
	}
}

/***********************************************
 MTP Event Processor Chains
 
 EP chinas are globally exposed
 They implement parts for dispatcher in MTP code
 ***********************************************/
void MtpSendChain(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream *cur_stream)
{
	// MTP_PRINT("Calling send chain\n");
    send_ep(mtcp, cur_ts, cur_stream);
}

int MtpReceiveChainPart1(mtcp_manager_t mtcp, socket_map_t socket, 
					bool non_block, char *ev_buf, int ev_data_size, 
					uint8_t stream_id, tcp_stream *cur_stream)
{
	return receive_ep(mtcp, socket, non_block, ev_buf, ev_data_size, 
					  stream_id, cur_stream);
}

void MtpReceiveChainPart2(mtcp_manager_t mtcp, uint32_t cur_ts, 
						 tcp_stream *cur_stream)
{
	struct mtp_ctx* ctx = cur_stream->mtp;

	// Check stream 0
	struct mtp_ctx_stream *stx = &ctx->s0;
	if (stx->adv_zero_wnd) {
		// MTP TODO: integrate with MTP
		stx->adv_zero_wnd = FALSE;
		mtp_bp* bp = GetFreeBP(cur_stream);

		// MTP_PRINT("got bp\n");
		// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;
		bp->hdr.seq = htonl(stx->send_next);
		// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(stx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;
		bp->hdr.urg_ptr = htons(0);

		// options to calculate data offset

		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		

		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint32_t window32 = stx->rwnd_size >> ctx->wscale;
		uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) stx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		bp->payload.data = NULL;
		bp->payload.len = 0;
		bp->payload.needs_segmentation = FALSE;

		AddtoGenList(mtcp, cur_stream, cur_ts);
	}

	// Check stream 1
	struct mtp_ctx_stream *stx = &ctx->s1;
	if (stx->adv_zero_wnd) {
		// MTP TODO: integrate with MTP
		stx->adv_zero_wnd = FALSE;
		mtp_bp* bp = GetFreeBP(cur_stream);

		// MTP_PRINT("got bp\n");
		// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;
		bp->hdr.seq = htonl(stx->send_next);
		// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(stx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;
		bp->hdr.urg_ptr = htons(1);

		// options to calculate data offset

		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		

		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint32_t window32 = stx->rwnd_size >> ctx->wscale;
		uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) stx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		bp->payload.data = NULL;
		bp->payload.len = 0;
		bp->payload.needs_segmentation = FALSE;

		AddtoGenList(mtcp, cur_stream, cur_ts);
	}
}

void MtpAckChain(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t ack_seq, 
    uint32_t window, uint32_t seq, struct tcp_opt_timestamp* ev_ts, 
	uint8_t stream_id, tcp_stream* cur_stream)
{
    /*
    struct tcp_send_vars *sndvar = cur_stream->sndvar;

    if (cur_stream->state == TCP_ST_SYN_RCVD){
		// check if we're processing an acknowledgement of a SYN-ACK
		if (ack_seq != sndvar->iss + 1) {
			CTRACE_ERROR("Stream %d (TCP_ST_SYN_RCVD): "
					"weird ack_seq: %u, iss: %u\n", 
					cur_stream->id, ack_seq, sndvar->iss);
			return;
		}

		TimerCancel(mtcp, cur_stream);
	
		uint32_t prior_cwnd = sndvar->cwnd;
		sndvar->snd_una++;
		cur_stream->snd_nxt = ack_seq;
		sndvar->cwnd = ((prior_cwnd == 1) ? (sndvar->mss * TCP_INIT_CWND): sndvar->mss);
		cur_stream->state = TCP_ST_ESTABLISHED;

		// Raise an event to the listening socket
		struct mtp_listen_ctx *listen_ctx = 
			(struct mtp_listen_ctx *)ListenerHTSearch(mtcp->listeners, &cur_stream->sport);
		if (listen_ctx->socket && (listen_ctx->socket->epoll & MTCP_EPOLLIN)) {
			AddEpollEvent(mtcp->ep, MTCP_EVENT_QUEUE, listen_ctx->socket, MTCP_EPOLLIN);
		}
    } else if(cur_stream->state == TCP_ST_ESTABLISHED) {
    */
    scratchpad scratch;
	timestamp_ep(mtcp, cur_ts, ev_ts, cur_stream, &scratch);
    conn_ack_ep(mtcp, cur_ts, ack_seq, seq, cur_stream, &scratch);
    rto_ep(mtcp, cur_ts, ack_seq, cur_stream, &scratch);
    fast_retr_rec_ep(mtcp, cur_ts, ack_seq, cur_stream, &scratch);
    slows_congc_ep(mtcp, cur_ts, ack_seq, cur_stream, &scratch);
    ack_net_ep(mtcp, cur_ts, ack_seq, window, seq, cur_stream, &scratch);
	fin_ack_ep(mtcp, cur_ts, ack_seq, cur_stream, &scratch);
}

void MtpDataChain(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t seq, uint8_t *payload, 
	int payloadlen, uint8_t stream_id, tcp_stream *cur_stream)
{
	data_net_ep(mtcp, cur_ts, seq, payload, payloadlen, stream_id, cur_stream);
    send_ack_ep(mtcp, cur_ts, stream_id, cur_stream);
}

int MtpListenChain(mtcp_manager_t mtcp, int sockid, int backlog)
{
	return listen_ep(mtcp, sockid, backlog);
}

struct accept_res* MtpAcceptChain(mctx_t mctx, mtcp_manager_t mtcp, struct sockaddr *addr, 
	socklen_t *addrlen, bool non_block, struct mtp_listen_ctx *ctx) 
{
	return accept_ep(mctx, mtcp, addr, addrlen, non_block, ctx);
}


tcp_stream* MtpConnectChainPart1(mtcp_manager_t mtcp, uint32_t cur_ts,
					 uint32_t ev_local_ip, uint32_t ev_remote_ip, 
					 uint16_t ev_local_port, uint16_t ev_remote_port){
	
	// MTP TODO: do rand init seq
	// uint32_t init_seq = rand_r(&next_seed) % TCP_MAX_SEQ;
	uint32_t init_seq = 0;	

	tcp_stream *cur_stream = CreateCtx(mtcp, cur_ts, 
                                      ev_remote_ip, ev_local_ip, 
                                      ev_remote_port, ev_local_port,
                                      false, 1460, 
                                      init_seq, init_seq, init_seq + 1,
                                      0, 0, 0, 0, 0,
                                      MTP_TCP_SYN_SENT_ST);
	MTP_PRINT("Created stream with saddr: %u, daddr: %u, sport: %u, dport: %u\n",
			cur_stream->saddr, cur_stream->daddr,
			cur_stream->sport, cur_stream->dport);

	cur_stream->sndvar->sndbuf0 = SBInit(mtcp->rbm_snd, cur_stream->mtp->init_seq + 1);
	if (!cur_stream->sndvar->sndbuf0) {
		cur_stream->close_reason = TCP_NO_MEM;
		/* notification may not required due to -1 return */
		errno = ENOMEM;
		return NULL;
	}

	cur_stream->sndvar->sndbuf1 = SBInit(mtcp->rbm_snd, cur_stream->mtp->init_seq + 1);
	if (!cur_stream->sndvar->sndbuf1) {
		cur_stream->close_reason = TCP_NO_MEM;
		/* notification may not required due to -1 return */
		errno = ENOMEM;
		return NULL;
	}
	return cur_stream;
}
	
void MtpConnectChainPart2(mtcp_manager_t mtcp, uint32_t cur_ts,
					 uint32_t ev_local_ip, uint32_t ev_remote_ip, 
					 uint16_t ev_local_port, uint16_t ev_remote_port, 
					 tcp_stream *cur_stream){	
	
	mtp_bp* bp = GetFreeBP(cur_stream);

	// MTP_PRINT("got bp\n");
	// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
    
    memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

	struct mtp_ctx *ctx = cur_stream->mtp;
	bp->hdr.source = ctx->local_port;
	bp->hdr.dest = ctx->remote_port;
	// MTP TODO: technically, should be the variable in Part1
    bp->hdr.seq = htonl(ctx->init_seq);
    bp->hdr.syn = TRUE;
    bp->hdr.ack = FALSE;
	bp->hdr.urg_ptr = ntohs(MTP_QUIC_SHARED);

    // options to calculate data offset
    // MSS
    MTP_set_opt_mss(&(bp->opts.mss), cur_stream->mtp->SMSS);
   
    // MTP TODO: SACK? 
#if TCP_OPT_SACK_ENABLED
    MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
#endif

    MTP_set_opt_nop(&(bp->opts.nop1));
    MTP_set_opt_nop(&(bp->opts.nop2));

    // MTP TODO: Timestamp
    MTP_set_opt_timestamp(&(bp->opts.timestamp),
                            htonl(cur_ts),
                            htonl(ctx->ts_recent));
    
    // MTP TODO: Window scale
    MTP_set_opt_nop(&(bp->opts.nop3));
    MTP_set_opt_wscale(&(bp->opts.wscale), cur_stream->mtp->wscale);
   
    // MTP TODO: would the MTP program do the length 
    //           calculation itself?
    uint16_t optlen = MTP_CalculateOptionLength(bp);
    bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

    uint32_t window32 = cur_stream->mtp->initial_rwnd_size >> cur_stream->mtp->wscale;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
	bp->hdr.window = htons(advertised_window);
	if (advertised_window == 0) {
		ctx->s0.adv_zero_wnd = TRUE;
		ctx->s1.adv_zero_wnd = TRUE;
	}

    // Payload
    bp->payload.data = NULL;
    bp->payload.len = 0;
    bp->payload.needs_segmentation = FALSE;

    AddtoGenList(mtcp, cur_stream, cur_ts);
}

void MtpSynChain(mtcp_manager_t mtcp, uint32_t cur_ts,
	uint32_t remote_ip, uint16_t remote_port, uint32_t init_seq, uint16_t rwnd_size,
    bool sack_permit, bool mss_valid, uint16_t mss, bool wscale_valid, uint8_t wscale,
	struct tcp_opt_timestamp *ev_ts, struct mtp_listen_ctx *ctx) 
{
	syn_ep(mtcp, cur_ts, remote_ip, remote_port, init_seq, rwnd_size, 
           sack_permit, mss_valid, mss, wscale_valid, wscale, ev_ts, ctx);
}

void MtpSyNAckChain(mtcp_manager_t mtcp, uint32_t cur_ts, 
					uint32_t ev_init_seq, uint32_t ev_ack_seq, 
					uint16_t ev_rwnd_size, bool ev_sack_permit, 
					bool ev_mss_valid, uint16_t ev_mss, 
                    bool ev_wscale_valid, uint8_t ev_wscale,
					struct tcp_opt_timestamp* ev_ts, 
					tcp_stream* cur_stream){
	synack_ep(mtcp, cur_ts, ev_init_seq, ev_ack_seq,	
				ev_rwnd_size, ev_sack_permit, 
				ev_mss_valid, ev_mss, 
				ev_wscale_valid, ev_wscale,
				ev_ts, cur_stream);

}

void MtpTimeoutChain(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream* cur_stream){
	timeout_ep(mtcp, cur_ts, cur_stream);
}

void MtpCloseChain(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream* cur_stream){
	struct mtp_ctx *ctx = cur_stream->mtp;

	ctx->closed = TRUE;

	if (ctx->state == MTP_TCP_CLOSED_ST) {
		MTP_PRINT("Stream %d at TCP_ST_CLOSED. destroying the stream.\n", 
				cur_stream->id);
		DestroyCtx(mtcp, cur_stream, ctx->local_port);
		return;

	} else if (ctx->state == MTP_TCP_SYN_SENT_ST) {
#if 1
		DestroyCtx(mtcp, cur_stream, ctx->local_port);
#endif
		return;

	} else if (ctx->state != MTP_TCP_ESTABLISHED_ST && 
			ctx->state != MTP_TCP_CLOSE_WAIT_ST) {
		TRACE_API("Stream %d at bad state\n", 
				cur_stream->id);
		errno = EBADF;
		return;
	}

	struct tcp_send_vars *sndvar = cur_stream->sndvar;
	if (sndvar->sndbuf) {
		ctx->final_seq = sndvar->sndbuf->head_seq + sndvar->sndbuf->len;
	} else {
		ctx->final_seq = ctx->send_next;
	}

	// if (CONFIG.tcp_timeout > 0)
	// 	RemoveFromTimeoutList(mtcp, cur_stream);

	if (ctx->state == MTP_TCP_ESTABLISHED_ST) {
		ctx->state = MTP_TCP_FIN_WAIT_1_ST;
	} else if (ctx->state == MTP_TCP_CLOSE_WAIT_ST) {
		ctx->state = MTP_TCP_LAST_ACK_ST;
	}
	// SEND FIN
	ctx->fin_sent = TRUE;

	mtp_bp* bp = GetFreeBP(cur_stream);

	// MTP_PRINT("got bp\n");
	// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
	
	memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

	bp->hdr.source = cur_stream->mtp->local_port;
	bp->hdr.dest = cur_stream->mtp->remote_port;
	bp->hdr.seq = htonl(ctx->final_seq);
	// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
	bp->hdr.ack_seq = htonl(ctx->recv_next);

	bp->hdr.syn = FALSE;
	bp->hdr.ack = TRUE;
	bp->hdr.fin = TRUE;

	// options to calculate data offset

	// MTP TODO: SACK? 
#if TCP_OPT_SACK_ENABLED
	MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
#endif

	MTP_set_opt_nop(&(bp->opts.nop1));
	MTP_set_opt_nop(&(bp->opts.nop2));

	// MTP TODO: Timestamp
	MTP_set_opt_timestamp(&(bp->opts.timestamp),
							htonl(cur_ts),
							htonl(ctx->ts_recent));
	

	// MTP TODO: would the MTP program do the length 
	//           calculation itself?
	uint16_t optlen = MTP_CalculateOptionLength(bp);
	bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

	// MTP TODO: wscale on local
	uint32_t window32 = ctx->rwnd_size >> ctx->wscale;
	uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
	bp->hdr.window = htons(advertised_window);
	if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

	// Payload
	// MTP TODO: fix snbuf
	bp->payload.data = NULL;
	bp->payload.len = 0;
	bp->payload.needs_segmentation = FALSE;

	AddtoGenList(mtcp, cur_stream, cur_ts);
}

void MtpFinChain(mtcp_manager_t mtcp, uint32_t cur_ts,
				 uint32_t ev_seq, uint32_t ev_payloadlen, 
				 tcp_stream* cur_stream){
	
    struct mtp_ctx *ctx = cur_stream->mtp;

	bool send_ack = FALSE;

	ctx->fin_received = TRUE;
	ctx->final_seq_remote = ev_seq + ev_payloadlen;

	if (ctx->state == MTP_TCP_ESTABLISHED_ST) send_ack = TRUE;

	MTP_PRINT("ev_seq: %u, ev_payload_len: %u, recv_next: %u\n",
			ev_seq, ev_payloadlen, ctx->recv_next);

	if (ctx->final_seq_remote == ctx->recv_next){
		ctx->recv_next = ctx->recv_next + 1;
		
		if (ctx->state == MTP_TCP_ESTABLISHED_ST){
				ctx->state = MTP_TCP_CLOSE_WAIT_ST;
				MTP_PRINT("Stream %d: TCP_ST_CLOSE_WAIT\n", cur_stream->id);
				/* notify FIN to application */
				RaiseReadEvent(mtcp, cur_stream);
		}

		else if (ctx->state == MTP_TCP_FIN_WAIT_1_ST) {
			ctx->state = MTP_TCP_CLOSING_ST;
			send_ack = TRUE;
			MTP_PRINT("Stream %d: TCP_ST_CLOSING\n", cur_stream->id);

		} else if (ctx->state == MTP_TCP_FIN_WAIT_2_ST) {
			send_ack = TRUE;
			ctx->state = MTP_TCP_TIME_WAIT_ST;
			MTP_PRINT("Stream %d: TCP_ST_TIME_WAIT\n", cur_stream->id);
			//AddtoTimewaitList(mtcp, cur_stream, cur_ts);
		}
	}
	if (send_ack)
	{
		mtp_bp* bp = GetFreeBP(cur_stream);

		// MTP_PRINT("got bp\n");
		// MTP_PRINT("index: %u\n", cur_stream->sndvar->mtp_bps_tail);
		
		memset(&(bp->hdr), 0, sizeof(struct mtp_bp_hdr) + sizeof(struct mtp_bp_options));

		bp->hdr.fin = FALSE; 
		if (ctx->state == MTP_TCP_CLOSING_ST){
			if ((ctx->fin_sent && ctx->send_next == ctx->final_seq) ||
				(!ctx->fin_sent)){
					bp->hdr.fin = TRUE;
					ctx->fin_sent = TRUE;
			}
		}

		bp->hdr.source = cur_stream->mtp->local_port;
		bp->hdr.dest = cur_stream->mtp->remote_port;
		bp->hdr.seq = htonl(ctx->send_next);
		if (bp->hdr.fin){
			bp->hdr.seq = htonl(ctx->final_seq);
		}
		// MTP_PRINT("Seq ack_ep: %u\n", ntohl(bp->hdr.seq));
		bp->hdr.ack_seq = htonl(ctx->recv_next);

		bp->hdr.syn = FALSE;
		bp->hdr.ack = TRUE;

		// options to calculate data offset

		// MTP TODO: SACK? 
	#if TCP_OPT_SACK_ENABLED
		MTP_PRINT("ERROR:SACK Not supported in MTP TCP\n");
	#endif

		MTP_set_opt_nop(&(bp->opts.nop1));
		MTP_set_opt_nop(&(bp->opts.nop2));

		// MTP TODO: Timestamp
		MTP_set_opt_timestamp(&(bp->opts.timestamp),
								htonl(cur_ts),
								htonl(ctx->ts_recent));
		

		// MTP TODO: would the MTP program do the length 
		//           calculation itself?
		uint16_t optlen = MTP_CalculateOptionLength(bp);
		bp->hdr.doff = (MTP_HEADER_LEN + optlen) >> 2;

		// MTP TODO: wscale on local
		uint32_t window32 = ctx->rwnd_size >> ctx->wscale;
		uint16_t advertised_window = MIN(window32, TCP_MAX_WINDOW);
		bp->hdr.window = htons(advertised_window);
		if (advertised_window == 0) ctx->adv_zero_wnd = TRUE;

		// Payload
		// MTP TODO: fix snbuf
		bp->payload.data = NULL;
		bp->payload.len = 0;
		bp->payload.needs_segmentation = FALSE;

		AddtoGenList(mtcp, cur_stream, cur_ts);

	}
}
