/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog_params.h"
#include "prog_types.h"
#include "prog_ctx.h"

#define TCPBP_src_port_OFF	0
#define TCPBP_dst_port_OFF	2
#define TCPBP_seq_no_OFF	4
#define TCPBP_ack_seq_OFF	8
#define TCPBP_data_off_OFF	12
#define TCPBP_flags_OFF	13
#define TCPBP_window_OFF	14
#define TCPBP_checksum_OFF	16
#define TCPBP_urg_ptr_OFF	18
#define TCPBP_FIXED_LEN	20

/*
 * Serialise the blueprint ONCE, when it is built -- not per segment. The
 * per-segment work is the recurrence in mtp_program_segment.
 */
static uint16_t
TCPBP_build(uint8_t *out, const struct TCPBP *b)
{
	uint16_t hdr_len;

	memset(out, 0, TCPBP_FIXED_LEN);
	{ uint16_t w = htons(b->src_port); memcpy(out + 0, &w, 2); }
	{ uint16_t w = htons(b->dst_port); memcpy(out + 2, &w, 2); }
	{ uint32_t w = htonl(b->seq_no); memcpy(out + 4, &w, 4); }
	{ uint32_t w = htonl(b->ack_seq); memcpy(out + 8, &w, 4); }
	out[13] = b->flags;
	{ uint16_t w = htons(b->window); memcpy(out + 14, &w, 2); }
	{ uint16_t w = htons(b->urg_ptr); memcpy(out + 18, &w, 2); }
	memcpy(out + TCPBP_FIXED_LEN, b->__opt, b->__opt_len);
	hdr_len = (uint16_t)(TCPBP_FIXED_LEN + b->__opt_len);
	/* hdrlen4_t: a property of the layout, so the compiler fills it */
	out[12] = (uint8_t)((hdr_len / 4) << 4);
	return hdr_len;
}

static void
TCPBP_add_opt_mss(struct TCPBP *b, uint16_t mss)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 2;
	*p++ = 4;
	{ uint16_t w = htons(mss); memcpy(p, &w, 2); p += 2; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

static void
TCPBP_add_opt_nop(struct TCPBP *b)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 1;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

static void
TCPBP_add_opt_ts(struct TCPBP *b, uint32_t ts_val, uint32_t ts_ecr)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 8;
	*p++ = 10;
	{ uint32_t w = htonl(ts_val); memcpy(p, &w, 4); p += 4; }
	{ uint32_t w = htonl(ts_ecr); memcpy(p, &w, 4); p += 4; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

static void
TCPBP_add_opt_wscale(struct TCPBP *b, uint8_t wscale)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 3;
	*p++ = 3;
	*p++ = wscale;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

static int
TCPBP_extract(struct TCPBP *b, const uint8_t *in, uint16_t len)
{
	uint32_t i = 0, olen;

	memset(b, 0, sizeof(*b));	/* absent reads as absent */
	if (len < TCPBP_FIXED_LEN)
		return -1;
	{ uint16_t w; memcpy(&w, in + TCPBP_src_port_OFF, 2); b->src_port = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_dst_port_OFF, 2); b->dst_port = ntohs(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_seq_no_OFF, 4); b->seq_no = ntohl(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_ack_seq_OFF, 4); b->ack_seq = ntohl(w); }
	b->flags = in[TCPBP_flags_OFF];
	{ uint16_t w; memcpy(&w, in + TCPBP_window_OFF, 2); b->window = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_urg_ptr_OFF, 2); b->urg_ptr = ntohs(w); }
	b->data_off = (uint8_t)(in[TCPBP_data_off_OFF] >> 4);
	olen = (uint32_t)(b->data_off * 4);
	if (olen < TCPBP_FIXED_LEN || olen > len)
		return -1;
	olen -= TCPBP_FIXED_LEN;

	while (i < olen) {
		uint8_t kind = in[TCPBP_FIXED_LEN + i];

		if (kind == 0)			/* end of list: TERMINATES */
			return 0;
		if (kind == 1) { i++; continue; }	/* no-op */
		if (i + 1 >= olen)
			return 0;
		if (in[TCPBP_FIXED_LEN + i + 1] < 2)	/* a zero length would loop */
			return 0;
		if (kind == 2 && in[TCPBP_FIXED_LEN + i + 1] == 4 && i + 4 <= olen) {
			b->__opt_mss_present = true;
			{ uint16_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 2); b->__opt_mss_mss = ntohs(w); }
		}
		if (kind == 8 && in[TCPBP_FIXED_LEN + i + 1] == 10 && i + 10 <= olen) {
			b->__opt_ts_present = true;
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 4); b->__opt_ts_ts_val = ntohl(w); }
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 6, 4); b->__opt_ts_ts_ecr = ntohl(w); }
		}
		if (kind == 3 && in[TCPBP_FIXED_LEN + i + 1] == 3 && i + 3 <= olen) {
			b->__opt_wscale_present = true;
			b->__opt_wscale_wscale = in[TCPBP_FIXED_LEN + i + 2];
		}
		i += in[TCPBP_FIXED_LEN + i + 1];
	}
	return 0;
}

/*
 * mtp/tcp.mtp §build_hdr
 * ---------------------------------------------------------------------------
 * THE ONE PLACE AN OUTBOUND HEADER IS BUILT, and it is a program function
 * rather than compiler output because THREE PROTOCOL SIDE EFFECTS HANG OFF IT.
 *
 *   - every packet that acknowledges resets the window probe's clock. That is
 *     the donor's rule (tcp_out.c:293) and was not ours: ours stamped it only
 *     when a probe was emitted, so the gate measured the interval between
 *     probes and we probed where the donor would not;
 *   - the same line stamps the donor's activity clock (tcp_out.c:293-296, and
 *     again on every received packet at tcp_in.c:1292), which is what our idle
 *     timer restart stands in for;
 *   - D11 ARM. The donor sets need_wnd_adv when the SCALED FIELD it is about to
 *     put on the wire is zero (tcp_out.c:304-309) — not when rcv_wnd is small.
 */
struct TCPBP
build_hdr(struct tcp_ctx *ctx, uint32_t seq, uint8_t flags, uint32_t now)
{
	struct TCPBP bp = { 0 };
	bool is_syn = (((flags & FLAG_SYN)) != 0);
	if ((((flags & FLAG_ACK)) != 0)) {
		ctx->last_ack_sent_ms = now;
		if (((ctx->state != ST_CLOSED) && (ctx->state != ST_TIME_WAIT))) {
			(ctx->idle_timer).ctx = ctx;
			mtp_timer_start(&(ctx->idle_timer), ((uint64_t)(tcp_timeout) * 1000000000ULL));
		}
	}
	bp.src_port = ctx->loc_port;
	bp.dst_port = ctx->rem_port;
	bp.seq_no = seq;
	bp.ack_seq = ctx->recv_next;
	bp.flags = (PARITY_SET_PSH ? flags : ((flags & ~(FLAG_PSH))));
	bp.window = (is_syn ? (uint16_t)(ctx->rcv_wnd) : (uint16_t)((ctx->rcv_wnd >> PARITY_WSCALE)));
	bp.urg_ptr = 0;
	if ((bp.window == 0)) {
		ctx->need_wnd_adv = true;
	}
	if (is_syn) {
		TCPBP_add_opt_mss(&bp, PARITY_MSS_ADVERTISED);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_ts(&bp, now, ctx->ts_recent);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_wscale(&bp, PARITY_WSCALE);
	} else {
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_ts(&bp, now, ctx->ts_recent);
	}
	return bp;
}

/*
 * mtp/tcp.mtp §build_rst_hdr
 * ---------------------------------------------------------------------------
 * A reset's header, built WITHOUT A CONTEXT, because a reset for a connection
 * that does not exist has none. Ports come from the offending segment with the
 * halves swapped, and there are NO OPTIONS: the donor's SendTCPPacketStandalone
 * sends none on this path, and a timestamp echo would need a `ts_recent` we
 * have never had. The window is zero, because there is no receive buffer behind
 * a connection that does not exist, and the donor passes 0 at every standalone
 * site.
 */
struct TCPBP
build_rst_hdr(uint16_t loc_port, uint16_t rem_port, uint32_t seq, uint32_t ack, uint8_t flags)
{
	struct TCPBP bp = { 0 };
	bp.src_port = loc_port;
	bp.dst_port = rem_port;
	bp.seq_no = seq;
	bp.ack_seq = ack;
	bp.flags = flags;
	bp.window = 0;
	bp.urg_ptr = 0;
	return bp;
}

/*
 * mtp/tcp.mtp §net_parser
 * ---------------------------------------------------------------------------
 * parse_tcp : a segment -> the list of events it raises.
 *
 * INCLUSIVE, which is the donor's shape: Handle_TCP_ST_ESTABLISHED runs three
 * independent tests on one packet, so a segment carrying payload, an
 * acknowledgement and a FIN does all three jobs. One event per segment would
 * drop the payload of a data-carrying FIN.
 *
 *   RST                   -> tcp_rst        (alone -- the donor returns from
 *                                            ProcessTCPPacket, delivering no
 *                                            payload and retiring no ack)
 *   SYN, no ACK           -> tcp_syn        (alone: nothing else in sequence)
 *   SYN + ACK             -> tcp_synack     (alone, likewise)
 *   ACK                   -> tcp_ack
 *   payload               -> tcp_data
 *   FIN                   -> tcp_fin
 *
 * The last three compose, in the order acknowledgement, payload, FIN.
 * proc_congestion is in the tcp_ack chain and reads `ack - send_una`, so
 * retiring the bytes first would leave the congestion window seeing nothing
 * newly acknowledged.
 *
 * THE PARSER ISSUES INSTRUCTIONS AND RESOLVES CONTEXTS, which the frozen
 * language does not say it may (docs/LANGUAGE-NEEDS.md N-E). It has to --
 * three jobs here are protocol policy and none can be done from a chain:
 *
 *   a segment for a connection that does not exist is answered with a RESET,
 *   and a chain is dispatched THROUGH a context;
 *
 *   a SYN is matched against a LISTENER, and backlog room decides whether a
 *   context is created at all (G8, C3);
 *
 *   validation refuses a segment BEFORE any event is raised, which is the
 *   donor's placement. As the first link of every chain instead, a segment
 *   raising two events would validate twice and owe a duplicate
 *   acknowledgement the donor does not send.
 */
unsigned
parse_tcp(const uint8_t *l4, uint16_t plen,
		const struct iphdr *iph, struct net_ev *ev, uint8_t *kinds,
		void **ctx_out, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	struct TCPBP bp;
	if (TCPBP_extract(&bp, l4, plen) < 0)
		return 0;
	uint32_t payload_len;
	if ((((plen < 20) || ((bp.data_off * 4) < 20)) || ((bp.data_off * 4) > plen))) {
		return __n;
	}
	payload_len = (plen - (bp.data_off * 4));
	flowkey_t fid = ((flowkey_t){ .kind = 0, .v0 = iph->daddr, .v1 = iph->saddr, .v2 = bp.dst_port, .v3 = bp.src_port });
	struct tcp_ctx *ctx = mtp_ctx_lookup(&(fid));
	if (!(((ctx) != NULL))) {
		bool refuse = ((((bp.flags & FLAG_SYN)) == 0) || (((bp.flags & FLAG_ACK)) != 0));
		flowkey_t lk = ((flowkey_t){ .kind = 1, .v0 = iph->daddr, .v1 = bp.dst_port });
		struct tcp_listen_ctx *lst = mtp_ctx_lookup(&(lk));
		if ((!(refuse) && ((!(((lst) != NULL)) || (lst->state != ST_LISTEN))))) {
			refuse = true;
		}
		if (refuse) {
			if ((((bp.flags & FLAG_RST)) != 0)) {
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			if ((((bp.flags & FLAG_ACK)) != 0)) {
				struct TCPBP __t0 = build_rst_hdr(bp.dst_port, bp.src_port, bp.ack_seq, 0, FLAG_RST);
				uint8_t __t1[PROG_HDR_MAX];
				uint16_t __t2 = TCPBP_build(__t1, &__t0);
				mtp_pkt_gen_orphan(iph->daddr, iph->saddr, __t1, __t2, PROG_OFFLOAD);
			} else {
				struct TCPBP __t3 = build_rst_hdr(bp.dst_port, bp.src_port, 0, ((bp.seq_no + payload_len) + (((((bp.flags & FLAG_SYN)) != 0) ? 1 : 0))), (FLAG_RST | FLAG_ACK));
				uint8_t __t4[PROG_HDR_MAX];
				uint16_t __t5 = TCPBP_build(__t4, &__t3);
				mtp_pkt_gen_orphan(iph->daddr, iph->saddr, __t4, __t5, PROG_OFFLOAD);
			}
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		if ((lst->pending_n >= lst->pending_cap)) {
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		ctx = mtp_new_ctx(&(fid), sizeof(struct tcp_ctx));
		if (!ctx)
			return __n;
		ctx->state = ST_CLOSED;
		ctx->send_wnd = 65535;
		ctx->cwnd = PARITY_INIT_CWND;
		ctx->rcv_wnd = PARITY_INITIAL_WINDOW;
		ctx->key = fid;
		ctx->lst_key = lk;
		ctx->loc_port = bp.dst_port;
		ctx->rem_port = bp.src_port;
		ctx->local_ip = iph->daddr;
		ctx->remote_ip = iph->saddr;
		ev->seq = bp.seq_no;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->has_ts = bp.__opt_ts_present;
		ev->wscale = bp.__opt_wscale_wscale;
		ev->has_wscale = bp.__opt_wscale_present;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_syn;
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if (((ctx->state != ST_CLOSED) && (ctx->state != ST_TIME_WAIT))) {
		(ctx->idle_timer).ctx = ctx;
		mtp_timer_start(&(ctx->idle_timer), ((uint64_t)(tcp_timeout) * 1000000000ULL));
	}
	bool accept = false;
	uint32_t seg_end;
	if (((((ctx->state == ST_CLOSED) || (ctx->state == ST_LISTEN)) || (ctx->state == ST_SYN_RCVD)) || (ctx->state == ST_SYN_SENT))) {
		accept = true;
	} else {
		if (((((bp.flags & FLAG_RST)) == 0) && ctx->saw_timestamp)) {
			if (!(bp.__opt_ts_present)) {
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			if (((int32_t)((bp.__opt_ts_ts_val - ctx->ts_recent)) < 0)) {
				ctx->ack_cnt = (ctx->ack_cnt + 1);
				mtp_retry(ctx->f);
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			ctx->ts_recent = bp.__opt_ts_ts_val;
		}
		seg_end = (bp.seq_no + payload_len);
		if ((((int32_t)((seg_end - ctx->recv_next)) >= 0) && ((int32_t)((seg_end - ((ctx->recv_next + ctx->rcv_wnd)))) <= 0))) {
			accept = true;
		}
	}
	if (!(accept)) {
		if ((((bp.flags & FLAG_RST)) != 0)) {
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		if ((ctx->state == ST_ESTABLISHED)) {
			if ((((bp.seq_no + 1) == ctx->recv_next) || ((int32_t)((bp.seq_no - ctx->recv_next)) <= 0))) {
				if ((ctx->ack_cnt == 0)) {
					ctx->ack_cnt = 1;
				}
				mtp_retry(ctx->f);
			} else {
				ctx->ack_cnt = (ctx->ack_cnt + 1);
				mtp_retry(ctx->f);
			}
		} else {
			if ((ctx->state == ST_TIME_WAIT)) {
				ctx->state = ST_TIME_WAIT;
				(ctx->tw_timer).ctx = ctx;
				mtp_timer_start(&(ctx->tw_timer), ((uint64_t)(tcp_timewait) * 1000000000ULL));
			}
			ctx->ack_cnt = (ctx->ack_cnt + 1);
			mtp_retry(ctx->f);
		}
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_RST)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_rst;
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_SYN)) != 0)) {
		if ((((bp.flags & FLAG_ACK)) != 0)) {
			ev->seq = bp.seq_no;
			ev->ack = bp.ack_seq;
			ev->window = bp.window;
			ev->ts_val = bp.__opt_ts_ts_val;
			ev->ts_ecr = bp.__opt_ts_ts_ecr;
			ev->has_ts = bp.__opt_ts_present;
			ev->wscale = bp.__opt_wscale_wscale;
			ev->has_wscale = bp.__opt_wscale_present;
			ev->__key = fid;
			kinds[__n++] = EV_tcp_synack;
		}
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_ACK)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->ts_ecr = bp.__opt_ts_ts_ecr;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_ack;
	}
	if ((payload_len > 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->hold_addr = (struct mtp_rx_addr){ .data = l4 + bp.data_off * 4, .len = (uint32_t)(plen - bp.data_off * 4) };
		ev->data_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_data;
	}
	if ((((bp.flags & FLAG_FIN)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_fin;
	}
	if (ctx_out)
		*ctx_out = ctx;
	return __n;
}

/*
 * mtp/tcp.mtp §proc_passive_open
 * ---------------------------------------------------------------------------
 * A SYN with no context, and a listener that matches. The parser created the
 * context and recorded the endpoints; everything the handshake decides is here.
 */
void
proc_passive_open(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	ctx->state = ST_SYN_RCVD;
	ctx->recv_next = (ev->seq + 1);
	ctx->rcv_base = ctx->recv_next;
	ctx->delivered = ctx->rcv_base;
	mtp_sw_init(&(ctx->rx_wnd), ctx->recv_next);
	ctx->saw_timestamp = ev->has_ts;
	ctx->ts_recent = ev->ts_val;
	ctx->snd_wscale = (ev->has_wscale ? ev->wscale : 0);
	ctx->send_wnd = ev->window;
	ctx->send_una = PARITY_ISN;
	ctx->send_next = PARITY_ISN;
	ctx->cwnd = PARITY_INIT_CWND;
	ctx->ssthresh = (PARITY_OPENING_TRAJECTORY ? PARITY_SSTHRESH_PASSIVE : PARITY_SSTHRESH_ACTIVE);
	struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, (FLAG_SYN | FLAG_ACK), now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	if ((mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_CONTROL, PROG_OFFLOAD, false) == 0)) {
		ctx->send_next = (ctx->send_next + 1);
		ctx->snd_base = ctx->send_next;
		if (!(ctx->tx_open)) {
			mtp_new_tx_ordered_data(&(ctx->tx), MTP_SIZE_INF);
			ctx->tx_open = true;
		}
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_open_done
 * ---------------------------------------------------------------------------
 * The acknowledgement that completes a passive open.
 */
void
proc_open_done(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if ((ctx->state != ST_SYN_RCVD)) {
		return;
	}
	if ((ev->ack != ctx->send_next)) {
		return;
	}
	ctx->send_una = ev->ack;
	ctx->send_wnd = ((uint32_t)(ev->window) << ctx->snd_wscale);
	ctx->ts_recent = ev->ts_val;
	ctx->state = ST_ESTABLISHED;
	struct tcp_listen_ctx *lst = mtp_ctx_lookup(&(ctx->lst_key));
	if ((((lst) != NULL) && (lst->pending_n < PROG_MAX_BACKLOG))) {
		lst->pending[lst->pending_n] = ctx->key;
		lst->pending_n = (lst->pending_n + 1);
		mtp_notify(lst->f, &(struct mtp_notif){ .kind = MTP_NOTIF_READABLE });
	}
	if ((((lst) != NULL) && (lst->obj_len > 0))) {
		uint32_t wrote = mtp_add_tx_data(&(ctx->tx), lst->obj, lst->obj_len);
		if ((wrote > 0)) {
			struct tcp_scratch gs = { 0 };
			ctx->write_end = (ctx->write_end + wrote);
			gen_seg(ctx, &gs, now_ms);
			drain_owed_acks(ctx, &gs, now_ms);
			gen_wnd_adv(ctx, now_ms);
		}
		ctx->app_closed = true;
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_timestamp
 * ---------------------------------------------------------------------------
 * Record the peer's echo for our own.
 *
 * ONLY FOR A PEER THAT DOES NOT TIMESTAMP. For one that does, the parser
 * has already set it — before dispatch, and only for a segment it accepted,
 * which is the donor's placement.
 */
void
proc_timestamp(struct net_ev *ev, struct tcp_ctx *ctx)
{
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	if (!(ctx->saw_timestamp)) {
		ctx->ts_recent = ev->ts_val;
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_window
 * ---------------------------------------------------------------------------
 * The peer's advertised window, RFC 793's rule.
 *
 * A SEPARATE PROCESSOR, AND AHEAD OF §proc_fast_retransmit, because the donor
 * updates the window BEFORE it counts duplicates and the duplicate test asks
 * whether that update moved the right edge. Folded into §proc_congestion, where
 * it used to live, the test could not be written.
 */
void
proc_window(struct net_ev *ev, struct tcp_ctx *ctx)
{
	uint32_t cwindow;
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	cwindow = ((uint32_t)(ev->window) << ctx->snd_wscale);
	ctx->right_wnd_edge = (ctx->snd_wl2 + ctx->send_wnd);
	if (((((int32_t)((ctx->snd_wl1 - ev->seq)) < 0) || (((ctx->snd_wl1 == ev->seq) && ((int32_t)((ctx->snd_wl2 - ev->ack)) < 0)))) || (((ctx->snd_wl2 == ev->ack) && (cwindow > ctx->send_wnd))))) {
		ctx->send_wnd = cwindow;
		ctx->snd_wl1 = ev->seq;
		ctx->snd_wl2 = ev->ack;
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_rtt
 * ---------------------------------------------------------------------------
 * The round-trip estimate. Guarded on the acknowledgement ADVANCING, which is
 * why it sits ahead of §proc_ack in the chain: §proc_ack is what moves
 * send_una, so this must read it first.
 */
void
proc_rtt(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	uint32_t m;
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	if (((int32_t)((ev->ack - ctx->send_una)) <= 0)) {
		return;
	}
	if ((ev->ts_ecr == 0)) {
		return;
	}
	m = (now_ms - ev->ts_ecr);
	if ((m == 0)) {
		m = 1;
	}
	if ((ctx->srtt == 0)) {
		ctx->srtt = (m << 3);
		ctx->mdev = (m << 1);
	} else {
		int32_t d = ((int32_t)(m) - (int32_t)((ctx->srtt >> 3)));
		ctx->srtt = (uint32_t)(((int32_t)(ctx->srtt) + d));
		if ((d < 0)) {
			d = -(d);
			d = (d - (int32_t)((ctx->mdev >> 2)));
			if ((d > 0)) {
				d = (d >> 3);
			}
		} else {
			d = (d - (int32_t)((ctx->mdev >> 2)));
		}
		ctx->mdev = (uint32_t)(((int32_t)(ctx->mdev) + d));
	}
	ctx->rttvar = ctx->mdev;
	ctx->rto_ms = (((ctx->srtt >> 3)) + ctx->rttvar);
	ctx->have_rtt = true;
	return;
}

/*
 * mtp/tcp.mtp §proc_fast_retransmit
 * ---------------------------------------------------------------------------
 * Retransmit on the third duplicate. D-30 settled what goes here and this does
 * it: the donor's behaviour exactly, third duplicate only, INCLUDING its
 * refusal to attempt a send on the fourth and later.
 *
 * THE DONOR'S FIVE CONDITIONS, in its own order (tcp_in.c:373-396): the
 * acknowledgement is old, carries no payload, leaves the window's right edge
 * where it was, and repeats the last one seen. `snd_wl2 + send_wnd` is the
 * right edge AFTER §proc_window has run, so comparing it against the edge
 * BEFORE is what "the window did not change" means.
 */
void
proc_fast_retransmit(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	bool dup = false;
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	if ((((((int32_t)((ev->ack - ctx->send_next)) < 0) && (ev->ack == ctx->last_ack_seq)) && (ev->payload_len == 0)) && ((ctx->snd_wl2 + ctx->send_wnd) == ctx->right_wnd_edge))) {
		ctx->dup_acks = (ctx->dup_acks + 1);
		dup = true;
	}
	if (!(dup)) {
		ctx->dup_acks = 0;
		ctx->last_ack_seq = ev->ack;
		return;
	}
	if ((ctx->dup_acks == PARITY_DUP_ACK_THRESH)) {
		if (((int32_t)((ev->ack - ctx->send_next)) < 0)) {
			ctx->send_next = ev->ack;
		}
		ctx->ssthresh = ((((ctx->cwnd < ctx->send_wnd) ? ctx->cwnd : ctx->send_wnd)) / 2);
		if ((ctx->ssthresh < (2 * PARITY_MSS_ADVERTISED))) {
			ctx->ssthresh = (2 * PARITY_MSS_ADVERTISED);
		}
		ctx->cwnd = (ctx->ssthresh + (3 * PARITY_MSS_ADVERTISED));
		if ((ctx->rtx_count < PARITY_MAX_RTX)) {
			ctx->rtx_count = (ctx->rtx_count + 1);
		}
	} else {
		if ((ctx->dup_acks > PARITY_DUP_ACK_THRESH)) {
			if (((ctx->cwnd + PARITY_MSS_ADVERTISED) > ctx->cwnd)) {
				ctx->cwnd = (ctx->cwnd + PARITY_MSS_ADVERTISED);
			}
			s->no_send = true;
		} else {
			s->no_send = true;
		}
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_congestion
 * ---------------------------------------------------------------------------
 * The congestion window, and the guard for an acknowledgement past send_next.
 */
void
proc_congestion(struct net_ev *ev, struct tcp_ctx *ctx)
{
	uint32_t acked;
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	acked = (ev->ack - ctx->send_una);
	if (((int32_t)(acked) <= 0)) {
		return;
	}
	if (((int32_t)((ev->ack - ctx->send_next)) > 0)) {
		ctx->send_next = ev->ack;
		ctx->cwnd = ctx->ssthresh;
	}
	uint32_t packets = (acked / PARITY_MSS_PAYLOAD);
	if (((packets > 0) && (ctx->cwnd >= ctx->ssthresh))) {
		ctx->cwnd = (ctx->cwnd + ((((PARITY_MSS_ADVERTISED * PARITY_MSS_ADVERTISED)) / ctx->cwnd) * packets));
	} else {
		if ((packets > 0)) {
			ctx->cwnd = (ctx->cwnd + (PARITY_MSS_ADVERTISED * packets));
		}
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_ack
 * ---------------------------------------------------------------------------
 * Retire the acknowledged bytes, and our own FIN, which consumes sequence
 * space.
 *
 * It does not call the generator. §gen_seg follows it in every chain that can
 * send, so the duplicate case that used to call the generator inline simply
 * returns and the dispatch runs it — DEFERRED.md D2, one of the two places the
 * dispatch was hand-inlined.
 */
void
proc_ack(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	uint32_t acked;
	if (!(((((ctx->state != ST_CLOSED) && (ctx->state != ST_LISTEN)) && (ctx->state != ST_SYN_RCVD))))) {
		return;
	}
	if ((ev->ack == ctx->send_next)) {
		if ((ctx->state == ST_LAST_ACK)) {
			ctx->state = ST_CLOSED;
			s->__ctx_dead = true;
			mtp_del_ctx(&(ctx->key));
			return;
		}
		if ((ctx->state == ST_FIN_WAIT_1)) {
			ctx->state = ST_FIN_WAIT_2;
		} else {
			if ((ctx->state == ST_CLOSING)) {
				ctx->state = ST_TIME_WAIT;
				(ctx->tw_timer).ctx = ctx;
				mtp_timer_start(&(ctx->tw_timer), ((uint64_t)(tcp_timewait) * 1000000000ULL));
			}
		}
	}
	acked = (ev->ack - ctx->send_una);
	if (((int32_t)(acked) <= 0)) {
		return;
	}
	s->acked = acked;
	if ((ctx->fin_pending && ((int32_t)((ev->ack - ((ctx->fin_seq + 1)))) >= 0))) {
		ctx->fin_pending = false;
	}
	ctx->send_una = ev->ack;
	mtp_tx_flush_and_notify(&(ctx->tx), acked);
	ctx->rtx_count = 0;
	mtp_timer_stop(&(ctx->rto_timer));
	if (((((ctx->tx_open && (mtp_tx_emitted(&(ctx->tx)) > ((ctx->send_una - ctx->snd_base))))) || ((ctx->fin_pending && (ctx->send_una != ctx->send_next)))))) {
		(ctx->rto_timer).ctx = ctx;
		mtp_timer_start(&(ctx->rto_timer), ((uint64_t)((((ctx->have_rtt ? ctx->rto_ms : PARITY_INITIAL_RTO_MS)) << (((ctx->rtx_count < 7) ? ctx->rtx_count : 7)))) * 1000000ULL));
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_recv
 * ---------------------------------------------------------------------------
 * Payload, in order or not: stores it at its own sequence number, marks the
 * range in rx_wnd, slides, and recomputes the window if the boundary moved. The
 * acknowledgement it owes is §send_ack's, next in the chain.
 */
void
proc_recv(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	uint32_t next;
	if (!(((((ctx->state == ST_ESTABLISHED) || (ctx->state == ST_FIN_WAIT_1)) || (ctx->state == ST_FIN_WAIT_2))))) {
		return;
	}
	if ((ev->data_len == 0)) {
		return;
	}
	if (!(ctx->rx_open)) {
		mtp_new_rx_ordered_data(&(ctx->rx), MTP_SIZE_INF);
		ctx->rx_open = true;
	}
	if ((mtp_add_rx_data_seg(&(ctx->rx), ev->hold_addr, ev->data_len, ev->seq) < 0)) {
		return;
	}
	mtp_sw_set(&(ctx->rx_wnd), ev->seq, (ev->seq + ev->data_len));
	next = mtp_sw_slide(&(ctx->rx_wnd));
	if ((next != ctx->recv_next)) {
		ctx->recv_next = next;
		ctx->rcv_wnd = (PARITY_RCVBUF_SIZE - ((((ctx->recv_next - ctx->delivered)) - ((((ctx->fin_consumed && (ctx->recv_next != ctx->delivered))) ? 1 : 0)))));
		s->ack_opt = ACK_AGGREGATE;
	} else {
		s->ack_opt = ACK_APIECE;
	}
	return;
}

/*
 * mtp/tcp.mtp §send_ack
 * ---------------------------------------------------------------------------
 * Record what the chain decided it owed. The donor's EnqueueACK
 * (tcp_out.c:1088-1096): AGGREGATE raises ack_cnt to 1 if it is 0, so a pass
 * owes one acknowledgement for all its in-order segments; APIECE increments,
 * so a segment past a hole owes its own duplicate. Those duplicates are what
 * trips the peer's fast retransmit.
 *
 * IT RE-TESTS NOTHING. Every guard deciding whether an acknowledgement is due
 * lives at the decision site; this acts only on s.ack_opt. That is what makes
 * it safe to run after proc_fin's state transition.
 *
 * POST-FIN SUPPRESSION IS PER-PATH, NOT PER-CONNECTION (D-20). Once a FIN is
 * accepted the DATA path stops acknowledging that stream permanently; the
 * CONTROL path does not, and must not -- the donor sends pure acknowledgements
 * after a FIN from CLOSE_WAIT (tcp_out.c:632-634), FIN_WAIT_2 (:655-657) and
 * TIME_WAIT (:675-677), and the CLOSE_WAIT one is what acknowledges the peer's
 * FIN. Suppress it and teardown stalls.
 *
 * The effect is reproduced, not the structure: the donor's suppression is
 * emergent from its counter arithmetic, and we have one queue rather than
 * three, so what has to hold is the observable.
 */
void
send_ack(struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	if ((s->ack_opt == ACK_NONE)) {
		return;
	}
	if ((s->ack_opt == ACK_AGGREGATE)) {
		if ((ctx->ack_cnt == 0)) {
			ctx->ack_cnt = 1;
		}
	} else {
		ctx->ack_cnt = (ctx->ack_cnt + 1);
	}
	mtp_retry(ctx->f);
	return;
}

/*
 * mtp/tcp.mtp §proc_fin
 * ---------------------------------------------------------------------------
 * Teardown: the peer closes.
 *
 * Ordering, from the prototype and easy to invert: the acknowledgement is
 * DECIDED before the state transition, so it is still emitted for the FIN
 * itself. Transition first and the guard that silences the data path would
 * silence this too. Out of order is covered as well — a FIN arriving ahead of a
 * gap does not transition, and the later segment that fills the hole makes this
 * processor perform the transition and still owe the acknowledgement, because
 * the guard was evaluated before it. Either route owes exactly once.
 */
void
proc_fin(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	uint32_t fin_seq;
	if (!(((((ctx->state == ST_ESTABLISHED) || (ctx->state == ST_FIN_WAIT_1)) || (ctx->state == ST_FIN_WAIT_2))))) {
		return;
	}
	fin_seq = (ev->seq + ev->payload_len);
	if ((fin_seq != ctx->recv_next)) {
		s->ack_opt = ACK_APIECE;
		return;
	}
	ctx->recv_next = (fin_seq + 1);
	mtp_sw_set(&(ctx->rx_wnd), fin_seq, (fin_seq + 1));
	mtp_sw_slide(&(ctx->rx_wnd));
	ctx->fin_consumed = true;
	s->ack_opt = ACK_APIECE;
	if ((ctx->state == ST_FIN_WAIT_1)) {
		ctx->state = ST_CLOSING;
	} else {
		if ((ctx->state == ST_FIN_WAIT_2)) {
			ctx->state = ST_TIME_WAIT;
			(ctx->tw_timer).ctx = ctx;
			mtp_timer_start(&(ctx->tw_timer), ((uint64_t)(tcp_timewait) * 1000000000ULL));
		} else {
			bool was_established = (ctx->state == ST_ESTABLISHED);
			ctx->state = ST_CLOSE_WAIT;
			if (was_established) {
				mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_READABLE });
			}
		}
	}
	return;
}

/*
 * mtp/tcp.mtp §gen_fin
 * ---------------------------------------------------------------------------
 * Our FIN, gated on send_next == write_end (G10).
 *
 * The constraint is narrower than "order the FIN". Against data already turned
 * into blueprints the per-flow ring is FIFO, so a FIN committed after them
 * cannot overtake them. What must not happen is a FIN ahead of data the program
 * has NOT yet handed to the target — the window- or congestion-limited case —
 * which in the prototype goes out at one past ALL buffered data, leaving a
 * sequence gap and a second FIN once the buffer drains. So the gate is exactly:
 * send_next has caught up with write_end. The prototype gates this in one of
 * its two close paths and not the other, which is the evidence it is an
 * oversight rather than a decision.
 */
void
gen_fin(struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if (!(ctx->app_closed)) {
		return;
	}
	if (((ctx->state != ST_ESTABLISHED) && (ctx->state != ST_CLOSE_WAIT))) {
		return;
	}
	if (((ctx->send_next - ctx->snd_base) != ctx->write_end)) {
		return;
	}
	struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, (FLAG_ACK | FLAG_FIN), now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	if ((mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_DATA, PROG_OFFLOAD, false) == 0)) {
		ctx->fin_pending = true;
		ctx->fin_seq = ctx->send_next;
		ctx->send_next = (ctx->send_next + 1);
		ctx->state = ((ctx->state == ST_CLOSE_WAIT) ? ST_LAST_ACK : ST_FIN_WAIT_1);
	}
	return;
}

/*
 * mtp/tcp.mtp §mark_closed
 * ---------------------------------------------------------------------------
 * The application has no more to send.
 *
 * Split out of the close handler so that `app_close -> { mark_closed, gen_fin }`
 * is a chain the dispatch runs, not a processor calling a generator. That
 * direct call was the second of DEFERRED.md D2's two hand-inlined dispatches;
 * the first was §proc_ack's call to the generator.
 */
void
mark_closed(struct app_ev *ev, struct tcp_ctx *ctx)
{
	ctx->app_closed = true;
	return;
}

/*
 * mtp/tcp.mtp §record_data
 * ---------------------------------------------------------------------------
 * Application data appended to the transmit stream.
 *
 * RUNS ON THE CALLING THREAD, which is what makes the instruction below the
 * thing that CAUSES the copy rather than a note about one that already
 * happened. It touches the stream and `write_end`; neither generates a packet,
 * so nothing here belongs to the stack. The count it returns is what the
 * application is told it wrote, and a short return is back-pressure, not an
 * error.
 */
void
record_data(struct app_ev *ev, struct tcp_ctx *ctx)
{
	uint32_t wrote;
	if ((!((((ctx->state == ST_ESTABLISHED) || (ctx->state == ST_CLOSE_WAIT)))) || !(ctx->tx_open))) {
		ev->result = -(1);
		return;
	}
	wrote = mtp_add_tx_data(&(ctx->tx), ev->addr, ev->mlen);
	if ((wrote > 0)) {
		ctx->write_end = (ctx->write_end + wrote);
	}
	ev->result = (int32_t)(wrote);
	return;
}

/*
 * mtp/tcp.mtp §gen_seg
 * ---------------------------------------------------------------------------
 * The send decision, under min(cwnd, peer window).
 *
 * ONE pkt_gen for the whole sendable run: the target segments it and the
 * segmentation rule assigns each sequence number, so the recurrence is per
 * BYTE -- the program does not know how the run was split.
 *
 * The donor's loop predicate (tcp_out.c), reproduced rather than restated:
 *
 *     remaining = MIN(cwnd, peer_wnd) - (seq - snd_una)
 *     if (remaining <= 0 || (remaining < mss && seq - snd_una > 0)) bail
 *     len     = MIN(len, remaining)
 *     pkt_len = MIN(len, mss - 12)
 *
 * `seq - snd_una > 0` is an escape: with nothing in flight the silly-window
 * rule does not apply and the donor sends whatever fits, down to one byte.
 * Rounding to a multiple of the payload maximum instead would withhold the
 * last partial segment of every object for ever. The predicate tests unused
 * WINDOW, not bytes available -- the two come apart when the window binds.
 *
 * The donor's constants are kept: the window is compared against 1460 while a
 * segment consumes 1448. That mismatch is observable only when the remaining
 * window lands in [1448, 1460); one segment per RTO follows from cwnd == MSS,
 * not from the mismatch.
 *
 * Returns the number of packets sent, which the caller subtracts from
 * ack_cnt: a data packet carries the ACK flag, so it retires an
 * acknowledgement that would otherwise need its own frame.
 *
 * `inflight` counts GENERATED-unacknowledged, which includes blueprints still
 * in the ring. Basing it on the emitted position removes the only bound on
 * generation -- measured 0/0/4 completions against 28/26/28 -- so the
 * conflation stands until generation gets a bound of its own
 * (docs/DESIGN.md §25).
 */
void
gen_seg(struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms)
{
	(void)now_ms;
	uint32_t win;
	uint32_t to_send;
	uint32_t seq;
	uint32_t pkts;
	bool window_blocked = false;
	bool held_back = false;
	bool rtx;
	if (s->no_send) {
		return;
	}
	if (!((((ctx->state == ST_ESTABLISHED) || (ctx->state == ST_CLOSE_WAIT))))) {
		return;
	}
	win = ((ctx->cwnd < ctx->send_wnd) ? ctx->cwnd : ctx->send_wnd);
	seq = ctx->send_next;
	to_send = 0;
	while (true) {
		uint32_t inflight_here = (seq - ctx->send_una);
		int32_t rw = ((int32_t)(win) - (int32_t)(inflight_here));
		uint32_t avail_here;
		uint32_t len;
		uint32_t pkt;
		if ((rw <= 0)) {
			window_blocked = true;
			break;
		}
		if (((rw < (int32_t)(PARITY_MSS_ADVERTISED)) && (inflight_here > 0))) {
			held_back = true;
			break;
		}
		avail_here = (ctx->write_end - ((seq - ctx->snd_base)));
		if ((avail_here == 0)) {
			break;
		}
		len = ((avail_here < (uint32_t)(rw)) ? avail_here : (uint32_t)(rw));
		pkt = ((len < PARITY_MSS_PAYLOAD) ? len : PARITY_MSS_PAYLOAD);
		to_send = (to_send + pkt);
		seq = (seq + pkt);
	}
	if ((to_send == 0)) {
		if ((window_blocked || held_back)) {
			mtp_retry(ctx->f);
		}
		if (window_blocked) {
			(ctx->probe_timer).ctx = ctx;
			mtp_timer_start(&(ctx->probe_timer), ((uint64_t)(PARITY_PROBE_MS) * 1000000ULL));
		}
		return;
	}
	rtx = (ctx->send_next < ctx->send_high);
	struct TCPBP bp = build_hdr(ctx, ctx->send_next, FLAG_ACK, now_ms);
	bp.__pay.u   = &(ctx->tx);
	bp.__pay.off = (ctx->send_next - ctx->snd_base);
	bp.__pay.len = to_send;
	bp.__mss     = PARITY_MSS_PAYLOAD;
	uint8_t __t0[PROG_HDR_MAX];
	uint16_t __t1 = TCPBP_build(__t0, &bp);
	if ((mtp_pkt_gen(ctx->f, __t0, __t1, &bp.__pay, bp.__mss, PRIO_DATA, PROG_OFFLOAD, rtx) != 0)) {
		return;
	}
	pkts = ((((to_send + PARITY_MSS_PAYLOAD) - 1)) / PARITY_MSS_PAYLOAD);
	s->pkts_sent = (s->pkts_sent + pkts);
	ctx->send_next = (ctx->send_next + to_send);
	if ((ctx->send_next > ctx->send_high)) {
		ctx->send_high = ctx->send_next;
	}
	if (((((ctx->tx_open && (mtp_tx_emitted(&(ctx->tx)) > ((ctx->send_una - ctx->snd_base))))) || ((ctx->fin_pending && (ctx->send_una != ctx->send_next)))))) {
		(ctx->rto_timer).ctx = ctx;
		mtp_timer_start(&(ctx->rto_timer), ((uint64_t)((((ctx->have_rtt ? ctx->rto_ms : PARITY_INITIAL_RTO_MS)) << (((ctx->rtx_count < 7) ? ctx->rtx_count : 7)))) * 1000000ULL));
	}
	return;
}

/*
 * mtp/tcp.mtp §drain_owed_acks
 * ---------------------------------------------------------------------------
 * DATA FIRST, AND THAT ORDER IS THE POINT. The donor drains its send list
 * before its acknowledgement list, and every data packet it sends carries the
 * ACK flag — so it subtracts the packets sent from `ack_cnt` and only sends
 * separately whatever is still owed (ACK_PIGGYBACK, tcp_out.c:806-817, TRUE in
 * the donor's build).
 *
 * We had it backwards: acknowledgements first, then data. Every acknowledgement
 * therefore went out as its own packet even when a data packet in the same pass
 * was about to carry one. Invisible on a client, which sends nothing to carry
 * them; on a server it is a pure acknowledgement for every segment that a data
 * segment already acknowledged.
 */
void
drain_owed_acks(struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms)
{
	(void)now_ms;
	uint32_t sent = s->pkts_sent;
	ctx->ack_cnt = ((ctx->ack_cnt > sent) ? (ctx->ack_cnt - sent) : 0);
	while ((ctx->ack_cnt > 0)) {
		ctx->need_wnd_adv = false;
		struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, FLAG_ACK, now_ms);
		uint8_t __t1[PROG_HDR_MAX];
		uint16_t __t2 = TCPBP_build(__t1, &__t0);
		if ((mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_ACK, PROG_OFFLOAD, false) != 0)) {
			break;
		}
		ctx->ack_cnt = (ctx->ack_cnt - 1);
	}
	return;
}

/*
 * mtp/tcp.mtp §gen_wnd_adv
 * ---------------------------------------------------------------------------
 * D11, FIRE. The application drained and the window reopened; the peer is still
 * holding the zero we last advertised and will not send again until something
 * tells it otherwise. The donor enqueues an acknowledgement on its ackq from
 * CopyToUser and its stack sends it (api.c:1144-1151), gated on the window now
 * exceeding one segment.
 *
 * HERE RATHER THAN IN §proc_drain because that runs on the APPLICATION thread
 * and generation is the stack's (CR-4). §proc_drain raises the flag and asks
 * for a retry; this is the retry.
 */
void
gen_answer(struct app_ev *ev, struct tcp_ctx *ctx)
{
	ev->result = ((((ctx->state == ST_ESTABLISHED) || (ctx->state == ST_CLOSE_WAIT))) ? (int32_t)(ev->mlen) : -(1));
	return;
}

void
gen_wnd_adv(struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if ((!(ctx->need_wnd_adv) || (ctx->rcv_wnd <= PARITY_MSS_PAYLOAD))) {
		return;
	}
	ctx->need_wnd_adv = false;
	struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, FLAG_ACK, now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_ACK, PROG_OFFLOAD, false);
	return;
}

/*
 * mtp/tcp.mtp §proc_drain
 * ---------------------------------------------------------------------------
 * The application took bytes: §window_rule's RECOMPUTE POINT 2. `delivered`
 * advances by what the instruction REPORTS it handed over, so the accounting
 * cannot drift from what the target actually gave the application.
 *
 * The window that results is advertised on the next segment this flow sends —
 * one main-loop iteration later, as the donor does it. mTCP's application
 * thread never emits a packet, so deferring by one iteration is the donor's
 * behaviour and not a shortcut.
 */
void
proc_drain(struct app_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s)
{
	s->delivered = mtp_rx_flush_and_notify(&(ctx->rx), ev->len, ev->buf);
	if ((s->delivered == 0)) {
		ev->result = (ctx->fin_consumed ? 0 : -(1));
		return;
	}
	ev->result = (int32_t)(s->delivered);
	ctx->delivered = (ctx->delivered + s->delivered);
	ctx->rcv_wnd = (PARITY_RCVBUF_SIZE - ((((ctx->recv_next - ctx->delivered)) - ((((ctx->fin_consumed && (ctx->recv_next != ctx->delivered))) ? 1 : 0)))));
	if ((ctx->need_wnd_adv && (ctx->rcv_wnd > PARITY_MSS_PAYLOAD))) {
		mtp_retry(ctx->f);
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_rst
 * ---------------------------------------------------------------------------
 * The peer reset the connection. Reproduced from the donor's ProcessRST, and
 * TWO OF ITS ODDITIES ARE DELIBERATE:
 *
 *   - a reset on an ESTABLISHED connection leaves it in CLOSE_WAIT, not CLOSED,
 *     and destroys nothing. The donor's own destroy is commented out there. So
 *     the application still has to close it and the flow stays alive until it
 *     does;
 *   - the application is not told WHY. NotifyConnectionReset is commented out
 *     in the donor; it raises a close event, so the application learns the
 *     socket is readable and then reads end-of-stream.
 */
void
proc_rst(struct net_ev *ev, struct tcp_ctx *ctx)
{
	if (((ctx->state == ST_CLOSED) || (ctx->state == ST_LISTEN))) {
		return;
	}
	if ((ctx->state == ST_SYN_RCVD)) {
		if ((ev->ack == ctx->send_next)) {
			ctx->state = ST_CLOSED;
			mtp_del_ctx(&(ctx->key));
		}
		return;
	}
	if ((((((ctx->state == ST_FIN_WAIT_1) || (ctx->state == ST_FIN_WAIT_2)) || (ctx->state == ST_LAST_ACK)) || (ctx->state == ST_CLOSING)) || (ctx->state == ST_TIME_WAIT))) {
		ctx->state = ST_CLOSED;
		mtp_del_ctx(&(ctx->key));
		return;
	}
	ctx->state = ST_CLOSE_WAIT;
	ctx->fin_consumed = true;
	mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_READABLE });
	return;
}

/*
 * mtp/tcp.mtp §gen_syn
 * ---------------------------------------------------------------------------
 * Our SYN, emitted or re-attempted.
 *
 * The active open's first packet. It is a GENERATION step, not part of the open
 * chain, so the same retry that re-attempts a blocked send re-attempts an
 * unsent SYN — one path, not two.
 */
void
gen_syn(struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if (((ctx->state != ST_SYN_SENT) || (ctx->send_next != ctx->snd_base))) {
		return;
	}
	struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, FLAG_SYN, now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	if ((mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_CONTROL, PROG_OFFLOAD, false) != 0)) {
		mtp_retry(ctx->f);
		return;
	}
	ctx->send_next = (ctx->send_next + 1);
	ctx->snd_base = ctx->send_next;
	(ctx->rto_timer).ctx = ctx;
	mtp_timer_start(&(ctx->rto_timer), ((uint64_t)((((ctx->have_rtt ? ctx->rto_ms : PARITY_INITIAL_RTO_MS)) << (((ctx->rtx_count < 7) ? ctx->rtx_count : 7)))) * 1000000ULL));
	return;
}

/*
 * mtp/tcp.mtp §proc_synack
 * ---------------------------------------------------------------------------
 * The peer accepted our connection.
 *
 * Seeds everything the passive open seeds from a SYN, from the mirror image:
 * the peer's initial sequence number, its window and scale, its timestamp, and
 * whether it timestamps at all.
 */
void
proc_synack(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if ((ctx->state != ST_SYN_SENT)) {
		return;
	}
	if ((ev->ack != ctx->send_next)) {
		struct TCPBP __t0 = build_rst_hdr(ctx->loc_port, ctx->rem_port, ev->ack, 0, FLAG_RST);
		uint8_t __t1[PROG_HDR_MAX];
		uint16_t __t2 = TCPBP_build(__t1, &__t0);
		mtp_pkt_gen_orphan(ctx->local_ip, ctx->remote_ip, __t1, __t2, PROG_OFFLOAD);
		return;
	}
	ctx->send_una = ev->ack;
	ctx->recv_next = (ev->seq + 1);
	ctx->rcv_base = ctx->recv_next;
	mtp_sw_init(&(ctx->rx_wnd), ctx->recv_next);
	ctx->snd_wl1 = (ev->seq - 1);
	ctx->snd_wl2 = ev->ack;
	ctx->last_ack_seq = ev->ack;
	ctx->saw_timestamp = ev->has_ts;
	ctx->ts_recent = ev->ts_val;
	if (ev->has_wscale) {
		ctx->snd_wscale = ev->wscale;
	}
	ctx->send_wnd = ((uint32_t)(ev->window) << ctx->snd_wscale);
	ctx->cwnd = PARITY_INIT_CWND;
	ctx->ssthresh = PARITY_SSTHRESH_ACTIVE;
	ctx->rtx_count = 0;
	mtp_timer_stop(&(ctx->rto_timer));
	if (!(ctx->tx_open)) {
		mtp_new_tx_ordered_data(&(ctx->tx), MTP_SIZE_INF);
		ctx->tx_open = true;
	}
	ctx->state = ST_ESTABLISHED;
	mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_WRITABLE });
	struct TCPBP __t3 = build_hdr(ctx, ctx->send_next, FLAG_ACK, now_ms);
	uint8_t __t4[PROG_HDR_MAX];
	uint16_t __t5 = TCPBP_build(__t4, &__t3);
	mtp_pkt_gen(ctx->f, __t4, __t5, &__t3.__pay, __t3.__mss, PRIO_ACK, PROG_OFFLOAD, false);
	return;
}

/*
 * mtp/tcp.mtp §proc_rto
 * ---------------------------------------------------------------------------
 * The retransmission timeout, with backoff.
 *
 * After an RTO the donor sets cwnd = MSS and ssthresh = max(cwnd/2, 2*MSS). One
 * segment leaves, and the reason is that cwnd == MSS while a segment consumes
 * MSS - 12, so §gen_seg's window bail fires after the first segment regardless
 * of which constant it is compared against. It is NOT the 1460-versus-1448
 * mismatch, which was the earlier and wrong explanation.
 */
void
proc_rto(struct timer_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms)
{
	(void)now_ms;
	ctx->rtx_count = (ctx->rtx_count + 1);
	if ((ctx->rtx_count > PARITY_MAX_RTX)) {
		ctx->state = ST_CLOSED;
		mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_ERROR });
		return;
	}
	ctx->ssthresh = (((ctx->cwnd / 2) > (2 * PARITY_MSS_ADVERTISED)) ? (ctx->cwnd / 2) : (2 * PARITY_MSS_ADVERTISED));
	ctx->cwnd = PARITY_MSS_ADVERTISED;
	ctx->send_next = ctx->send_una;
	gen_seg(ctx, s, now_ms);
	struct TCPBP __t0 = build_hdr(ctx, ctx->send_next, (FLAG_ACK | FLAG_FIN), now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	if (((ctx->fin_pending && (ctx->send_next == ctx->fin_seq)) && (mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_DATA, PROG_OFFLOAD, true) == 0))) {
		ctx->send_next = (ctx->send_next + 1);
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_timewait_done
 * ---------------------------------------------------------------------------
 * The TIME_WAIT interval expired; the context goes.
 *
 * D-24 reproduces the DONOR'S GUARD, not its timer value: even at
 * tcp_timewait = 0 the state must be entered and left, because skipping it does
 * not skip a wait, it removes the place the final acknowledgement is owed from.
 * That acknowledgement was committed to the target in the iteration that
 * entered this state, so by the time this fires it has drained.
 */
void
proc_timewait_done(struct timer_ev *ev, struct tcp_ctx *ctx)
{
	ctx->state = ST_CLOSED;
	mtp_del_ctx(&(ctx->key));
	return;
}

/*
 * mtp/tcp.mtp §proc_probe
 * ---------------------------------------------------------------------------
 * The window-blocked probe fires.
 *
 * WHAT IT IS FOR, AND IT IS NOT WHAT THE STALL TURNED OUT TO BE. The
 * event-driven retry recovers a window whose reopening is ANNOUNCED; this
 * recovers one whose announcement is LOST. No retry can substitute for a
 * message that never arrives, and no run so far has produced that case — which
 * is exactly why it would be easy to skip now that the symptom is gone. An
 * absence that currently produces the donor's behaviour is not agreement with
 * the donor.
 */
void
proc_probe(struct timer_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms)
{
	(void)now_ms;
	if ((ctx->send_wnd > ctx->cwnd)) {
		return;
	}
	if (((now_ms - ctx->last_ack_sent_ms) <= PARITY_PROBE_MS)) {
		return;
	}
	struct TCPBP __t0 = build_hdr(ctx, (ctx->send_next - 1), FLAG_ACK, now_ms);
	uint8_t __t1[PROG_HDR_MAX];
	uint16_t __t2 = TCPBP_build(__t1, &__t0);
	mtp_pkt_gen(ctx->f, __t1, __t2, &__t0.__pay, __t0.__mss, PRIO_ACK, PROG_OFFLOAD, false);
	(ctx->probe_timer).ctx = ctx;
	mtp_timer_start(&(ctx->probe_timer), ((uint64_t)(PARITY_PROBE_MS) * 1000000ULL));
	return;
}

/*
 * mtp/tcp.mtp §proc_idle
 * ---------------------------------------------------------------------------
 * The connection has been quiet too long.
 *
 * THE DONOR TELLS THE APPLICATION WITH AN ERROR, not a clean close
 * (timer.c, CheckConnectionTimeout): state goes to CLOSED with close_reason
 * TCP_TIMEDOUT, and a stream that still has a socket gets an error event — only
 * one with no socket is destroyed silently. NO FIN IS SENT, so the peer learns
 * nothing; that is the donor's behaviour and it is why D-27 calls the mechanism
 * a workaround for its own close path rather than protocol. The lead still owes
 * a decision on whether to keep it.
 */
void
proc_idle(struct timer_ev *ev, struct tcp_ctx *ctx)
{
	ctx->state = ST_CLOSED;
	mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_ERROR });
	mtp_del_ctx(&(ctx->key));
	return;
}

/*
 * mtp/tcp.mtp §proc_bind
 * ---------------------------------------------------------------------------
 * The application names a local endpoint.
 *
 * THIS EVENT IS WHAT BRINGS A LISTEN CONTEXT INTO EXISTENCE. It exists after
 * bind and is not yet matchable: §net_parser tests for ST_LISTEN, so a SYN for
 * a bound-but-not-listening endpoint is dropped. The duplicate-endpoint check
 * is here and the donor makes it at listen; ours is here because this is where
 * the context is created.
 */
void
proc_bind(struct app_ev *ev, struct tcp_listen_ctx *ctx)
{
	if (((ctx) != NULL)) {
		return;
	}
	ctx = mtp_new_ctx(&(ev->__key), sizeof(struct tcp_listen_ctx));
	if (!ctx)
		return;
	ctx->state = ST_CLOSED;
	ctx->key = ((flowkey_t){ .kind = 1, .v0 = ev->ip, .v1 = ev->port });
	ctx->local_ip = ev->ip;
	ctx->local_port = ev->port;
	ctx->state = ST_CLOSED;
	return;
}

/*
 * mtp/tcp.mtp §proc_listen
 * ---------------------------------------------------------------------------
 * The endpoint starts answering.
 *
 * No instructions: it flips a state and sets a bound. Everything that follows
 * happens because §net_parser now finds a listen context in ST_LISTEN. The
 * analogue of the donor's ListenerHTInsert — bind created the context and
 * recorded the endpoint; this is where it becomes matchable.
 */
void
proc_listen(struct app_ev *ev, struct tcp_listen_ctx *ctx)
{
	if (!(((ctx) != NULL))) {
		return;
	}
	ctx->state = ST_LISTEN;
	ctx->pending_cap = ((ev->backlog > 0) ? ev->backlog : PROG_MAX_BACKLOG);
	if ((ctx->pending_cap > PROG_MAX_BACKLOG)) {
		ctx->pending_cap = PROG_MAX_BACKLOG;
	}
	ev->opened = ctx->key;
	return;
}

/*
 * mtp/tcp.mtp §proc_accept
 * ---------------------------------------------------------------------------
 * The application takes a pending connection.
 *
 * THE BACKLOG IS PROTOCOL STATE AND THIS IS WHAT DRAINS IT. §proc_open_done
 * adds an entry when a handshake completes; this removes one. Without it
 * `pending` would only ever grow and `pending_cap` would start refusing
 * connections the application had in fact already taken. Everything else about
 * accept — copying the peer address out, allocating a descriptor — is the
 * application interface's business; the queue it consumes is the protocol's,
 * which is why this is an event rather than a convenience in a shim.
 */
void
proc_accept(struct app_ev *ev, struct tcp_listen_ctx *ctx)
{
	uint32_t i;
	if ((!(((ctx) != NULL)) || (ctx->state != ST_LISTEN))) {
		ev->result = -(1);
		return;
	}
	if ((ctx->pending_n == 0)) {
		ev->result = -(1);
		return;
	}
	ev->accepted = ctx->pending[0];
	for (i = 1; (i < ctx->pending_n); i = (i + 1)) {
		ctx->pending[(i - 1)] = ctx->pending[i];
	}
	ctx->pending_n = (ctx->pending_n - 1);
	if ((ctx->pending_n > 0)) {
		mtp_notify(ctx->f, &(struct mtp_notif){ .kind = MTP_NOTIF_READABLE });
	}
	return;
}

/*
 * mtp/tcp.mtp §proc_connect
 * ---------------------------------------------------------------------------
 * The application opens a connection.
 *
 * It fills in the endpoints the target cannot know — there is no arriving
 * packet to take them from — and asks for the SYN. cwnd is NOT set to the
 * initial window here: the donor sets cwnd = 1 at connect and turns that into
 * mss * TCP_INIT_CWND when the SYN-ACK arrives, so the initial window is a
 * property of the handshake completing rather than of asking. `cwnd = 1` means
 * "not yet opened", not one byte.
 */
void
proc_connect(struct app_ev *ev, struct tcp_ctx *ctx)
{
	if (((ctx) != NULL)) {
		return;
	}
	ctx = mtp_new_ctx(&(ev->__key), sizeof(struct tcp_ctx));
	if (!ctx)
		return;
	ctx->state = ST_CLOSED;
	ctx->send_wnd = 65535;
	ctx->cwnd = PARITY_INIT_CWND;
	ctx->rcv_wnd = PARITY_INITIAL_WINDOW;
	ctx->key = ev->__key;
	ctx->local_ip = ev->loc_ip;
	ctx->remote_ip = ev->rem_ip;
	ctx->loc_port = ev->loc_port;
	ctx->rem_port = ev->rem_port;
	ctx->rcv_wnd = PARITY_INITIAL_WINDOW;
	ctx->snd_base = PARITY_ISN;
	ctx->send_una = PARITY_ISN;
	ctx->send_next = PARITY_ISN;
	ctx->cwnd = 1;
	ctx->ssthresh = PARITY_SSTHRESH_ACTIVE;
	ctx->state = ST_SYN_SENT;
	mtp_ctx_addrs(ctx->f, ctx->local_ip, ctx->remote_ip);
	if (((ctx->state != ST_CLOSED) && (ctx->state != ST_TIME_WAIT))) {
		(ctx->idle_timer).ctx = ctx;
		mtp_timer_start(&(ctx->idle_timer), ((uint64_t)(tcp_timeout) * 1000000000ULL));
	}
	ev->opened = ctx->key;
	return;
}

/*
 * mtp/tcp.mtp §post_object
 * ---------------------------------------------------------------------------
 * A send with no flow: the object a one-shot server posts before any connection
 * exists, so that every accepted connection receives it. It is posted to a
 * LISTENER, not to the process — with several listeners there is no "the"
 * listener to post to, which is why the op carries the endpoint. §proc_open_done
 * is what serves it.
 */
void
post_object(struct app_ev *ev, struct tcp_listen_ctx *ctx)
{
	if (!(((ctx) != NULL))) {
		return;
	}
	ctx->obj = ev->addr;
	ctx->obj_len = ev->mlen;
	return;
}

/* generated from: tcp_syn -> { proc_passive_open } */
bool
dispatch_tcp_syn(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	proc_passive_open(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_synack -> { proc_synack } */
bool
dispatch_tcp_synack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	proc_synack(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_ack -> { proc_timestamp, proc_open_done, proc_window, proc_rtt, proc_fast_retransmit, proc_congestion, proc_ack, gen_seg, gen_fin } */
bool
dispatch_tcp_ack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_timestamp(ev, ctx);
	proc_open_done(ev, ctx, now_ms);
	proc_window(ev, ctx);
	proc_rtt(ev, ctx, now_ms);
	proc_fast_retransmit(ev, ctx, &sc);
	proc_congestion(ev, ctx);
	proc_ack(ev, ctx, &sc);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	gen_seg(ctx, &sc, now_ms);
	gen_fin(ctx, now_ms);
	return true;
}

/* generated from: tcp_data -> { proc_recv, send_ack } */
bool
dispatch_tcp_data(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_recv(ev, ctx, &sc);
	send_ack(ctx, &sc);
	return true;
}

/* generated from: tcp_fin -> { proc_fin, send_ack } */
bool
dispatch_tcp_fin(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_fin(ev, ctx, &sc);
	send_ack(ctx, &sc);
	return true;
}

/* generated from: tcp_rst -> { proc_rst } */
bool
dispatch_tcp_rst(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_rst(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: tcp_rto_timeout -> { proc_rto } */
bool
dispatch_tcp_rto_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_rto(ev, ctx, &sc, now_ms);
	return true;
}

/* generated from: tcp_timewait_timeout -> { proc_timewait_done } */
bool
dispatch_tcp_timewait_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_timewait_done(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: tcp_probe_timeout -> { proc_probe } */
bool
dispatch_tcp_probe_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	proc_probe(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_idle_timeout -> { proc_idle } */
bool
dispatch_tcp_idle_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_idle(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: app_bind -> { proc_bind } */
bool
dispatch_app_bind(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_bind(ev, ctx);
	if (!ctx)
		ctx = mtp_ctx_lookup(&ev->__key);
	return true;
}

/* generated from: app_listen -> { proc_listen } */
bool
dispatch_app_listen(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_listen(ev, ctx);
	return true;
}

/* generated from: app_accept -> { proc_accept } */
bool
dispatch_app_accept(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_accept(ev, ctx);
	return true;
}

/* generated from: app_connect -> { proc_connect, gen_syn } */
bool
dispatch_app_connect(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_connect(ev, ctx);
	if (!ctx)
		ctx = mtp_ctx_lookup(&ev->__key);
	gen_syn(ctx, now_ms);
	return true;
}

/* generated from: app_recv -> { proc_drain } */
bool
dispatch_app_recv(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_drain(ev, ctx, &sc);
	return true;
}

/* generated from: app_send -> { record_data, post_object } */
bool
dispatch_app_send(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	record_data(ev, ctx);
	{
		struct tcp_listen_ctx *ctx2 = ev->__flow ? NULL
					     : mtp_ctx_lookup(&ev->__key);
		if (ctx2)
			post_object(ev, ctx2);
	}
	return true;
}

/* generated from: app_gen -> { gen_syn, gen_seg, drain_owed_acks, gen_wnd_adv, gen_answer } */
bool
dispatch_app_gen(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	gen_syn(ctx, now_ms);
	gen_seg(ctx, &sc, now_ms);
	drain_owed_acks(ctx, &sc, now_ms);
	gen_wnd_adv(ctx, now_ms);
	gen_answer(ev, ctx);
	return true;
}

/* generated from: app_close -> { mark_closed, gen_fin } */
bool
dispatch_app_close(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	mark_closed(ev, ctx);
	gen_fin(ctx, now_ms);
	return true;
}

int
mtp_program_net_input(const uint8_t *l4, uint16_t len,
		const struct iphdr *iph, uint32_t now_ms)
{
	uint8_t  kinds[EV_KIND__N];
	struct net_ev ev;
	void    *cv = NULL;
	unsigned n, i;

	n = parse_tcp(l4, len, iph, &ev, kinds, &cv, now_ms);
	if (!cv)
		return 0;	/* the parser answered it, or refused it */

	for (i = 0; i < n; i++) {
		bool alive = true;

		switch (kinds[i]) {
		case EV_tcp_ack:
			alive = dispatch_tcp_ack((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		case EV_tcp_data:
			alive = dispatch_tcp_data((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		case EV_tcp_fin:
			alive = dispatch_tcp_fin((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		case EV_tcp_rst:
			alive = dispatch_tcp_rst((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		case EV_tcp_syn:
			alive = dispatch_tcp_syn((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		case EV_tcp_synack:
			alive = dispatch_tcp_synack((struct tcp_ctx *)cv, &ev, now_ms);
			break;
		default: break;
		}
		if (!alive)
			return 0;	/* the context is gone */
	}
	return 0;
}

/*
 * The timer side. Each declared timer was bound to the event its expiry
 * raises, so "which timer fired" is answered by the binding rather than by
 * the program comparing addresses at run time.
 */
void
mtp_program_timer(struct mtp_timer *t, uint32_t now_ms)
{
	struct tcp_ctx *ctx = t->ctx;
	struct timer_ev ev;

	memset(&ev, 0, sizeof(ev));
	if (!ctx)
		return;
	if (t == &ctx->rto_timer) {
		dispatch_tcp_rto_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->tw_timer) {
		dispatch_tcp_timewait_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->probe_timer) {
		dispatch_tcp_probe_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->idle_timer) {
		dispatch_tcp_idle_timeout(ctx, &ev, now_ms);
		return;
	}
}

void
mtp_program_segment(const struct mtp_seg_view *v)
{
	uint32_t seq;

	if (!v->prev_hdr)
		return;		/* segment 0 keeps what the program built */
	memcpy(&seq, (const uint8_t *)v->prev_hdr + TCPBP_seq_no_OFF, 4);
	seq = htonl(ntohl(seq) + v->prev_paylen);
	memcpy((uint8_t *)v->hdr + TCPBP_seq_no_OFF, &seq, 4);
}

void
mtp_program_coalesce(const uint8_t *hdr, uint16_t hdr_len,
		uint8_t *class, uint32_t *key, bool *inherit_base,
		uint16_t *keep_off, uint16_t *keep_len)
{
	struct TCPBP b;

	(void)hdr_len;
	TCPBP_extract(&b, hdr, TCPBP_FIXED_LEN);
	/* the fields that travel with the payload origin rather than with
	 * the newer header */
	*keep_off = TCPBP_seq_no_OFF;
	*keep_len = 4;
	/* anything consuming sequence space stands alone */
	if ((((b.flags & (((FLAG_SYN | FLAG_FIN) | FLAG_RST)))) != 0)) {
		*class = 0;
		return;
	}
	*class = 1;
	*key = b.flags;
	*inherit_base = true;
}
