/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog.h"

/* generated from: tcp_syn -> { proc_passive_open } */
bool
dispatch_tcp_syn(struct tcp_listen_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	proc_passive_open(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_synack -> { proc_synack } */
bool
dispatch_tcp_synack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	proc_synack(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_ack -> { proc_seq_check, proc_timestamp, proc_accept_queue, proc_open_done, proc_window, proc_rtt, proc_fast_retransmit, proc_congestion, proc_ack, gen_seg, gen_fin } */
bool
dispatch_tcp_ack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	if (ctx)
		proc_seq_check(ev, ctx);
	if (ctx)
		proc_timestamp(ev, ctx);
	{
		struct tcp_listen_ctx *ctx2 = ev->__have_tcp_listen_ctx
			? mtp_ctx_lookup(&ev->__key_tcp_listen_ctx) : NULL;
		if (ctx2)
			proc_accept_queue(ev, ctx, ctx2);
	}
	if (ctx)
		proc_open_done(ev, ctx);
	if (ctx)
		proc_window(ev, ctx);
	if (ctx)
		proc_rtt(ev, ctx, now_ms);
	if (ctx)
		proc_fast_retransmit(ev, ctx, &sc);
	if (ctx)
		proc_congestion(ev, ctx);
	if (ctx)
		proc_ack(ev, ctx, &sc);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	if (ctx)
		gen_seg(ctx, &sc, now_ms);
	if (ctx)
		gen_fin(ctx, now_ms);
	return true;
}

/* generated from: tcp_data -> { proc_recv, send_ack } */
bool
dispatch_tcp_data(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_recv(ev, ctx, &sc);
	send_ack(ctx, &sc);
	return true;
}

/* generated from: tcp_fin -> { proc_fin, send_ack } */
bool
dispatch_tcp_fin(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_fin(ev, ctx, &sc);
	send_ack(ctx, &sc);
	return true;
}

/* generated from: tcp_rst -> { proc_rst } */
bool
dispatch_tcp_rst(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_rst(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: tcp_rto_timeout -> { proc_rto } */
bool
dispatch_tcp_rto_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_rto(ev, ctx, &sc, now_ms);
	return true;
}

/* generated from: tcp_timewait_timeout -> { proc_timewait_done } */
bool
dispatch_tcp_timewait_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_timewait_done(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: tcp_probe_timeout -> { proc_probe } */
bool
dispatch_tcp_probe_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	proc_probe(ev, ctx, now_ms);
	return true;
}

/* generated from: tcp_idle_timeout -> { proc_idle } */
bool
dispatch_tcp_idle_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_idle(ev, ctx);
	if (sc.__ctx_dead)
		return false;	/* del_ctx ran: the context is gone */
	return true;
}

/* generated from: app_bind -> { proc_bind } */
bool
dispatch_app_bind_record(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_bind(ev, ctx);
	if (!ctx)
		ctx = mtp_ctx_lookup(&ev->__key_tcp_listen_ctx);
	return true;
}

/* generated from: app_listen -> { proc_listen } */
bool
dispatch_app_listen_record(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_listen(ev, ctx);
	return true;
}

/* generated from: app_accept -> { proc_accept } */
bool
dispatch_app_accept_record(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_accept(ev, ctx);
	return true;
}

/* generated from: app_connect -> { proc_connect, gen_syn } */
bool
dispatch_app_connect_record(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	proc_connect(ev, ctx);
	if (!ctx)
		ctx = mtp_ctx_lookup(&ev->__key_tcp_ctx);
	return true;
}

bool
dispatch_app_connect_generate(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	gen_syn(ctx, now_ms);
	return true;
}

/* generated from: app_recv -> { proc_drain } */
bool
dispatch_app_recv_record(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	proc_drain(ev, ctx, &sc);
	return true;
}

/* generated from: app_send -> { record_data, gen_syn, gen_seg, drain_owed_acks, gen_wnd_adv } */
bool
dispatch_app_send_record(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	record_data(ev, ctx);
	return true;
}

bool
dispatch_app_send_generate(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	struct tcp_scratch sc = { 0 };

	gen_syn(ctx, now_ms);
	gen_seg(ctx, &sc, now_ms);
	drain_owed_acks(ctx, &sc, now_ms);
	gen_wnd_adv(ctx, now_ms);
	return true;
}

/* generated from: app_close -> { mark_closed, gen_fin } */
bool
dispatch_app_close_record(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	mark_closed(ev, ctx);
	return true;
}

bool
dispatch_app_close_generate(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms)
{
	gen_fin(ctx, now_ms);
	return true;
}

int
mtp_program_net_input(const uint8_t *l4, uint16_t len,
		const struct iphdr *iph, uint32_t now_ms)
{
	uint8_t  kinds[EV_KIND__N];
	struct net_ev ev;
	unsigned n, i;

	n = parse_tcp(l4, len, iph, &ev, kinds, now_ms);

	for (i = 0; i < n; i++) {
		bool alive = true;

		switch (kinds[i]) {
		case EV_tcp_ack: {
			struct tcp_ctx *c = ev.__have_tcp_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_ctx) : NULL;
			alive = dispatch_tcp_ack(c, &ev, now_ms);
			break;
		}
		case EV_tcp_data: {
			struct tcp_ctx *c = ev.__have_tcp_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_ctx) : NULL;
			if (!c)
				break;	/* look-up miss: TODO, an error event the program handles */
			alive = dispatch_tcp_data(c, &ev, now_ms);
			break;
		}
		case EV_tcp_fin: {
			struct tcp_ctx *c = ev.__have_tcp_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_ctx) : NULL;
			if (!c)
				break;	/* look-up miss: TODO, an error event the program handles */
			alive = dispatch_tcp_fin(c, &ev, now_ms);
			break;
		}
		case EV_tcp_rst: {
			struct tcp_ctx *c = ev.__have_tcp_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_ctx) : NULL;
			if (!c)
				break;	/* look-up miss: TODO, an error event the program handles */
			alive = dispatch_tcp_rst(c, &ev, now_ms);
			break;
		}
		case EV_tcp_syn: {
			struct tcp_listen_ctx *c = ev.__have_tcp_listen_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_listen_ctx) : NULL;
			if (!c)
				break;	/* look-up miss: TODO, an error event the program handles */
			alive = dispatch_tcp_syn(c, &ev, now_ms);
			break;
		}
		case EV_tcp_synack: {
			struct tcp_ctx *c = ev.__have_tcp_ctx
				? mtp_ctx_lookup(&ev.__key_tcp_ctx) : NULL;
			if (!c)
				break;	/* look-up miss: TODO, an error event the program handles */
			alive = dispatch_tcp_synack(c, &ev, now_ms);
			break;
		}
		default: break;
		}
		if (!alive)
			return 0;	/* the context is gone */
	}
	return 0;
}

void
mtp_program_generate(flow_t *f, uint32_t now_ms)
{
	struct tcp_ctx *ctx = mtp_ctx_of(f);
	struct app_ev ev;

	if (!ctx)
		return;
	memset(&ev, 0, sizeof(ev));
	dispatch_app_send_generate(ctx, &ev, now_ms);
}

/*
 * The timer side. Each declared timer was bound to the event its expiry
 * raises, so "which timer fired" is answered by the binding rather than by
 * the program comparing addresses at run time.
 */
void
mtp_program_timer(struct mtp_timer *t, uint32_t now_ms)
{
	struct tcp_ctx *ctx = t->ctx;
	struct timer_ev ev;

	memset(&ev, 0, sizeof(ev));
	if (!ctx)
		return;
	if (t == &ctx->rto_timer) {
		dispatch_tcp_rto_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->tw_timer) {
		dispatch_tcp_timewait_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->probe_timer) {
		dispatch_tcp_probe_timeout(ctx, &ev, now_ms);
		return;
	}
	if (t == &ctx->idle_timer) {
		dispatch_tcp_idle_timeout(ctx, &ev, now_ms);
		return;
	}
}

void
mtp_program_segment(const struct mtp_seg_view *v)
{
	uint32_t seq;

	if (!v->prev_hdr)
		return;		/* segment 0 keeps what the program built */
	memcpy(&seq, (const uint8_t *)v->prev_hdr + TCPBP_seq_no_OFF, 4);
	seq = htonl(ntohl(seq) + v->prev_paylen);
	memcpy((uint8_t *)v->hdr + TCPBP_seq_no_OFF, &seq, 4);
}

void
mtp_program_coalesce(const uint8_t *hdr, uint16_t hdr_len,
		uint8_t *class, uint32_t *key, bool *inherit_base,
		uint16_t *keep_off, uint16_t *keep_len)
{
	struct TCPBP b;

	(void)hdr_len;
	TCPBP_extract(&b, hdr, TCPBP_FIXED_LEN);
	/* the fields that travel with the payload origin rather than with
	 * the newer header */
	*keep_off = TCPBP_seq_no_OFF;
	*keep_len = 4;
	/* anything consuming sequence space stands alone */
	if ((((b.flags & (((FLAG_SYN | FLAG_FIN) | FLAG_RST)))) != 0)) {
		*class = 0;
		return;
	}
	*class = 1;
	*key = b.flags;
	*inherit_base = true;
}
