/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#ifndef PROG_PARAMS_H
#define PROG_PARAMS_H
/*
 * Compiler output: this program's compile-time constants.
 *
 * Rule 4 permits protocol identity HERE and nowhere else. Rebuilding the
 * tree for another protocol is expected; what is forbidden is the target
 * or the infrastructure knowing which protocol it was built for.
 */
#include <stdint.h>

#include "prog_types.h"

#define FLAG_FIN	(1)
#define FLAG_SYN	(2)
#define FLAG_RST	(4)
#define FLAG_PSH	(8)
#define FLAG_ACK	(16)
#define ST_CLOSED	(0)
#define ST_LISTEN	(1)
#define ST_SYN_RCVD	(2)
#define ST_ESTABLISHED	(3)
#define ST_CLOSE_WAIT	(4)
#define ST_LAST_ACK	(5)
#define ST_FIN_WAIT_1	(6)
#define ST_FIN_WAIT_2	(7)
#define ST_CLOSING	(8)
#define ST_TIME_WAIT	(9)
#define ST_SYN_SENT	(10)
#define PARITY_MSS_ADVERTISED	(1460)
#define PARITY_MSS_PAYLOAD	(1448)
#define PARITY_WSCALE	(7)
#define PARITY_RCVBUF_SIZE	(262144)
#define PARITY_INITIAL_WINDOW	(14600)
#define PARITY_ISN	(0)
#define PARITY_INIT_CWND	(2920)
#define PARITY_SSTHRESH_ACTIVE	(14600)
#define PARITY_OPENING_TRAJECTORY	(true)
#define PARITY_SSTHRESH_PASSIVE	(0)
#define PARITY_DUP_ACK_THRESH	(3)
#define PARITY_MAX_RTX	(16)
#define PARITY_MAX_SYN_RETRY	(7)
#define PARITY_INITIAL_RTO_MS	(500)
#define PARITY_PROBE_MS	(500)
#define PROG_MAX_BACKLOG	(128)
#define PARITY_SET_PSH	(false)
#define PRIO_CONTROL	(2)
#define PRIO_ACK	(1)
#define PRIO_DATA	(0)
#define ACK_NONE	(0)
#define ACK_AGGREGATE	(1)
#define ACK_APIECE	(2)
#define TRANSPORT_IP_PROTO	(6)

/* Largest serialised header image a blueprint carries: the fixed header
 * plus the option bytes the program can construct. */
#define PROG_OPT_MAX	40
#define PROG_HDR_MAX	64

/* Where the transport checksum sits within this program's header. The
 * target asks the NIC to compute it and needs the offset; it never learns
 * what is being summed. */
#define PROG_L4_CSUM_OFFSET	16
#define PROG_OFFLOAD		1

/* Parameters (param). Set from configuration; see ProgConfigKey. */
extern uint32_t tcp_timewait;
extern uint32_t tcp_timeout;

#endif /* PROG_PARAMS_H */
