/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog.h"

/*
 * mtp/tcp.mtp §net_parser
 * ---------------------------------------------------------------------------
 * parse_tcp : a segment -> the list of events it raises.
 *
 * INCLUSIVE, which is the donor's shape: Handle_TCP_ST_ESTABLISHED runs three
 * independent tests on one packet, so a segment carrying payload, an
 * acknowledgement and a FIN does all three jobs. One event per segment would
 * drop the payload of a data-carrying FIN.
 *
 *   RST                   -> tcp_rst        (alone -- the donor returns from
 *                                            ProcessTCPPacket, delivering no
 *                                            payload and retiring no ack)
 *   SYN, no ACK           -> tcp_syn        (alone: nothing else in sequence)
 *   SYN + ACK             -> tcp_synack     (alone, likewise)
 *   ACK                   -> tcp_ack
 *   payload               -> tcp_data
 *   FIN                   -> tcp_fin
 *
 * The last three compose, in the order acknowledgement, payload, FIN.
 * proc_congestion is in the tcp_ack chain and reads `ack - send_una`, so
 * retiring the bytes first would leave the congestion window seeing nothing
 * newly acknowledged.
 *
 * THE PARSER ISSUES INSTRUCTIONS AND RESOLVES CONTEXTS, which the frozen
 * language does not say it may (docs/LANGUAGE-NEEDS.md N-E). It has to --
 * three jobs here are protocol policy and none can be done from a chain:
 *
 *   a segment for a connection that does not exist is answered with a RESET,
 *   and a chain is dispatched THROUGH a context;
 *
 *   a SYN is matched against a LISTENER, and backlog room decides whether a
 *   context is created at all (G8, C3);
 *
 *   validation refuses a segment BEFORE any event is raised, which is the
 *   donor's placement. As the first link of every chain instead, a segment
 *   raising two events would validate twice and owe a duplicate
 *   acknowledgement the donor does not send.
 */
unsigned
parse_tcp(const uint8_t *l4, uint16_t plen,
		const struct iphdr *iph, struct net_ev *ev, uint8_t *kinds,
		void **ctx_out, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	struct TCPBP bp;
	if (TCPBP_extract(&bp, l4, plen) < 0)
		return 0;
	uint32_t payload_len;
	if ((((plen < 20) || ((bp.data_off * 4) < 20)) || ((bp.data_off * 4) > plen))) {
		return __n;
	}
	payload_len = (plen - (bp.data_off * 4));
	flowkey_t fid = ((flowkey_t){ .kind = 0, .v0 = iph->daddr, .v1 = iph->saddr, .v2 = bp.dst_port, .v3 = bp.src_port });
	struct tcp_ctx *ctx = mtp_ctx_lookup(&(fid));
	if (!(((ctx) != NULL))) {
		bool refuse = ((((bp.flags & FLAG_SYN)) == 0) || (((bp.flags & FLAG_ACK)) != 0));
		flowkey_t lk = ((flowkey_t){ .kind = 1, .v0 = iph->daddr, .v1 = bp.dst_port });
		struct tcp_listen_ctx *lst = mtp_ctx_lookup(&(lk));
		if ((!(refuse) && ((!(((lst) != NULL)) || (lst->state != ST_LISTEN))))) {
			refuse = true;
		}
		if (refuse) {
			if ((((bp.flags & FLAG_RST)) != 0)) {
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			if ((((bp.flags & FLAG_ACK)) != 0)) {
				struct TCPBP __t0 = build_rst_hdr(bp.dst_port, bp.src_port, bp.ack_seq, 0, FLAG_RST);
				uint8_t __t1[PROG_HDR_MAX];
				uint16_t __t2 = TCPBP_build(__t1, &__t0);
				mtp_pkt_gen_orphan(iph->daddr, iph->saddr, __t1, __t2, PROG_OFFLOAD);
			} else {
				struct TCPBP __t3 = build_rst_hdr(bp.dst_port, bp.src_port, 0, ((bp.seq_no + payload_len) + (((((bp.flags & FLAG_SYN)) != 0) ? 1 : 0))), (FLAG_RST | FLAG_ACK));
				uint8_t __t4[PROG_HDR_MAX];
				uint16_t __t5 = TCPBP_build(__t4, &__t3);
				mtp_pkt_gen_orphan(iph->daddr, iph->saddr, __t4, __t5, PROG_OFFLOAD);
			}
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		if ((lst->pending_n >= lst->pending_cap)) {
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		ctx = mtp_new_ctx(&(fid), sizeof(struct tcp_ctx));
		if (!ctx)
			return __n;
		ctx->state = ST_CLOSED;
		ctx->send_wnd = 65535;
		ctx->cwnd = PARITY_INIT_CWND;
		ctx->rcv_wnd = PARITY_INITIAL_WINDOW;
		ctx->key = fid;
		ctx->lst_key = lk;
		ctx->loc_port = bp.dst_port;
		ctx->rem_port = bp.src_port;
		ctx->local_ip = iph->daddr;
		ctx->remote_ip = iph->saddr;
		ev->seq = bp.seq_no;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->has_ts = bp.__opt_ts_present;
		ev->wscale = bp.__opt_wscale_wscale;
		ev->has_wscale = bp.__opt_wscale_present;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_syn;
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if (((ctx->state != ST_CLOSED) && (ctx->state != ST_TIME_WAIT))) {
		(ctx->idle_timer).ctx = ctx;
		mtp_timer_start(&(ctx->idle_timer), ((uint64_t)(tcp_timeout) * 1000000000ULL));
	}
	bool accept = false;
	uint32_t seg_end;
	if (((((ctx->state == ST_CLOSED) || (ctx->state == ST_LISTEN)) || (ctx->state == ST_SYN_RCVD)) || (ctx->state == ST_SYN_SENT))) {
		accept = true;
	} else {
		if (((((bp.flags & FLAG_RST)) == 0) && ctx->saw_timestamp)) {
			if (!(bp.__opt_ts_present)) {
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			if (((int32_t)((bp.__opt_ts_ts_val - ctx->ts_recent)) < 0)) {
				ctx->ack_cnt = (ctx->ack_cnt + 1);
				mtp_retry(ctx->f);
				if (ctx_out)
					*ctx_out = ctx;
				return __n;
			}
			ctx->ts_recent = bp.__opt_ts_ts_val;
		}
		seg_end = (bp.seq_no + payload_len);
		if ((((int32_t)((seg_end - ctx->recv_next)) >= 0) && ((int32_t)((seg_end - ((ctx->recv_next + ctx->rcv_wnd)))) <= 0))) {
			accept = true;
		}
	}
	if (!(accept)) {
		if ((((bp.flags & FLAG_RST)) != 0)) {
			if (ctx_out)
				*ctx_out = ctx;
			return __n;
		}
		if ((ctx->state == ST_ESTABLISHED)) {
			if ((((bp.seq_no + 1) == ctx->recv_next) || ((int32_t)((bp.seq_no - ctx->recv_next)) <= 0))) {
				if ((ctx->ack_cnt == 0)) {
					ctx->ack_cnt = 1;
				}
				mtp_retry(ctx->f);
			} else {
				ctx->ack_cnt = (ctx->ack_cnt + 1);
				mtp_retry(ctx->f);
			}
		} else {
			if ((ctx->state == ST_TIME_WAIT)) {
				ctx->state = ST_TIME_WAIT;
				(ctx->tw_timer).ctx = ctx;
				mtp_timer_start(&(ctx->tw_timer), ((uint64_t)(tcp_timewait) * 1000000000ULL));
			}
			ctx->ack_cnt = (ctx->ack_cnt + 1);
			mtp_retry(ctx->f);
		}
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_RST)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_rst;
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_SYN)) != 0)) {
		if ((((bp.flags & FLAG_ACK)) != 0)) {
			ev->seq = bp.seq_no;
			ev->ack = bp.ack_seq;
			ev->window = bp.window;
			ev->ts_val = bp.__opt_ts_ts_val;
			ev->ts_ecr = bp.__opt_ts_ts_ecr;
			ev->has_ts = bp.__opt_ts_present;
			ev->wscale = bp.__opt_wscale_wscale;
			ev->has_wscale = bp.__opt_wscale_present;
			ev->__key = fid;
			kinds[__n++] = EV_tcp_synack;
		}
		if (ctx_out)
			*ctx_out = ctx;
		return __n;
	}
	if ((((bp.flags & FLAG_ACK)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->ts_ecr = bp.__opt_ts_ts_ecr;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_ack;
	}
	if ((payload_len > 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->hold_addr = (struct mtp_rx_addr){ .data = l4 + bp.data_off * 4, .len = (uint32_t)(plen - bp.data_off * 4) };
		ev->data_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_data;
	}
	if ((((bp.flags & FLAG_FIN)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->payload_len = payload_len;
		ev->__key = fid;
		kinds[__n++] = EV_tcp_fin;
	}
	if (ctx_out)
		*ctx_out = ctx;
	return __n;
}

