/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#ifndef PROG_BLUEPRINT_H
#define PROG_BLUEPRINT_H
/*
 * pkt_bp -- the packet this program builds and parses, its field
 * offsets, and the serialiser and extractor over it.
 *
 * The helpers are NOT static: the parser and the processors both call
 * them, and they are in different translation units now.
 */
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog_const.h"
#include "prog_flow_id.h"
#include "prog_event.h"

/*
 * The packet blueprint, from `pkt_bp TCPBP`.
 *
 * `hdrlen4_t` and `checksum16_t` are NOT fields: the first is filled by the
 * serialiser from the layout, the second is an offload request. A program
 * that computed either would be doing arithmetic over the compiler's own
 * layout.
 */
struct TCPBP {
	uint16_t src_port;
	uint16_t dst_port;
	uint32_t seq_no;
	uint32_t ack_seq;
	uint8_t data_off;
	uint8_t flags;
	uint16_t window;
	uint16_t urg_ptr;
	/* the option list, serialised IN THE ORDER THE PROGRAM CONSTRUCTS IT --
	 * the order is the parity item, so it is bytes and not a table a
	 * serialiser could reorder */
	uint8_t  __opt[PROG_OPT_MAX];
	uint16_t __opt_len;
	/* what the extractor found, so `absent` and `present and zero` are
	 * different -- PAWS turns on exactly that difference */
	bool     __opt_mss_present;
	uint16_t __opt_mss_mss;
	bool     __opt_nop_present;
	bool     __opt_ts_present;
	uint32_t __opt_ts_ts_val;
	uint32_t __opt_ts_ts_ecr;
	bool     __opt_wscale_present;
	uint8_t __opt_wscale_wscale;
	struct mtp_tx_payload __pay;
	uint32_t __mss;
};


/* field offsets within the serialised header */
#define TCPBP_src_port_OFF	0
#define TCPBP_dst_port_OFF	2
#define TCPBP_seq_no_OFF	4
#define TCPBP_ack_seq_OFF	8
#define TCPBP_data_off_OFF	12
#define TCPBP_flags_OFF	13
#define TCPBP_window_OFF	14
#define TCPBP_checksum_OFF	16
#define TCPBP_urg_ptr_OFF	18
#define TCPBP_FIXED_LEN	20

/* the serialiser and extractor; the parser and the processors both call them */
uint16_t TCPBP_build(uint8_t *out, const struct TCPBP *b);
int TCPBP_extract(struct TCPBP *b, const uint8_t *in, uint16_t len);
void TCPBP_add_opt_mss(struct TCPBP *b, uint16_t mss);
void TCPBP_add_opt_nop(struct TCPBP *b);
void TCPBP_add_opt_ts(struct TCPBP *b, uint32_t ts_val, uint32_t ts_ecr);
void TCPBP_add_opt_wscale(struct TCPBP *b, uint8_t wscale);

#endif /* PROG_BLUEPRINT_H */
