/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#ifndef PROG_EVENT_H
#define PROG_EVENT_H
/*
 * event -- one frame per BASE type, not per event. One packet
 * raises several events and they are projections of ONE parse, so the
 * events of a base type share a frame and the event itself is a tag.
 */
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog_const.h"
#include "prog_flow_id.h"

/* which event a frame is carrying */
enum ev_kind {
	EV_app_accept,
	EV_app_bind,
	EV_app_close,
	EV_app_connect,
	EV_app_gen,
	EV_app_listen,
	EV_app_recv,
	EV_app_send,
	EV_tcp_ack,
	EV_tcp_data,
	EV_tcp_fin,
	EV_tcp_idle_timeout,
	EV_tcp_probe_timeout,
	EV_tcp_rst,
	EV_tcp_rto_timeout,
	EV_tcp_seg,
	EV_tcp_syn,
	EV_tcp_synack,
	EV_tcp_timewait_timeout,
	EV_KIND__N
};

/* every app_event of this program, as one frame */
struct app_ev {
	flowkey_t accepted;
	struct mtp_addr addr;
	uint32_t backlog;
	struct mtp_addr buf;
	uint32_t ip;
	uint32_t len;
	uint32_t loc_ip;
	uint16_t loc_port;
	uint32_t mlen;
	flowkey_t opened;
	uint16_t port;
	uint32_t rem_ip;
	uint16_t rem_port;
	int32_t result;
	flowkey_t __key_tcp_ctx;
	bool      __have_tcp_ctx;
	flowkey_t __key_tcp_listen_ctx;
	bool      __have_tcp_listen_ctx;
};

/* every net_event of this program, as one frame */
struct net_ev {
	uint32_t ack;
	uint32_t data_len;
	uint16_t dport;
	uint16_t flags;
	bool has_ts;
	bool has_wscale;
	struct mtp_addr hold_addr;
	uint32_t local_ip;
	uint32_t payload_len;
	uint32_t remote_ip;
	uint32_t seq;
	uint16_t sport;
	uint32_t ts_ecr;
	uint32_t ts_val;
	uint16_t window;
	uint8_t wscale;
	flowkey_t __key_tcp_ctx;
	bool      __have_tcp_ctx;
	flowkey_t __key_tcp_listen_ctx;
	bool      __have_tcp_listen_ctx;
};

/* every timer_event of this program, as one frame */
struct timer_ev {
	flowkey_t __key_tcp_ctx;
	bool      __have_tcp_ctx;
	flowkey_t __key_tcp_listen_ctx;
	bool      __have_tcp_listen_ctx;
};


#endif /* PROG_EVENT_H */
