/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
/*
 * The two things the infrastructure needs from the program: which IP
 * protocol number the transport answers to, and what to do with a
 * configuration key the infrastructure did not recognise.
 *
 * Both are here rather than in src/target/ because they are the only two
 * places below the transport where protocol identity would otherwise have to
 * be written down, and rule 4 says it may only be written down in
 * src/program/.
 */
#include <stdlib.h>
#include <string.h>

#include "upcall.h"
#include "contract.h"
#include "prog_params.h"

/* Named as a NUMBER, not as a symbol, because ip_in.c compares against it
 * and ip_in.c is infrastructure. */
#undef TRANSPORT_IP_PROTO
const uint8_t TRANSPORT_IP_PROTO = 6;

/*
 * The parameters this protocol declares. An unrecognised key must not be
 * silently ignored: the configuration file the donor is measured with is the
 * configuration file this target is measured with.
 */
uint32_t tcp_timewait = 0;
uint32_t tcp_timeout = 30;

int
ProgConfigKey(const char *key, const char *value)
{
	if (strcmp(key, "tcp_timewait") == 0) {
		tcp_timewait = (uint32_t)atoi(value);
		return 1;
	}
	if (strcmp(key, "tcp_timeout") == 0) {
		tcp_timeout = (uint32_t)atoi(value);
		return 1;
	}
	return 0;
}
