/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog.h"

/*
 * mtp/tcp.mtp §net_parser
 * ---------------------------------------------------------------------------
 * parse_tcp : a segment -> the list of events it raises.
 *
 * INCLUSIVE, which is the donor's shape: Handle_TCP_ST_ESTABLISHED runs three
 * independent tests on one packet, so a segment carrying payload, an
 * acknowledgement and a FIN does all three jobs. One event per segment would
 * drop the payload of a data-carrying FIN.
 *
 *   RST                   -> tcp_rst        (alone -- the donor returns from
 *                                            ProcessTCPPacket, delivering no
 *                                            payload and retiring no ack)
 *   SYN, no ACK           -> tcp_syn        (alone: nothing else in sequence)
 *   SYN + ACK             -> tcp_synack     (alone, likewise)
 *   ACK                   -> tcp_ack
 *   payload               -> tcp_data
 *   FIN                   -> tcp_fin
 *
 * The last three compose, in the order acknowledgement, payload, FIN.
 * proc_congestion is in the tcp_ack chain and reads `ack - send_una`, so
 * retiring the bytes first would leave the congestion window seeing nothing
 * newly acknowledged.
 *
 * THE PARSER EXTRACTS LOOK-UP KEYS AND EVENT METADATA, AND NOTHING ELSE (D-33).
 * It resolves no context, so it decides nothing that needs one:
 *
 *   a segment for a connection that does not exist is a look-up MISS, reported
 *   by the target, not a reset built here;
 *
 *   a SYN keys the LISTENER, and the backlog test and the context it creates
 *   are §proc_passive_open's, which is where allocation belongs;
 *
 *   validation reads the context, so it is §proc_seq_check on the tcp_seg
 *   chain -- raised first and once, which is what keeps a segment that raises
 *   three events from validating three times and owing acknowledgements the
 *   donor does not send.
 *
 * WHICH CONTEXT AN EVENT NEEDS IS PROTOCOL KNOWLEDGE, and it is stated here
 * with set_ctx_lookup_info. A key alone cannot say: every flow id in this
 * program is a tuple of scalars, so a listener key and a connection key are the
 * same shape and only the program knows which it meant.
 */
unsigned
parse_tcp(const uint8_t *l4, uint16_t plen,
		const struct iphdr *iph, struct net_ev *ev, uint8_t *kinds,
		uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	struct TCPBP bp;
	if (TCPBP_extract(&bp, l4, plen) < 0)
		return 0;
	uint32_t payload_len;
	if ((((plen < 20) || ((bp.data_off * 4) < 20)) || ((bp.data_off * 4) > plen))) {
		return __n;
	}
	payload_len = (plen - (bp.data_off * 4));
	flowkey_t fid = ((flowkey_t){ .kind = 0, .v0 = iph->daddr, .v1 = iph->saddr, .v2 = bp.dst_port, .v3 = bp.src_port });
	flowkey_t lid = ((flowkey_t){ .kind = 1, .v0 = iph->daddr, .v1 = bp.dst_port });
	if (((((bp.flags & FLAG_SYN)) != 0) && (((bp.flags & FLAG_ACK)) == 0))) {
		ev->seq = bp.seq_no;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->has_ts = bp.__opt_ts_present;
		ev->wscale = bp.__opt_wscale_wscale;
		ev->has_wscale = bp.__opt_wscale_present;
		ev->local_ip = iph->daddr;
		ev->remote_ip = iph->saddr;
		(ev->__key_tcp_listen_ctx = lid, ev->__have_tcp_listen_ctx = true);
		kinds[__n++] = EV_tcp_syn;
		return __n;
	}
	ev->flags = bp.flags;
	ev->seq = bp.seq_no;
	ev->ack = bp.ack_seq;
	ev->payload_len = payload_len;
	ev->ts_val = bp.__opt_ts_ts_val;
	ev->has_ts = bp.__opt_ts_present;
	(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
	kinds[__n++] = EV_tcp_seg;
	if ((((bp.flags & FLAG_RST)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->sport = bp.src_port;
		ev->dport = bp.dst_port;
		ev->payload_len = payload_len;
		(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
		kinds[__n++] = EV_tcp_rst;
		return __n;
	}
	if ((((bp.flags & FLAG_SYN)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->ts_ecr = bp.__opt_ts_ts_ecr;
		ev->has_ts = bp.__opt_ts_present;
		ev->wscale = bp.__opt_wscale_wscale;
		ev->has_wscale = bp.__opt_wscale_present;
		(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
		kinds[__n++] = EV_tcp_synack;
		return __n;
	}
	if ((((bp.flags & FLAG_ACK)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->ts_ecr = bp.__opt_ts_ts_ecr;
		ev->payload_len = payload_len;
		(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
		(ev->__key_tcp_listen_ctx = lid, ev->__have_tcp_listen_ctx = true);
		kinds[__n++] = EV_tcp_ack;
	}
	if ((payload_len > 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->hold_addr = (struct mtp_addr){ .base = l4 + bp.data_off * 4, .len = (uint32_t)(plen - bp.data_off * 4) };
		ev->data_len = payload_len;
		(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
		kinds[__n++] = EV_tcp_data;
	}
	if ((((bp.flags & FLAG_FIN)) != 0)) {
		ev->seq = bp.seq_no;
		ev->ack = bp.ack_seq;
		ev->window = bp.window;
		ev->ts_val = bp.__opt_ts_ts_val;
		ev->payload_len = payload_len;
		(ev->__key_tcp_ctx = fid, ev->__have_tcp_ctx = true);
		kinds[__n++] = EV_tcp_fin;
	}
	return __n;
}

