/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#ifndef PROG_TYPES_H
#define PROG_TYPES_H
/*
 * Compiler output, from `flow_id tcp_fid`.
 *
 * SHAPE ONLY (CR-5). The positional names are the compiler's; they mean
 * nothing and nothing may read them as though they did. The PARSER
 * constructs the value and canonicalises direction, so an inbound packet
 * and an outbound application operation resolve the same context. That is
 * protocol logic; the compiler does not do it and the target must not.
 *
 * The target keys its store on the raw bytes and never reads a field, so
 * there is no hash or compare callback. Packed, because the key is
 * compared and hashed as bytes and padding would make two equal keys
 * differ.
 */
#include <stdint.h>

typedef struct __attribute__((packed)) {
	uint32_t v0;
	uint32_t v1;
	uint16_t v2;
	uint16_t v3;
} flowkey_t;

#endif /* PROG_TYPES_H */
