/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog.h"

#define TCPBP_FIXED_LEN	20

/*
 * Serialise the blueprint ONCE, when it is built -- not per segment. The
 * per-segment work is the recurrence in mtp_program_segment.
 */
uint16_t
TCPBP_build(uint8_t *out, const struct TCPBP *b)
{
	uint16_t hdr_len;

	memset(out, 0, TCPBP_FIXED_LEN);
	{ uint16_t w = htons(b->src_port); memcpy(out + 0, &w, 2); }
	{ uint16_t w = htons(b->dst_port); memcpy(out + 2, &w, 2); }
	{ uint32_t w = htonl(b->seq_no); memcpy(out + 4, &w, 4); }
	{ uint32_t w = htonl(b->ack_seq); memcpy(out + 8, &w, 4); }
	out[13] = b->flags;
	{ uint16_t w = htons(b->window); memcpy(out + 14, &w, 2); }
	{ uint16_t w = htons(b->urg_ptr); memcpy(out + 18, &w, 2); }
	memcpy(out + TCPBP_FIXED_LEN, b->__opt, b->__opt_len);
	hdr_len = (uint16_t)(TCPBP_FIXED_LEN + b->__opt_len);
	/* hdrlen4_t: a property of the layout, so the compiler fills it */
	out[12] = (uint8_t)((hdr_len / 4) << 4);
	return hdr_len;
}

void
TCPBP_add_opt_mss(struct TCPBP *b, uint16_t mss)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 2;
	*p++ = 4;
	{ uint16_t w = htons(mss); memcpy(p, &w, 2); p += 2; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_nop(struct TCPBP *b)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 1;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_ts(struct TCPBP *b, uint32_t ts_val, uint32_t ts_ecr)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 8;
	*p++ = 10;
	{ uint32_t w = htonl(ts_val); memcpy(p, &w, 4); p += 4; }
	{ uint32_t w = htonl(ts_ecr); memcpy(p, &w, 4); p += 4; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_wscale(struct TCPBP *b, uint8_t wscale)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 3;
	*p++ = 3;
	*p++ = wscale;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

int
TCPBP_extract(struct TCPBP *b, const uint8_t *in, uint16_t len)
{
	uint32_t i = 0, olen;

	memset(b, 0, sizeof(*b));	/* absent reads as absent */
	if (len < TCPBP_FIXED_LEN)
		return -1;
	{ uint16_t w; memcpy(&w, in + TCPBP_src_port_OFF, 2); b->src_port = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_dst_port_OFF, 2); b->dst_port = ntohs(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_seq_no_OFF, 4); b->seq_no = ntohl(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_ack_seq_OFF, 4); b->ack_seq = ntohl(w); }
	b->flags = in[TCPBP_flags_OFF];
	{ uint16_t w; memcpy(&w, in + TCPBP_window_OFF, 2); b->window = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_urg_ptr_OFF, 2); b->urg_ptr = ntohs(w); }
	b->data_off = (uint8_t)(in[TCPBP_data_off_OFF] >> 4);
	olen = (uint32_t)(b->data_off * 4);
	if (olen < TCPBP_FIXED_LEN || olen > len)
		return -1;
	olen -= TCPBP_FIXED_LEN;

	while (i < olen) {
		uint8_t kind = in[TCPBP_FIXED_LEN + i];

		if (kind == 0)			/* end of list: TERMINATES */
			return 0;
		if (kind == 1) { i++; continue; }	/* no-op */
		if (i + 1 >= olen)
			return 0;
		if (in[TCPBP_FIXED_LEN + i + 1] < 2)	/* a zero length would loop */
			return 0;
		if (kind == 2 && in[TCPBP_FIXED_LEN + i + 1] == 4 && i + 4 <= olen) {
			b->__opt_mss_present = true;
			{ uint16_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 2); b->__opt_mss_mss = ntohs(w); }
		}
		if (kind == 8 && in[TCPBP_FIXED_LEN + i + 1] == 10 && i + 10 <= olen) {
			b->__opt_ts_present = true;
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 4); b->__opt_ts_ts_val = ntohl(w); }
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 6, 4); b->__opt_ts_ts_ecr = ntohl(w); }
		}
		if (kind == 3 && in[TCPBP_FIXED_LEN + i + 1] == 3 && i + 3 <= olen) {
			b->__opt_wscale_present = true;
			b->__opt_wscale_wscale = in[TCPBP_FIXED_LEN + i + 2];
		}
		i += in[TCPBP_FIXED_LEN + i + 1];
	}
	return 0;
}

