/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
/*
 * The application-interface half: the socket operations this protocol
 * binds, and what they do. From `app_parser` (CR-7) -- the target defines
 * the op schema and this program maps the ops it needs. There is no
 * universal `send`.
 */
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog_params.h"
#include "prog_types.h"
#include "prog_ctx.h"

/*
 * The op's endpoint is in NETWORK order, as the schema declares; this program
 * works in host order once past the parser. Converting HERE rather than at the
 * comparison site keeps the one representation choice in one place — the two
 * being out of step is what made the listener never match and swallowed every
 * SYN silently.
 */
unsigned
sock_bind(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->ip = op->local.ip;
	ev->port = ntohs(op->local.port);
	ev->__key = key_of_listener(op->local.ip, ntohs(op->local.port));
	kinds[__n++] = EV_app_bind;
	return __n;
}

unsigned
sock_listen(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->ip = op->local.ip;
	ev->port = ntohs(op->local.port);
	ev->backlog = op->len;
	ev->__key = key_of_listener(op->local.ip, ntohs(op->local.port));
	kinds[__n++] = EV_app_listen;
	return __n;
}

unsigned
sock_accept(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->ip = op->local.ip;
	ev->port = ntohs(op->local.port);
	ev->__key = key_of_listener(op->local.ip, ntohs(op->local.port));
	kinds[__n++] = EV_app_accept;
	return __n;
}

/*
 * THE LOCAL PORT IS THE CALLER'S (B4): the donor allocates from a per-core
 * address pool in mtcp_connect and fails EAGAIN when exhausted, and whose job
 * that is in general is undecided — it is protocol policy in TCP and not
 * obviously so elsewhere. The op carries both endpoints for that reason.
 */
unsigned
sock_connect(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->loc_ip = op->local.ip;
	ev->rem_ip = op->remote.ip;
	ev->loc_port = ntohs(op->local.port);
	ev->rem_port = ntohs(op->remote.port);
	ev->__key = key_of_inbound(op->local.ip, op->remote.ip, ntohs(op->local.port), ntohs(op->remote.port));
	kinds[__n++] = EV_app_connect;
	return __n;
}

/*
 * TWO HALVES ON TWO THREADS (CR-4). The phase rides on the op because the
 * contract has one entry point; the program never branches on a thread, and the
 * generated dispatch branches on which half it was asked for, which is
 * knowledge the compiler has because it made the placement.
 *
 * A send with NO FLOW is the object posted before any connection exists, which
 * is how a one-shot server hands over what every accepted connection receives.
 * It is posted to a LISTENER, not to the process: with several listeners there
 * is no "the" listener to post to, which is why the op carries the endpoint.
 */
unsigned
sock_send(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	if ((((op->flags & MTP_OP_PHASE_RECORD)) != 0)) {
		ev->addr = op->data;
		ev->mlen = op->len;
		ev->ip = op->local.ip;
		ev->port = ntohs(op->local.port);
		if ((op->flow != NULL)) {
			ev->__flow = op->flow;
		} else {
			ev->__key = key_of_listener(op->local.ip, ntohs(op->local.port));
		}
		kinds[__n++] = EV_app_send;
	} else {
		ev->mlen = op->len;
		ev->__flow = op->flow;
		kinds[__n++] = EV_app_gen;
	}
	return __n;
}

/*
 * mtp/tcp.mtp §sock_recv
 * ---------------------------------------------------------------------------
 * The application drains. RECOMPUTE POINT 2 of §window_rule and the only reason
 * `recv` is bound at all: `delivered` advances by what the flush instruction
 * REPORTS it handed over — not by what the application asked for, which may be
 * more — and the advertised window reopens by exactly that much. The count
 * comes from the instruction's return value rather than from a target accessor,
 * which is what lets the program own `delivered` without the target exposing
 * its unit's occupancy. The work itself is §proc_drain.
 */
unsigned
parse_recv(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->buf = ((struct mtp_rx_addr){ .data = (const uint8_t *)(op->data.base), .len = op->len });
	ev->len = op->len;
	ev->__flow = op->flow;
	kinds[__n++] = EV_app_recv;
	return __n;
}

/*
 * mtp/tcp.mtp §sock_close
 * ---------------------------------------------------------------------------
 * The application has no more to send. THIS, AND NOT THE PEER'S FIN, IS WHAT
 * RELEASES OUR OWN FIN.
 *
 * D-20's per-path rule reaches teardown here. A peer's FIN closes the PEER's
 * path; ours stays open until this arrives, so CLOSE_WAIT is a state in which
 * the program still accepts writes, still generates segments, and still
 * processes returning acknowledgements. Gating any of those three on
 * ESTABLISHED alone silently discards a response to a request whose FIN arrived
 * with it — which is a request/response server's ordinary case, and was
 * invisible for as long as the object was posted before any connection existed.
 *
 * mtp/tcp.mtp §gen_fin is tried immediately rather than waiting for the next packet,
 * because if the peer has already finished, no further packet will arrive to
 * carry the attempt.
 */
unsigned
sock_close(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms)
{
	unsigned __n = 0;
	(void)now_ms;
	ev->__flow = op->flow;
	kinds[__n++] = EV_app_close;
	return __n;
}

int
mtp_program_app_op(struct mtp_app_op *op, uint32_t now_ms)
{
	uint8_t  kinds[EV_KIND__N];
	struct app_ev ev;
	unsigned n, i;

	memset(&ev, 0, sizeof(ev));
	switch (op->kind) {
	case MTP_APP_BIND:
		n = sock_bind(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_LISTEN:
		n = sock_listen(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_ACCEPT:
		n = sock_accept(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_CONNECT:
		n = sock_connect(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_SEND:
		n = sock_send(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_RECV:
		n = parse_recv(op, &ev, kinds, now_ms);
		break;
	case MTP_APP_CLOSE:
		n = sock_close(op, &ev, kinds, now_ms);
		break;
	default:
		return -1;	/* an op this program does not bind */
	}

	for (i = 0; i < n; i++) {
		switch (kinds[i]) {
		case EV_app_accept: {
			struct tcp_listen_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_accept(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_bind: {
			struct tcp_listen_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_bind(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_close: {
			struct tcp_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_close(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_connect: {
			struct tcp_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_connect(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_gen: {
			struct tcp_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_gen(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_listen: {
			struct tcp_listen_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_listen(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_recv: {
			struct tcp_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_recv(ctx, &ev, now_ms))
				return 0;
			break;
		}
		case EV_app_send: {
			struct tcp_ctx *ctx = ev.__flow ? mtp_ctx_of(ev.__flow)
						     : mtp_ctx_lookup(&ev.__key);
			if (!dispatch_app_send(ctx, &ev, now_ms))
				return 0;
			break;
		}
		default: break;
		}
	}

	/* CR-2: the handle the chain produced */
	if (ev.accepted)
		op->flow = ev.accepted;
	if (ev.opened)
		op->flow = ev.opened;
	/* ...and the count, which is the other half of the same need */
	return ev.result;
}
