/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#ifndef PROG_CTX_H
#define PROG_CTX_H
/*
 * Compiler output: the context and scratchpad structs, the event frames and
 * the blueprint, from this program's declarations.
 *
 * Under CR-3 the context IS this generated struct -- the target does not hand
 * out an opaque block and does not know what is in it.
 */
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog_params.h"
#include "prog_types.h"

/* which event a frame is carrying */
enum ev_kind {
	EV_app_accept,
	EV_app_bind,
	EV_app_close,
	EV_app_connect,
	EV_app_gen,
	EV_app_listen,
	EV_app_recv,
	EV_app_send,
	EV_tcp_ack,
	EV_tcp_data,
	EV_tcp_fin,
	EV_tcp_idle_timeout,
	EV_tcp_probe_timeout,
	EV_tcp_rst,
	EV_tcp_rto_timeout,
	EV_tcp_syn,
	EV_tcp_synack,
	EV_tcp_timewait_timeout,
	EV_KIND__N
};

/* every app_event of this program, as one frame */
struct app_ev {
	flow_t *accepted;
	struct mtp_tx_addr addr;
	uint32_t backlog;
	struct mtp_rx_addr buf;
	uint32_t ip;
	uint32_t len;
	uint32_t loc_ip;
	uint16_t loc_port;
	uint32_t mlen;
	flow_t *opened;
	uint16_t port;
	uint32_t rem_ip;
	uint16_t rem_port;
	int32_t result;
	flowkey_t __key;	/* set by the parser's set_flow_id */
	flow_t   *__flow;	/* set by set_flow, when the op names one */
};

/* every net_event of this program, as one frame */
struct net_ev {
	uint32_t ack;
	uint32_t data_len;
	uint16_t dport;
	bool has_ts;
	bool has_wscale;
	struct mtp_rx_addr hold_addr;
	uint32_t payload_len;
	uint32_t seq;
	uint16_t sport;
	uint32_t ts_ecr;
	uint32_t ts_val;
	uint16_t window;
	uint8_t wscale;
	flowkey_t __key;	/* set by the parser's set_flow_id */
	flow_t   *__flow;	/* set by set_flow, when the op names one */
};

/* every timer_event of this program, as one frame */
struct timer_ev {
	flowkey_t __key;	/* set by the parser's set_flow_id */
	flow_t   *__flow;	/* set by set_flow, when the op names one */
};

/*
 * The packet blueprint, from `pkt_bp TCPBP`.
 *
 * `hdrlen4_t` and `checksum16_t` are NOT fields: the first is filled by the
 * serialiser from the layout, the second is an offload request. A program
 * that computed either would be doing arithmetic over the compiler's own
 * layout.
 */
struct TCPBP {
	uint16_t src_port;
	uint16_t dst_port;
	uint32_t seq_no;
	uint32_t ack_seq;
	uint8_t data_off;
	uint8_t flags;
	uint16_t window;
	uint16_t urg_ptr;
	/* the option list, serialised IN THE ORDER THE PROGRAM CONSTRUCTS IT --
	 * the order is the parity item, so it is bytes and not a table a
	 * serialiser could reorder */
	uint8_t  __opt[PROG_OPT_MAX];
	uint16_t __opt_len;
	/* what the extractor found, so `absent` and `present and zero` are
	 * different -- PAWS turns on exactly that difference */
	bool     __opt_mss_present;
	uint16_t __opt_mss_mss;
	bool     __opt_nop_present;
	bool     __opt_ts_present;
	uint32_t __opt_ts_ts_val;
	uint32_t __opt_ts_ts_ecr;
	bool     __opt_wscale_present;
	uint8_t __opt_wscale_wscale;
	struct mtp_tx_payload __pay;
	uint32_t __mss;
};

struct tcp_ctx {
	flow_t *f;
	uint8_t state;
	uint16_t loc_port;
	uint16_t rem_port;
	uint32_t local_ip;
	uint32_t remote_ip;
	flowkey_t key;
	flowkey_t lst_key;
	bool has_lst;
	uint32_t snd_base;
	uint32_t send_una;
	uint32_t send_next;
	uint32_t write_end;
	uint32_t send_high;
	uint32_t send_wnd;
	uint8_t snd_wscale;
	uint32_t cwnd;
	uint32_t ssthresh;
	uint32_t snd_wl1;
	uint32_t snd_wl2;
	uint32_t right_wnd_edge;
	uint32_t last_ack_seq;
	uint32_t dup_acks;
	uint32_t rcv_base;
	uint32_t recv_next;
	struct mtp_sliding_wnd rx_wnd;
	uint32_t delivered;
	uint32_t rcv_wnd;
	bool need_wnd_adv;
	uint32_t ack_cnt;
	bool fin_consumed;
	uint32_t ts_recent;
	bool saw_timestamp;
	uint32_t last_ack_sent_ms;
	uint32_t srtt;
	uint32_t mdev;
	uint32_t rttvar;
	uint32_t rto_ms;
	bool have_rtt;
	uint32_t rtx_count;
	bool fin_pending;
	uint32_t fin_seq;
	bool app_closed;
	struct mtp_data_unit tx;
	struct mtp_data_unit rx;
	bool tx_open;
	bool rx_open;
	struct mtp_timer rto_timer;
	struct mtp_timer tw_timer;
	struct mtp_timer probe_timer;
	struct mtp_timer idle_timer;
};

#define TCP_CTX_INIT	{ .state = ST_CLOSED, .send_wnd = 65535, .cwnd = PARITY_INIT_CWND, .rcv_wnd = PARITY_INITIAL_WINDOW }

struct tcp_listen_ctx {
	flow_t *f;
	uint32_t local_ip;
	uint16_t local_port;
	uint8_t state;
	uint32_t pending_cap;
	uint32_t pending_n;
	flow_t *pending[PROG_MAX_BACKLOG];
	struct mtp_tx_addr obj;
	uint32_t obj_len;
};

#define TCP_LISTEN_CTX_INIT	{ .state = ST_CLOSED }

/*
 * Per-dispatch working state: one instance per event, discarded when the
 * chain ends.
 *
 * `__ctx_dead` is NOT declared by the program and is not protocol state: it
 * is how `del_ctx` ends the chain it was issued from. This target frees the
 * context immediately, so every later processor in the chain would read
 * freed memory; a target that deferred destruction would not need it.
 */
struct tcp_scratch {
	uint32_t acked;
	uint32_t delivered;
	uint8_t ack_opt;
	bool no_send;
	uint32_t pkts_sent;
	bool __ctx_dead;
};

/*
 * Prototypes. A program is written in the order a reader wants and its calls
 * run in every direction, so nothing depends on the order the declarations
 * happen to be in -- and the split across two .c files stays a presentation
 * choice rather than a linkage constraint.
 */
flowkey_t
key_of_inbound(uint32_t loc_ip, uint32_t rem_ip, uint16_t loc_port, uint16_t rem_port);
flowkey_t
key_of_listener(uint32_t loc_ip, uint16_t loc_port);
void
tcp_on_payload_merged(struct tcp_ctx *ctx, uint32_t new_recv_next);
void
sock_recv(struct tcp_ctx *ctx, uint32_t delivered_now);
void
recompute_rcv_wnd(struct tcp_ctx *ctx);
uint16_t
tcp_window_field(struct tcp_ctx *ctx, bool is_syn);
struct TCPBP
build_hdr(struct tcp_ctx *ctx, uint32_t seq, uint8_t flags, uint32_t now);
struct TCPBP
build_rst_hdr(uint16_t loc_port, uint16_t rem_port, uint32_t seq, uint32_t ack, uint8_t flags);
void
touch_idle(struct tcp_ctx *ctx);
bool
send_side_open(struct tcp_ctx *ctx);
bool
recv_side_open(struct tcp_ctx *ctx);
bool
conn_exists(struct tcp_ctx *ctx);
bool
unacked_on_wire(struct tcp_ctx *ctx);
void
arm_rto(struct tcp_ctx *ctx);
void
estimate_rtt(struct tcp_ctx *ctx, uint32_t now, uint32_t ts_ecr);
unsigned
parse_tcp(const uint8_t *l4, uint16_t plen,
		const struct iphdr *iph, struct net_ev *ev, uint8_t *kinds,
		void **ctx_out, uint32_t now_ms);
unsigned
sock_bind(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
sock_listen(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
sock_accept(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
sock_connect(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
sock_send(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
parse_recv(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
unsigned
sock_close(struct mtp_app_op *op, struct app_ev *ev,
		uint8_t *kinds, uint32_t now_ms);
bool
proc_validate(struct tcp_ctx *ctx, struct TCPBP bp, uint32_t payload_len);
void
gen_rst(uint32_t local_ip, uint32_t remote_ip, struct TCPBP seg, uint32_t payload_len);
void
gen_rst_from_ctx(struct tcp_ctx *ctx, uint32_t ack);
void
proc_passive_open(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_open_done(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_timestamp(struct net_ev *ev, struct tcp_ctx *ctx);
void
proc_window(struct net_ev *ev, struct tcp_ctx *ctx);
void
proc_rtt(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_fast_retransmit(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s);
void
proc_congestion(struct net_ev *ev, struct tcp_ctx *ctx);
void
proc_ack(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s);
void
proc_recv(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s);
void
owe_ack(struct tcp_ctx *ctx, uint8_t opt);
void
send_ack(struct tcp_ctx *ctx, struct tcp_scratch *s);
void
enter_time_wait(struct tcp_ctx *ctx);
void
proc_fin(struct net_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s);
void
gen_fin(struct tcp_ctx *ctx, uint32_t now_ms);
int32_t
fin_emit(struct tcp_ctx *ctx, bool rtx, uint32_t now_ms);
void
mark_closed(struct app_ev *ev, struct tcp_ctx *ctx);
void
record_data(struct app_ev *ev, struct tcp_ctx *ctx);
void
gen_seg(struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms);
void
drain_owed_acks(struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms);
void
gen_answer(struct app_ev *ev, struct tcp_ctx *ctx);
void
gen_wnd_adv(struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_drain(struct app_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s);
void
proc_rst(struct net_ev *ev, struct tcp_ctx *ctx);
void
gen_syn(struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_synack(struct net_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_rto(struct timer_ev *ev, struct tcp_ctx *ctx, struct tcp_scratch *s, uint32_t now_ms);
void
proc_timewait_done(struct timer_ev *ev, struct tcp_ctx *ctx);
void
proc_probe(struct timer_ev *ev, struct tcp_ctx *ctx, uint32_t now_ms);
void
proc_idle(struct timer_ev *ev, struct tcp_ctx *ctx);
void
proc_bind(struct app_ev *ev, struct tcp_listen_ctx *ctx);
void
proc_listen(struct app_ev *ev, struct tcp_listen_ctx *ctx);
void
proc_accept(struct app_ev *ev, struct tcp_listen_ctx *ctx);
void
proc_connect(struct app_ev *ev, struct tcp_ctx *ctx);
void
post_object(struct app_ev *ev, struct tcp_listen_ctx *ctx);
bool dispatch_tcp_syn(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_synack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_ack(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_data(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_fin(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_rst(struct tcp_ctx *ctx, struct net_ev *ev, uint32_t now_ms);
bool dispatch_tcp_rto_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms);
bool dispatch_tcp_timewait_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms);
bool dispatch_tcp_probe_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms);
bool dispatch_tcp_idle_timeout(struct tcp_ctx *ctx, struct timer_ev *ev, uint32_t now_ms);
bool dispatch_app_bind(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_listen(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_accept(struct tcp_listen_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_connect(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_recv(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_send(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_gen(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms);
bool dispatch_app_close(struct tcp_ctx *ctx, struct app_ev *ev, uint32_t now_ms);

#endif /* PROG_CTX_H */
