/* GENERATED by the MTP compiler's DPDK backend. Do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "contract.h"
#include "prog.h"

/*
 * pkt_bp -- the blueprint's serialiser, option writers and extractor.
 */

/*
 * Serialise the blueprint ONCE, when it is built -- not per segment. The
 * per-segment work is the recurrence in mtp_program_segment.
 */
uint16_t
TCPBP_build(uint8_t *out, const struct TCPBP *b)
{
	uint16_t hdr_len;

	memset(out, 0, TCPBP_FIXED_LEN);
	{ uint16_t w = htons(b->src_port); memcpy(out + 0, &w, 2); }
	{ uint16_t w = htons(b->dst_port); memcpy(out + 2, &w, 2); }
	{ uint32_t w = htonl(b->seq_no); memcpy(out + 4, &w, 4); }
	{ uint32_t w = htonl(b->ack_seq); memcpy(out + 8, &w, 4); }
	out[13] = b->flags;
	{ uint16_t w = htons(b->window); memcpy(out + 14, &w, 2); }
	{ uint16_t w = htons(b->urg_ptr); memcpy(out + 18, &w, 2); }
	memcpy(out + TCPBP_FIXED_LEN, b->__opt, b->__opt_len);
	hdr_len = (uint16_t)(TCPBP_FIXED_LEN + b->__opt_len);
	/* hdrlen4_t: a property of the layout, so the compiler fills it */
	out[12] = (uint8_t)((hdr_len / 4) << 4);
	return hdr_len;
}

void
TCPBP_add_opt_mss(struct TCPBP *b, uint16_t mss)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 2;
	*p++ = 4;
	{ uint16_t w = htons(mss); memcpy(p, &w, 2); p += 2; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_nop(struct TCPBP *b)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 1;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_ts(struct TCPBP *b, uint32_t ts_val, uint32_t ts_ecr)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 8;
	*p++ = 10;
	{ uint32_t w = htonl(ts_val); memcpy(p, &w, 4); p += 4; }
	{ uint32_t w = htonl(ts_ecr); memcpy(p, &w, 4); p += 4; }
	b->__opt_len = (uint16_t)(p - b->__opt);
}

void
TCPBP_add_opt_wscale(struct TCPBP *b, uint8_t wscale)
{
	uint8_t *p = b->__opt + b->__opt_len;
	*p++ = 3;
	*p++ = 3;
	*p++ = wscale;
	b->__opt_len = (uint16_t)(p - b->__opt);
}

int
TCPBP_extract(struct TCPBP *b, const uint8_t *in, uint16_t len)
{
	uint32_t i = 0, olen;

	memset(b, 0, sizeof(*b));	/* absent reads as absent */
	if (len < TCPBP_FIXED_LEN)
		return -1;
	{ uint16_t w; memcpy(&w, in + TCPBP_src_port_OFF, 2); b->src_port = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_dst_port_OFF, 2); b->dst_port = ntohs(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_seq_no_OFF, 4); b->seq_no = ntohl(w); }
	{ uint32_t w; memcpy(&w, in + TCPBP_ack_seq_OFF, 4); b->ack_seq = ntohl(w); }
	b->flags = in[TCPBP_flags_OFF];
	{ uint16_t w; memcpy(&w, in + TCPBP_window_OFF, 2); b->window = ntohs(w); }
	{ uint16_t w; memcpy(&w, in + TCPBP_urg_ptr_OFF, 2); b->urg_ptr = ntohs(w); }
	b->data_off = (uint8_t)(in[TCPBP_data_off_OFF] >> 4);
	olen = (uint32_t)(b->data_off * 4);
	if (olen < TCPBP_FIXED_LEN || olen > len)
		return -1;
	olen -= TCPBP_FIXED_LEN;

	while (i < olen) {
		uint8_t kind = in[TCPBP_FIXED_LEN + i];

		if (kind == 0)			/* end of list: TERMINATES */
			return 0;
		if (kind == 1) { i++; continue; }	/* no-op */
		if (i + 1 >= olen)
			return 0;
		if (in[TCPBP_FIXED_LEN + i + 1] < 2)	/* a zero length would loop */
			return 0;
		if (kind == 2 && in[TCPBP_FIXED_LEN + i + 1] == 4 && i + 4 <= olen) {
			b->__opt_mss_present = true;
			{ uint16_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 2); b->__opt_mss_mss = ntohs(w); }
		}
		if (kind == 8 && in[TCPBP_FIXED_LEN + i + 1] == 10 && i + 10 <= olen) {
			b->__opt_ts_present = true;
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 2, 4); b->__opt_ts_ts_val = ntohl(w); }
			{ uint32_t w; memcpy(&w, in + TCPBP_FIXED_LEN + i + 6, 4); b->__opt_ts_ts_ecr = ntohl(w); }
		}
		if (kind == 3 && in[TCPBP_FIXED_LEN + i + 1] == 3 && i + 3 <= olen) {
			b->__opt_wscale_present = true;
			b->__opt_wscale_wscale = in[TCPBP_FIXED_LEN + i + 2];
		}
		i += in[TCPBP_FIXED_LEN + i + 1];
	}
	return 0;
}

/*
 * mtp/tcp.mtp §build_hdr
 * ---------------------------------------------------------------------------
 * THE ONE PLACE AN OUTBOUND HEADER IS BUILT, and it is a program function
 * rather than compiler output because THREE PROTOCOL SIDE EFFECTS HANG OFF IT.
 *
 *   - every packet that acknowledges resets the window probe's clock. That is
 *     the donor's rule (tcp_out.c:293) and was not ours: ours stamped it only
 *     when a probe was emitted, so the gate measured the interval between
 *     probes and we probed where the donor would not;
 *   - the same line stamps the donor's activity clock (tcp_out.c:293-296, and
 *     again on every received packet at tcp_in.c:1292), which is what our idle
 *     timer restart stands in for;
 *   - D11 ARM. The donor sets need_wnd_adv when the SCALED FIELD it is about to
 *     put on the wire is zero (tcp_out.c:304-309) — not when rcv_wnd is small.
 */
struct TCPBP
build_hdr(struct tcp_ctx *ctx, uint32_t seq, uint8_t flags, uint32_t now)
{
	struct TCPBP bp = { 0 };
	bool is_syn = (((flags & FLAG_SYN)) != 0);
	if ((((flags & FLAG_ACK)) != 0)) {
		ctx->last_ack_sent_ms = now;
		if (((ctx->state != ST_CLOSED) && (ctx->state != ST_TIME_WAIT))) {
			(ctx->idle_timer).ctx = ctx;
			mtp_timer_start(&(ctx->idle_timer), ((uint64_t)(tcp_timeout) * 1000000000ULL));
		}
	}
	bp.src_port = ctx->loc_port;
	bp.dst_port = ctx->rem_port;
	bp.seq_no = seq;
	bp.ack_seq = ctx->recv_next;
	bp.flags = (PARITY_SET_PSH ? flags : ((flags & ~(FLAG_PSH))));
	bp.window = (is_syn ? (uint16_t)(ctx->rcv_wnd) : (uint16_t)((ctx->rcv_wnd >> PARITY_WSCALE)));
	bp.urg_ptr = 0;
	if ((bp.window == 0)) {
		ctx->need_wnd_adv = true;
	}
	if (is_syn) {
		TCPBP_add_opt_mss(&bp, PARITY_MSS_ADVERTISED);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_ts(&bp, now, ctx->ts_recent);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_wscale(&bp, PARITY_WSCALE);
	} else {
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_nop(&bp);
		TCPBP_add_opt_ts(&bp, now, ctx->ts_recent);
	}
	return bp;
}

/*
 * mtp/tcp.mtp §build_rst_hdr
 * ---------------------------------------------------------------------------
 * A reset's header, built WITHOUT A CONTEXT, because a reset for a connection
 * that does not exist has none. Ports come from the offending segment with the
 * halves swapped, and there are NO OPTIONS: the donor's SendTCPPacketStandalone
 * sends none on this path, and a timestamp echo would need a `ts_recent` we
 * have never had. The window is zero, because there is no receive buffer behind
 * a connection that does not exist, and the donor passes 0 at every standalone
 * site.
 */
struct TCPBP
build_rst_hdr(uint16_t loc_port, uint16_t rem_port, uint32_t seq, uint32_t ack, uint8_t flags)
{
	struct TCPBP bp = { 0 };
	bp.src_port = loc_port;
	bp.dst_port = rem_port;
	bp.seq_no = seq;
	bp.ack_seq = ack;
	bp.flags = flags;
	bp.window = 0;
	bp.urg_ptr = 0;
	return bp;
}
