#ifndef MTP_NET_H
#define MTP_NET_H

#include "mtcp.h"
#include "tcp_stream.h"



#ifndef MTP_ERROR
#define MTP_ERROR (-1)
#endif



/********************** MTP Network Interface **********************
 * This module implements MTP net RX and TX interfaces
 *
 * This module shoule be generated by the MTP compiler
 *******************************************************************/

// RX - Net interface
int MTP_ProcessTransportPacket(struct mtcp_manager *mtcp, uint32_t cur_ts, const int ifidx,
    const struct iphdr* iph, int ip_len);
// RX - App interface
void MTP_ProcessSendEvents(mtcp_manager_t mtcp, 
    struct mtcp_sender *sender, uint32_t cur_ts, int thresh);

// TX
int MTP_PacketGenList(mtcp_manager_t mtcp, 
    struct mtcp_sender *sender, uint32_t cur_ts, int thresh);


#endif
