#ifndef MTP_EP_H
#define MTP_EP_H

#include <netinet/ip.h>

#include "mtcp.h"
#include "tcp_stream.h"
#include "socket.h"

#define MTP_NO_EVENT -1
#define MTP_SYN 0


/********************** MTP EPs & Dispatcher **********************
 * This module implements MTP Event Processors(EP), corresponding
 * EP chains, and dispatcher for events. 
 * Each EP chain is one line in the dispatcher.
 * EPs should be static while EP chains should be globally exposed.
 *
 * This module shoule be generated by the MTP compiler
 ******************************************************************/

// Event Processor Chains
int mtp_recv_chain(mtcp_manager_t mtcp, tcp_stream *cur_stream, 
	char* buf, int len, socket_map_t socket);
int mtp_send_chain(mtcp_manager_t mtcp, tcp_stream *cur_stream, uint32_t cur_ts);
void mtp_ack_chain(mtcp_manager_t mtcp, uint32_t cur_ts, tcp_stream* cur_stream,
	struct tcphdr* tcph, uint32_t seq, uint32_t ack_seq, int payloadlen,
	uint32_t window);
void mtp_data_chain(mtcp_manager_t mtcp, tcp_stream *cur_stream, uint32_t cur_ts,
	uint32_t seq, uint8_t *payload, int payloadlen);
int mtp_listen_chain(mtcp_manager_t mtcp, int sockid, int backlog);
tcp_stream* mtp_accept_chain(mctx_t mctx, mtcp_manager_t mtcp, struct mtp_listen_ctx *ctx, 
	struct sockaddr *addr, socklen_t *addrlen);
void mtp_syn_chain(mtcp_manager_t mtcp, uint32_t cur_ts, uint32_t remote_ip, uint16_t remote_port, 
	uint32_t init_seq, uint16_t rwnd, uint32_t local_ip, uint16_t local_port,
	struct tcphdr* tcph, struct mtp_listen_ctx *ctx);


// Net RX parser
void parse_net_rx();	// parse net RX packet & modify contexts

// Net dispatcher
void dispatch_net_incoming();


// Net interfaces
// RX interface
int MTP_ProcessTransportPacket(struct mtcp_manager *mtcp, uint32_t cur_ts, const int ifidx,
    const struct iphdr* iph, int ip_len);
// TX interface
void MTP_ProcessSendEvents(mtcp_manager_t mtcp, 
    struct mtcp_sender *sender, uint32_t cur_ts, int thresh);

#endif
