#!/usr/bin/env python3
"""Generate a site's arp.conf and route.conf from the inventory.

Nothing about the cluster may be hard-coded in a script, because the move to
CloudLab is meant to be a config change rather than a port. That rule was being
broken quietly by a hand-maintained arp.conf: it listed two nodes, the inventory
has four, and the first run against a node that was not in the file would fail
in a way that looks like a transport bug.

The MAC addresses are not in the inventory (they are Phase 0 discovery fields),
so they are read off each node. That is the only thing this touches remotely,
and it is read-only.

    MTP_INVENTORY=<path> tools/gen_conf.py <site>

Writes conf/<site>/config/{arp,route}.conf. Both are committed, so a diff after
running it is the record of what changed on the testbed.
"""
import os
import subprocess
import sys

import yaml

SSH = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=8"]


def mac_of(host, iface):
    out = subprocess.run(SSH + [host, f"cat /sys/class/net/{iface}/address"],
                         capture_output=True, text=True, timeout=20)
    if out.returncode != 0:
        return None
    return out.stdout.strip() or None


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    site = sys.argv[1]

    inv_path = os.environ.get("MTP_INVENTORY")
    if not inv_path or not os.path.exists(inv_path):
        sys.exit("set MTP_INVENTORY to the inventory yaml "
                 "(it is gitignored and lives outside this repo)")

    inv = yaml.safe_load(open(inv_path))
    peers, routes, subnet, skipped = [], [], None, []

    for node in inv.get("nodes", []):
        nic = node.get("data_nic") or {}
        ip, iface = nic.get("ip"), nic.get("name") or nic.get("iface")
        if not ip or not iface:
            continue
        host = (node.get("ssh") or {}).get("host") or node.get("name")
        mac = mac_of(host, iface)
        if not mac:
            skipped.append(f"{node.get('name')} ({ip})")
            print(f"  ! {node.get('name')}: could not read {iface}'s MAC; skipped",
                  file=sys.stderr)
            continue
        peers.append((ip, mac, node.get("name")))
        subnet = subnet or (inv.get("network") or {}).get("data_plane_subnet")
        routes.append((ip, iface))

    if not peers:
        sys.exit("no usable nodes in the inventory")

    d = f"conf/{site}/config"
    os.makedirs(d, exist_ok=True)

    with open(f"{d}/arp.conf", "w") as f:
        f.write("# GENERATED by tools/gen_conf.py from the inventory. Do not edit.\n"
                "# Every data-plane node, so a run against any of them resolves.\n\n")
        if skipped:
            # In the file, not just on stderr: a node missing here fails later
            # as something that looks like a transport bug, and the log from
            # the generation run will be long gone.
            f.write("# UNREACHABLE WHEN GENERATED, so absent below:\n")
            for s_ in skipped:
                f.write(f"#   {s_}\n")
            f.write("\n")
        f.write(f"ARP_ENTRY {len(peers)}\n")
        for ip, mac, name in peers:
            f.write(f"{ip}/32 {mac}\t# {name}\n")

    iface = routes[0][1]
    with open(f"{d}/route.conf", "w") as f:
        f.write("# GENERATED by tools/gen_conf.py from the inventory. Do not edit.\n\n")
        f.write("ROUTES 1\n")
        f.write(f"{subnet or '10.7.0.0/24'} {iface}\n")

    print(f"wrote {d}/arp.conf ({len(peers)} entries) and {d}/route.conf")


if __name__ == "__main__":
    main()
